<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import type { VNode } from 'vue';
import { NSpace, NDataTable, NButton, NFormItem, NInput, NPagination, NSelect } from 'naive-ui';
import type { DataTableColumns } from 'naive-ui';
import moment from 'moment';
import {
  make_text_NButton,
  make_h_NSpace,
  h_tag,
  make_download_Abutton,
} from '@utility/NaiveHComponent.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { findLabel } from '@utility/OptionsTool.ts';
import { translate } from '@utility/i18n.ts';
import { GetOne, Delete, MultiPagedSearch, GetOptions } from '@request/Basic_Request.ts';
import { confirmDel } from '@common/message/confirmDel.ts';
import Layout_UMD from '@common/layoutIndi/Layout_UMD.vue';
import dict_silo_Form from './dict_silo_Form.vue';
import type { Dict_silo_Class, Dict_silo_Search } from '@entities/dict_silo.d.ts';
import {
  get_dict_silo_silo_type_options,
  get_dict_silo_silo_diameter_options,
} from './options_dict_silo.ts';

const itemName = 'Dict_silo';

//检索条件
const queryInfo = ref<Dict_silo_Search>({
  page: 1,
  pageSize: 15,
  silo_type: '',
  silo_diameter: '',
  silo_name: '',
  using_type: '',
  create_account: '',
  update_account: '',
});

const tableLoading = ref(false); //加载中
const columns = ref<DataTableColumns<Dict_silo_Class>>([]); //显示的列
const tableData = ref<Dict_silo_Class[]>([]); //表格数据
const totalCount = ref(0); //数据总数

const dict_silo_FormRef = useTemplateRef('dict_silo_FormRef'); //表单控件

const emit = defineEmits([]);
const inPara = defineProps({});

onMounted(() => {
  //注意，加载选项时可能需要异步处理
  //TODO,整理成异步形式
  refresh_dict_silo_silo_type_options();
  refresh_dict_silo_silo_diameter_options();
  resetColumns();
  initData();
});

//初始化数据
function initData() {
  tableLoading.value = true;
  MultiPagedSearch(queryInfo.value, itemName)
    .then((res) => {
      tableData.value = res.datas;
      totalCount.value = res.totalCount;
      tableLoading.value = false;
    })
    .catch((err) => console.error(err));
}

//重置列
function resetColumns() {
  columns.value = [
    //{
    //  key: '__index',
    //  title: translate.t('序号'),
    //  align: 'center',
    //  width: '50px',
    //  render(_row: Dict_silo_Class, index: number) {
    //      return index + 1;
    //  },
    //},
    {
      key: 'sort',
      title: translate.t('序号'),
      align: 'center',
      width: '50px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
    },
    //    {
    //      title: translate.t('主键Id'),
    //      key: 'id',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Dict_silo_Class, idx: number) {
    //        return val.id;
    //      },
    //    },
    {
      title: translate.t('库型'),
      key: 'silo_type',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return findLabel(dict_silo_silo_type_options.value, val.silo_type);
      },
    },
    {
      title: translate.t('直径'),
      key: 'silo_diameter',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return findLabel(dict_silo_silo_diameter_options.value, val.silo_diameter);
      },
    },
    {
      title: translate.t('库型名称'),
      key: 'silo_name',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.silo_name;
      },
    },
    {
      title: translate.t('库体直径'),
      key: 'diameter_val',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.diameter_val;
      },
    },
    {
      title: translate.t('使用类别'),
      key: 'using_type',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.using_type;
      },
    },
    {
      title: translate.t('参考项目'),
      key: 'projects',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.projects;
      },
    },
    //    {
    //      title: translate.t('创建账号'),
    //      key: 'create_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Dict_silo_Class, idx: number) {
    //        return val.create_account;
    //      },
    //    },
    {
      title: translate.t('创建人'),
      key: 'create_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.create_username;
      },
    },
    {
      title: translate.t('创建时间'),
      key: 'create_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return moment(val.create_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('更新账号'),
    //      key: 'update_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Dict_silo_Class, idx: number) {
    //        return val.update_account;
    //      },
    //    },
    {
      title: translate.t('更新人'),
      key: 'update_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return val.update_username;
      },
    },
    {
      title: translate.t('更新时间'),
      key: 'update_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Dict_silo_Class, idx: number) {
        return moment(val.update_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('备注'),
    //      key: 'remark',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Dict_silo_Class, idx: number) {
    //        return val.remark;
    //      },
    //    },
    {
      key: '__actions',
      title: translate.t('操作'),
      width: 160,
      render(row: Dict_silo_Class) {
        const opts: VNode[] = [];
        opts.push(make_text_NButton(translate.t('编辑'), () => editRow(row)));
        opts.push(
          make_text_NButton(translate.t('删除'), () => confirmDel(translate, () => delRow(row))),
        );
        //opts.push(make_text_NButton(translate.t('选中'), () => pickRow(row)));
        return make_h_NSpace(opts, 'start', false);
      },
    },
  ];
}

//高级查询
function queryList() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  initData();
}
//重置查询
function resetQuery() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  queryInfo.value.silo_type = '';
  queryInfo.value.silo_diameter = '';
  queryInfo.value.silo_name = '';
  queryInfo.value.using_type = '';
  queryInfo.value.create_account = '';
  queryInfo.value.update_account = '';
  initData();
}

//新任务
function newTask() {
  dict_silo_FormRef.value?.open('add', {} as Dict_silo_Class, []);
}

//编辑
function editRow(row: Dict_silo_Class) {
  GetOne(row.id, itemName).then((res) => {
    dict_silo_FormRef.value?.open('edit', res, []);
  });
}

//删除
function delRow(row: Dict_silo_Class) {
  Delete([row.id], itemName).then((res) => {
    executeRes(res, translate, () => {
      initData();
    });
  });
}
//翻页
function pageChange(page: number) {
  queryInfo.value.page = page;
  initData();
}
//改变页码
function pageSizeChange(pageSize: number) {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = pageSize;
  initData();
}

////选中行
//function pickRow(row: Dict_silo_Class) {
//    console.log(row.id);
//}

//dict_silo_silo_type选项
const dict_silo_silo_type_options = ref<{ label: string; value: number | string }[]>([]);
//刷新dict_silo_silo_type选项
function refresh_dict_silo_silo_type_options() {
  dict_silo_silo_type_options.value = get_dict_silo_silo_type_options(translate);
}

//dict_silo_silo_diameter选项
const dict_silo_silo_diameter_options = ref<{ label: string; value: number | string }[]>([]);
//刷新dict_silo_silo_diameter选项
function refresh_dict_silo_silo_diameter_options() {
  dict_silo_silo_diameter_options.value = get_dict_silo_silo_diameter_options(translate);
}
</script>

<template>
  <Layout_UMD>
    <template #header>
      <NSpace justify="space-between">
        <!-- 高级查询 -->
        <NSpace>
          <NFormItem :label="translate.t('库型')" label-placement="left">
            <NSelect
              filterable
              style="width: 200px"
              clearable
              v-model:value="queryInfo.silo_type"
              :options="dict_silo_silo_type_options"
            ></NSelect>
          </NFormItem>
          <NFormItem :label="translate.t('直径')" label-placement="left">
            <NSelect
              filterable
              style="width: 200px"
              clearable
              v-model:value="queryInfo.silo_diameter"
              :options="dict_silo_silo_diameter_options"
            ></NSelect>
          </NFormItem>
          <NFormItem :label="translate.t('库型名称')" label-placement="left">
            <NInput v-model:value="queryInfo.silo_name" />
          </NFormItem>
          <NFormItem :label="translate.t('使用类别')" label-placement="left">
            <NInput v-model:value="queryInfo.using_type" />
          </NFormItem>
          <!-- <NFormItem :label="translate.t('创建账号')" label-placement="left">
            <NInput v-model:value="queryInfo.create_account" />
          </NFormItem> -->
          <!-- <NFormItem :label="translate.t('更新账号')" label-placement="left">
            <NInput v-model:value="queryInfo.update_account" />
          </NFormItem> -->
          <NButton type="primary" @click="queryList">{{ translate.t('查询') }}</NButton>
          <NButton @click="resetQuery">{{ translate.t('重置') }}</NButton>
        </NSpace>
        <NSpace>
          <NButton type="primary" @click="newTask">
            {{ translate.t('添加') }}
          </NButton>
        </NSpace>
      </NSpace>
    </template>
    <template #list>
      <NDataTable
        ref="table"
        bordered
        striped
        :loading="tableLoading"
        :columns="columns"
        :data="tableData"
        :style="{ height: `100%` }"
        flex-height
      ></NDataTable>
    </template>
    <template #footer>
      <NSpace>
        <NPagination
          v-model:page="queryInfo.page"
          v-model:page-size="queryInfo.pageSize"
          :item-count="totalCount"
          show-size-picker
          :page-sizes="[15, 30, 45]"
          :on-update:page="pageChange"
          :on-update:page-size="pageSizeChange"
          :prefix="
            ({ itemCount }: { itemCount: number | undefined }) => {
              return translate.t('共') + ' ' + itemCount + ' ' + translate.t('条');
            }
          "
        />
      </NSpace>
    </template>
  </Layout_UMD>
  <dict_silo_Form ref="dict_silo_FormRef" @sheetDone="initData()"></dict_silo_Form>
</template>
<style scoped></style>
