// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20221130

using System;
using SqlSugar;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// Tenant业务类
/// </summary>
public class Tenant_Business : ITenant_Business
{
    private readonly static string CacheKey = "Tenant_AllData";
    private readonly ICache CacheFunc;
    private readonly IDBHelper dbHelper;

    /// <summary>
    /// 构造函数
    /// </summary>
    public Tenant_Business(ICache inDI, IDBHelper inDI2)
    {
        CacheFunc = inDI;
        dbHelper = inDI2;
    }

    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    public bool CreateTable()
    {
        try
        {
            dbHelper.GetDB("System").CodeFirst.InitTables<Tenant_Class>();
            return true;
        }
        catch (Exception)
        {
            throw;
        }
    }

    /////////////////////////////////////////////////////////// 
    //  以下为生成代码
    /////////////////////////////////////////////////////////// 

    #region 查询
    /// <summary> 
    /// 获取所有实体 
    /// </summary> 
    /// <returns></returns> 
    public List<Tenant_Class> GetAll()
    {
        var cacheData = CacheFunc.GetFromCache<List<Tenant_Class>>(CacheKey);
        if (cacheData == null || cacheData.Count < 1)
        {
            var newData = dbHelper.QueryList<Tenant_Class>("System");
            CacheFunc.Insert(CacheKey, newData);
            return newData;
        }
        else
        {
            return cacheData;
        }
    }

    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    /// <returns></returns>
    public int GetAllCount()
    {
        return dbHelper.QueryCount<Tenant_Class>("System", (x) => true);
    }

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    /// <param name="pageIndex"></param>
    /// <param name="pageSize"></param>
    /// <returns></returns>
    public (int TotalCount, List<Tenant_Class> Datas) GetAllPaged(int pageIndex, int pageSize)
    {
        return dbHelper.QueryPageList<Tenant_Class>("System",
            (x) => true, (x) => new
            {
                x.Id
            }, default, pageIndex, pageSize);
    }
    /// <summary> 
    /// 根据主键得到一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public List<Tenant_Class> GetByIds(Guid[] inSet)
    {
        return dbHelper.QueryByIds<Tenant_Class, Guid>("System", inSet);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public Tenant_Class GetOneFromAll(Guid id)
    {
        return GetAll().Find(p => p.Id == id);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public Tenant_Class GetOne(Guid id)
    {
        return dbHelper.QueryOne<Tenant_Class, Guid>("System", id);
    }

    /// <summary>
    /// 根据code查询
    /// </summary>
    /// <param name="inSearch_Code">查询字段</param>
    /// <returns></returns>
    public List<Tenant_Class> SearchBy_Code(string inSearch_Code)
    {
        return dbHelper.QueryListByClause<Tenant_Class>("System",
            (x) => x.Code == inSearch_Code,
            (x) => x.Code, default);
    }

    /// <summary>
    /// 根据create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    public List<Tenant_Class> SearchBy_Create_account(string inSearch_Create_account)
    {
        return dbHelper.QueryListByClause<Tenant_Class>("System",
            (x) => x.Create_account == inSearch_Create_account,
            (x) => x.Create_account, default);
    }

    /// <summary>
    /// 根据update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    public List<Tenant_Class> SearchBy_Update_account(string inSearch_Update_account)
    {
        return dbHelper.QueryListByClause<Tenant_Class>("System",
            (x) => x.Update_account == inSearch_Update_account,
            (x) => x.Update_account, default);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<Tenant_Class> MultiSearch(Tenant_Search inSearchModel)
    {
        var exp = Expressionable.Create<Tenant_Class>();
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Code)), x => x.Code.Contains(inSearchModel.Code));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Update_account)), x => x.Update_account.Contains(inSearchModel.Update_account));
        return dbHelper.QueryListByClause("System", exp.ToExpression(), x => x.Id);
    }
    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<Tenant_Class> BlurSearch(Tenant_Search inSearchModel)
    {
        var exp = Expressionable.Create<Tenant_Class>();
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Code)), x => x.Code.Contains(inSearchModel.Code));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Update_account)), x => x.Update_account.Contains(inSearchModel.Update_account));
        return dbHelper.QueryListByClause("System", exp.ToExpression(), x => x.Id);
    }
    #endregion 查询

    #region 添加
    /// <summary> 
    /// 添加一个实体 
    /// </summary> 
    /// <param name="inEntity"></param> 
    /// <returns></returns> 
    public bool Add(Tenant_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.AddOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 添加一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public int Add(List<Tenant_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.AddBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }
    #endregion 添加


    #region 修改
    /// <summary> 
    /// 修改一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param> 
    /// <returns></returns> 
    public bool Update(Tenant_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.UpdateOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 修改一批实体 
    /// </summary> 
    /// <param name="inSet">实体</param> 
    /// <returns></returns> 
    public int Update(List<Tenant_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.UpdateBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }
    #endregion 修改

    #region 删除
    /// <summary> 
    /// 删除一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param>
    /// <returns></returns> 
    public bool Delete(Tenant_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 删除一批实体 
    /// </summary> 
    /// <param name="inSet">实体集合</param>
    /// <returns></returns> 
    public int Delete(List<Tenant_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 根据主键删除一个实体 
    /// </summary> 
    /// <param name="inId">主键</param>
    /// <returns></returns> 
    public bool DeleteById(Guid inId)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteOneById<Tenant_Class, Guid>("System", inId);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 根据主键删除一批实体 
    /// </summary> 
    /// <param name="inArr">主键集合</param>
    /// <returns></returns> 
    public int DeleteByIds(Guid[] inArr)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteBatchByIds<Tenant_Class, Guid>("System", inArr);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    #endregion 删除
}
