// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// 适配VUE-i18n的语言包类
/// </summary>
public class LanDict
{
    /// <summary>
    /// 中文
    /// </summary>
    public Dictionary<string, string> ZH { get; set; }
    /// <summary>
    /// 德文
    /// </summary>
    public Dictionary<string, string> DE { get; set; }
    /// <summary>
    /// 俄文
    /// </summary>
    public Dictionary<string, string> RU { get; set; }
    /// <summary>
    /// 英文
    /// </summary>
    public Dictionary<string, string> EN { get; set; }

    /// <summary>
    /// 西班牙语
    /// </summary>
    public Dictionary<string, string> ES { get; set; }

    /// <summary>
    /// 葡萄牙语
    /// </summary>
    public Dictionary<string, string> PT { get; set; }
}

/// <summary>
/// 字典缓存
/// </summary>
public static class LanCache
{
    /// <summary>
    /// 字典缓存
    /// </summary>
    public static LanDict Dictionary { get; set; }
}
