<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import type { VNode } from 'vue';
import { NSpace, NDataTable, NButton, NFormItem, NInput, NPagination, NSelect } from 'naive-ui';
import type { DataTableColumns } from 'naive-ui';
import moment from 'moment';
import {
  make_text_NButton,
  make_h_NSpace,
  h_tag,
  make_download_Abutton,
} from '@utility/NaiveHComponent.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { findLabel } from '@utility/OptionsTool.ts';
import { translate } from '@utility/i18n.ts';
import { confirmDel } from '@common/message/confirmDel.ts';
import Layout_UMD from '@common/layoutIndi/Layout_UMD.vue';

import { GetAllLanguages, GetOne, Delete } from './req_language.ts';
import sys_language_Form from './sys_language_Form.vue';
import type { Sys_language_Class, Sys_language_Search } from './sys_language.d.ts';

// const itemName = 'Sys_language';

//检索条件
const queryInfo = ref<Sys_language_Search>({
  page: 1,
  pageSize: 15,
  key: '',
  create_account: '',
  update_account: '',
});

const tableLoading = ref(false); //加载中
const columns = ref<DataTableColumns<Sys_language_Class>>([]); //显示的列
const tableData = ref<Sys_language_Class[]>([]); //表格数据
const totalCount = ref(0); //数据总数

const sys_language_FormRef = useTemplateRef('sys_language_FormRef'); //表单控件
const emit = defineEmits([]);
const inPara = defineProps({});

onMounted(() => {
  resetColumns();
  initData();
});

//初始化数据
function initData() {
  tableLoading.value = true;
  GetAllLanguages(queryInfo.value.key)
    .then((res) => {
      tableData.value = res;
      totalCount.value = res.length;
      tableLoading.value = false;
    })
    .catch((err) => console.error(err));
}

//重置列
function resetColumns() {
  columns.value = [
    {
      key: '__index',
      title: translate.t('序号'),
      align: 'center',
      width: '50px',
      render(_row: Sys_language_Class, index: number) {
        return index + 1;
      },
    },
    {
      title: translate.t('中文'),
      key: 'key',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.key;
      },
    },
    // {
    //   title: translate.t('中文'),
    //   key: 'zh',
    //   width: '100px',
    //   ellipsis: {
    //     tooltip: true,
    //   },
    //   sorter: 'default',
    //   render(val: Sys_language_Class, idx: number) {
    //     return val.zh;
    //   },
    // },
    {
      title: translate.t('英文'),
      key: 'en',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.en;
      },
    },
    {
      title: translate.t('俄文'),
      key: 'ru',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.ru;
      },
    },
    {
      title: translate.t('德语'),
      key: 'de',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.de;
      },
    },
    {
      title: translate.t('西语'),
      key: 'es',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.es;
      },
    },
    {
      title: translate.t('葡语'),
      key: 'pt',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.pt;
      },
    },
    //    {
    //      title: translate.t('创建账号'),
    //      key: 'create_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Sys_language_Class, idx: number) {
    //        return val.create_account;
    //      },
    //    },
    {
      title: translate.t('创建人'),
      key: 'create_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.create_username;
      },
    },
    {
      title: translate.t('创建时间'),
      key: 'create_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return moment(val.create_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('更新账号'),
    //      key: 'update_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Sys_language_Class, idx: number) {
    //        return val.update_account;
    //      },
    //    },
    {
      title: translate.t('更新人'),
      key: 'update_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return val.update_username;
      },
    },
    {
      title: translate.t('更新时间'),
      key: 'update_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Sys_language_Class, idx: number) {
        return moment(val.update_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('备注'),
    //      key: 'remark',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Sys_language_Class, idx: number) {
    //        return val.remark;
    //      },
    //    },
    {
      key: '__actions',
      title: translate.t('操作'),
      width: 160,
      render(row: Sys_language_Class) {
        const opts: VNode[] = [];
        opts.push(make_text_NButton(translate.t('编辑'), () => editRow(row)));
        opts.push(
          make_text_NButton(translate.t('删除'), () => confirmDel(translate, () => delRow(row))),
        );
        //opts.push(make_text_NButton(translate.t('选中'), () => pickRow(row)));
        return make_h_NSpace(opts, 'start', false);
      },
    },
  ];
}

//高级查询
function queryList() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  initData();
}
//重置查询
function resetQuery() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  queryInfo.value.key = '';
  queryInfo.value.create_account = '';
  queryInfo.value.update_account = '';
  initData();
}

//新任务
function newTask() {
  sys_language_FormRef.value?.open('add', {} as Sys_language_Class, []);
}

//编辑
function editRow(row: Sys_language_Class) {
  GetOne(row.key).then((res) => {
    sys_language_FormRef.value?.open('edit', res, []);
  });
}

//删除
function delRow(row: Sys_language_Class) {
  Delete([row.key]).then((res) => {
    executeRes(res, translate, () => {
      initData();
    });
  });
}
function importLanguages() {
  window.$message.info(translate.t('敬请期待'));
}
// //翻页
// function pageChange(page: number) {
//   queryInfo.value.page = page;
//   initData();
// }
// //改变页码
// function pageSizeChange(pageSize: number) {
//   queryInfo.value.page = 1;
//   queryInfo.value.pageSize = pageSize;
//   initData();
// }

////选中行
//function pickRow(row: Sys_language_Class) {
//    console.log(row.id);
//}
</script>

<template>
  <Layout_UMD>
    <template #header>
      <NSpace justify="space-between">
        <!-- 高级查询 -->
        <NSpace>
          <NFormItem :label="translate.t('中文')" label-placement="left">
            <NInput v-model:value="queryInfo.key" />
          </NFormItem>
          <!-- <NFormItem :label="translate.t('创建账号')" label-placement="left">
            <NInput v-model:value="queryInfo.create_account" />
          </NFormItem> -->
          <!-- <NFormItem :label="translate.t('更新账号')" label-placement="left">
            <NInput v-model:value="queryInfo.update_account" />
          </NFormItem> -->
          <NButton type="primary" @click="queryList">{{ translate.t('查询') }}</NButton>
          <NButton @click="resetQuery">{{ translate.t('重置') }}</NButton>
        </NSpace>
        <NSpace>
          <NButton type="primary" @click="newTask">
            {{ translate.t('添加') }}
          </NButton>
          <NButton type="primary" @click="importLanguages">
            {{ translate.t('导入') }}
          </NButton>
        </NSpace>
      </NSpace>
    </template>
    <template #list>
      <NDataTable
        ref="table"
        bordered
        striped
        :loading="tableLoading"
        :columns="columns"
        :data="tableData"
        :style="{ height: `100%` }"
        flex-height
      ></NDataTable>
    </template>
    <template #footer>
      <NSpace>
        {{ translate.t('共') + ' ' + totalCount + ' ' + translate.t('条') }}
        <!-- <NPagination
          v-model:page="queryInfo.page"
          v-model:page-size="queryInfo.pageSize"
          :item-count="totalCount"
          show-size-picker
          :page-sizes="[15, 30, 45]"
          :on-update:page="pageChange"
          :on-update:page-size="pageSizeChange"
          :prefix="
            ({ itemCount }: { itemCount: number | undefined }) => {
              return translate.t('共') + ' ' + (itemCount || 0) + ' ' + translate.t('条');
            }
          "
        /> -->
      </NSpace>
    </template>
  </Layout_UMD>
  <sys_language_Form ref="sys_language_FormRef" @sheetDone="initData()"></sys_language_Form>
</template>
<style scoped></style>
