<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import {
  NSpace,
  NButton,
  NInput,
  NForm,
  NModal,
  NGrid,
  NFormItemGi,
  NSelect,
  NInputNumber,
  NDynamicTags,
  NDatePicker,
} from 'naive-ui';
//import moment from 'moment';
import { Add, Update } from './req_language.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { translate } from '@utility/i18n.ts';
import type { LabelValueArray } from '../../types/kv.d.ts';
import type { Sys_language_Class } from './sys_language.d.ts';

// const itemName = 'Sys_language';

const sheetData = ref<Sys_language_Class>({} as Sys_language_Class); //表单数据
const dialogShow = ref(false); //表单显隐
const formRef = useTemplateRef('formRef'); //表单控件
const formState = ref<'add' | 'edit'>('add'); //表单状态add,edit
//表单规则
const sheetRules = {};

defineExpose({ open });
const emit = defineEmits(['sheetDone']);
const inPara = defineProps({});

onMounted(() => {});

//表单开启
function open(openType: 'add' | 'edit', data: Sys_language_Class, []: LabelValueArray[]) {
  formState.value = openType;
  sheetData.value = data;
  dialogShow.value = true;
}

//表单完成
function formDone(res: { status?: boolean; message?: string }) {
  executeRes(res, translate, () => {
    emit('sheetDone');
    dialogShow.value = false;
  });
}

//提交
function btnSubmit() {
  formRef.value
    ?.validate((errors: any) => {
      if (!errors) {
        sheetData.value.zh = sheetData.value.key;
        if (formState.value == 'add') {
          Add(sheetData.value).then((res) => {
            formDone(res);
          });
        } else {
          Update(sheetData.value).then((res) => {
            formDone(res);
          });
        }
      }
    })
    .catch((err: Error) => {
      window.$message.warning(err.message);
    });
}

//取消
function btnCancel() {
  sheetData.value = {} as Sys_language_Class;
  dialogShow.value = false;
}
</script>

<template>
  <NModal
    :title="formState == 'add' ? translate.t('新增') : translate.t('编辑')"
    v-model:show="dialogShow"
    preset="card"
    :style="{ width: '60%' }"
    :segmented="{ footer: 'soft' }"
    :on-after-leave="btnCancel"
  >
    <NForm
      ref="formRef"
      :rules="sheetRules"
      :model="sheetData"
      label-placement="left"
      :label-width="120"
      require-mark-placement="right-hanging"
      size="medium"
    >
      <NGrid :cols="24" :x-gap="24">
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('中文做Key')" path="key">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('中文做Key')"
              v-model:value="sheetData.key"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('中文')" path="zh">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('中文')"
            v-model:value="sheetData.zh"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('英文')" path="en">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('英文')"
            v-model:value="sheetData.en"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('俄文')" path="ru">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('俄文')"
            v-model:value="sheetData.ru"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('德语')" path="de">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('德语')"
            v-model:value="sheetData.de"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('西班牙语')" path="es">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('西班牙语')"
            v-model:value="sheetData.es"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('葡萄牙语')" path="pt">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('葡萄牙语')"
            v-model:value="sheetData.pt"
          />
        </NFormItemGi>
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('创建账号')" path="create_account">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('创建账号')"
              v-model:value="sheetData.create_account"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('创建人姓名')" path="create_username">
          <NInput
            disabled
            :placeholder="translate.t('请输入') + ' ' + translate.t('创建人姓名')"
            v-model:value="sheetData.create_username"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('创建时间')" path="create_time">
          <NDatePicker
            disabled
            style="width: 100%"
            type="datetime"
            v-model:value="sheetData.create_time"
            :placeholder="translate.t('请输入') + ' ' + translate.t('创建时间')"
          />
        </NFormItemGi>
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('更新账号')" path="update_account">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('更新账号')"
              v-model:value="sheetData.update_account"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('更新人姓名')" path="update_username">
          <NInput
            disabled
            :placeholder="translate.t('请输入') + ' ' + translate.t('更新人姓名')"
            v-model:value="sheetData.update_username"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('更新时间')" path="update_time">
          <NDatePicker
            disabled
            style="width: 100%"
            type="datetime"
            v-model:value="sheetData.update_time"
            :placeholder="translate.t('请输入') + ' ' + translate.t('更新时间')"
          />
        </NFormItemGi>
        <NFormItemGi :span="24" :label="translate.t('备注')" path="remark">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('备注')"
            v-model:value="sheetData.remark"
          />
        </NFormItemGi>
      </NGrid>
    </NForm>
    <template #footer>
      <NSpace justify="center">
        <NButton type="primary" @click="btnSubmit">{{ translate.t('提交') }}</NButton>
        <NButton type="primary" @click="btnCancel">{{ translate.t('取消') }}</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
<style scoped></style>
