// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126
 
using OfficeOpenXml;
using System.Collections.Generic;
using System.Drawing;
using System;
using System.IO;
using System.Linq;
using OfficeOpenXml.Drawing;

namespace TPFun_Excel
{
    /// <summary>
    /// 单元格
    /// </summary>
    public class CellDraw
    {
        /// <summary>
        /// 起始行号
        /// </summary>
        public int StartRow { get; set; }

        /// <summary>
        /// 起始列号
        /// </summary>
        public int StartCol { get; set; }


        /// <summary>
        /// 起始行偏移
        /// </summary>
        public int StartRowOffset { get; set; }

        /// <summary>
        /// 起始列偏移
        /// </summary>
        public int StartColOffset { get; set; }

        ///// <summary>
        ///// 图片高度
        ///// </summary>
        //public int HeightPX { get; set; }

        ///// <summary>
        ///// 图片宽度
        ///// </summary>
        //public int WidthPX { get; set; }

        /// <summary>
        /// 起始行号
        /// </summary>
        public int EndRow { get; set; }

        /// <summary>
        /// 起始列号
        /// </summary>
        public int EndCol { get; set; }


        /// <summary>
        /// 起始行偏移
        /// </summary>
        public int EndRowOffset { get; set; }

        /// <summary>
        /// 起始列偏移
        /// </summary>
        public int EndColOffset { get; set; }



        /// <summary>
        /// 内容
        /// </summary>
        public string ImgBase64 { get; set; }

        /// <summary>
        /// 图名
        /// </summary>
        public string ImgName { get; set; }


        /// <summary>
        /// 图设置
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetDrawToSheet(ExcelWorksheet worksheet)
        {
            var bytes = Convert.FromBase64String(ImgBase64);
            MemoryStream stream = new MemoryStream(bytes);
            var image = Image.FromStream(stream);
            var graphUnit = GraphicsUnit.Pixel;

            #region log

            Console.WriteLine("------------------------------");
            Console.WriteLine("图片准备添加");
            Console.WriteLine(ImgName);
            Console.WriteLine("图片宽高：" + image.Width.ToString() + "," + image.Height.ToString());
            Console.WriteLine("Bounds：" + image.GetBounds(ref graphUnit).ToString());
            Console.WriteLine("物理Dimension：" + image.PhysicalDimension.ToString());
            Console.WriteLine("开始位置：" + StartRow + "," + StartCol);
            Console.WriteLine("结束位置：" + EndRow + "," + EndCol);
            Console.WriteLine("开始偏差：" + (StartRowOffset * 9525) + "," + (StartColOffset * 9525));
            Console.WriteLine("结束偏差：" + (EndRowOffset * 9525) + "," + (EndColOffset * 9525));
            Console.WriteLine("工作簿范围：" + worksheet.Dimension.Address);
             
            #endregion log

            try
            {
                var picture = worksheet.Drawings.AddPicture(ImgName, image);
                Console.WriteLine("图片已添加");

                picture.From.Row = StartRow;
                picture.From.Column = StartCol;
                picture.From.RowOff = StartRowOffset * 9525;
                picture.From.ColumnOff = StartColOffset * 9525;

                picture.To.Row = EndRow;
                picture.To.Column = EndCol;
                picture.To.RowOff = EndRowOffset * 9525;
                picture.To.ColumnOff = EndColOffset * 9525;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.WriteLine("------------------------------");

        }

        /// <summary>
        /// 读取worksheet上的图
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<CellDraw> ReadPictures(ExcelWorksheet worksheet)
        {
            var draws = worksheet.Drawings.ToList();

            var pictures = new List<CellDraw>();

            foreach (var item in draws)
            {
                var draw = new CellDraw();
                draw.StartRow = item.From.Row;
                draw.StartCol = item.From.Column;
                draw.StartRowOffset = item.From.RowOff / 9525;
                draw.StartColOffset = item.From.ColumnOff / 9525;

                draw.EndRow = item.To.Row;
                draw.EndCol = item.To.Column;
                draw.EndRowOffset = item.To.RowOff / 9525;
                draw.EndColOffset = item.To.ColumnOff / 9525;

                var pic = item as ExcelPicture;

                if (pic != null)
                {
                    //draw.WidthPX = pic.Image.Width;
                    //draw.HeightPX = pic.Image.Height;

                    var ms = new MemoryStream();
                    pic.Image.Save(ms, pic.ImageFormat);
                    byte[] arr = new byte[ms.Length];
                    ms.Position = 0;
                    ms.Read(arr, 0, (int)ms.Length);
                    ms.Close();
                    var content = Convert.ToBase64String(arr);
                    draw.ImgBase64 = content;
                }

                draw.ImgName = item.Name;

                pictures.Add(draw);
            }
            return pictures;
        }

    }

}
