// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Security.Cryptography.X509Certificates;

namespace TPFun_Excel
{
    /// <summary>
    /// 单元格样式
    /// </summary>
    public class CellStyle
    {
        /// <summary>
        /// 开始行号
        /// </summary>
        public int StartRow { get; set; }

        /// <summary>
        /// 开始列号
        /// </summary>
        public int StartCol { get; set; }

        /// <summary>
        /// 结束行号
        /// </summary>
        public int EndRow { get; set; }

        /// <summary>
        /// 结束列号
        /// </summary>
        public int EndCol { get; set; }


        /// <summary>
        /// 字体
        /// </summary>
        public string Font { get; set; }

        /// <summary>
        /// 字体颜色
        /// </summary>
        public string FontColor { get; set; }

        /// <summary>
        /// 字号
        /// </summary>
        public int Size { get; set; }

        /// <summary>
        /// 是否加粗
        /// </summary>
        public bool UseBold { get; set; }

        /// <summary>
        /// 是否斜体
        /// </summary>
        public bool UseItalic { get; set; }

        /// <summary>
        /// 是否下划线
        /// </summary>
        public bool UseUnderLine { get; set; }

        /// <summary>
        /// 是否删除线
        /// </summary>
        public bool UseStrike { get; set; }

        /// <summary>
        /// 是否自动换行
        /// </summary>
        public bool UseWrapText { get; set; }

        /// <summary>
        /// 水平对齐
        /// </summary>
        public string HorizontalAlignment { get; set; }

        /// <summary>
        /// 垂直对齐
        /// </summary>
        public string VerticalAlignment { get; set; }


        /// <summary>
        /// 设置单元格样式
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetCellStyleToSheet(ExcelWorksheet worksheet)
        {
            try
            {
                var range = worksheet.Cells[StartRow, StartCol, EndRow, EndCol];
                range.Style.Font.Name = Font;
                range.Style.Font.Size = Size;
                range.Style.Font.Bold = UseBold;
                range.Style.Font.Italic = UseItalic;
                range.Style.Font.UnderLine = UseUnderLine;
                range.Style.Font.Strike = UseStrike;
                range.Style.Font.Color.SetColor(StyleCommon.CastColorFromStr(FontColor));

                range.Style.HorizontalAlignment = CastHorizontalAlignmentFromStr(HorizontalAlignment);
                range.Style.VerticalAlignment = CastVerticalAlignmentFromStr(VerticalAlignment);

                range.Style.WrapText = UseWrapText; //自动换行 
            }
            catch (Exception ex)
            {
                string error = ex.ToString();
            }

        }


        /// <summary>
        /// 水平对齐，文本转枚举
        /// </summary>
        /// <param name="HorizontalAlignmentStr"></param>
        /// <returns></returns>
        private static ExcelHorizontalAlignment CastHorizontalAlignmentFromStr(string HorizontalAlignmentStr)
        {
            switch (HorizontalAlignmentStr)
            {
                case "General":
                    return ExcelHorizontalAlignment.General;
                case "Left":
                    return ExcelHorizontalAlignment.Left;
                case "Center":
                    return ExcelHorizontalAlignment.Center;
                case "CenterContinuous":
                    return ExcelHorizontalAlignment.CenterContinuous;
                case "Right":
                    return ExcelHorizontalAlignment.Right;
                case "Fill":
                    return ExcelHorizontalAlignment.Fill;
                case "Distributed":
                    return ExcelHorizontalAlignment.Distributed;
                case "Justify":
                    return ExcelHorizontalAlignment.Justify;
                default:
                    return ExcelHorizontalAlignment.General;
            }
        }


        /// <summary>
        /// 垂直对齐，文本转枚举
        /// </summary>
        /// <param name="VerticalAlignmentStr"></param>
        /// <returns></returns>
        private static ExcelVerticalAlignment CastVerticalAlignmentFromStr(string VerticalAlignmentStr)
        {
            switch (VerticalAlignmentStr)
            {
                case "Top":
                    return ExcelVerticalAlignment.Top;
                case "Center":
                    return ExcelVerticalAlignment.Center;
                case "Bottom":
                    return ExcelVerticalAlignment.Bottom;
                case "Distributed":
                    return ExcelVerticalAlignment.Distributed;
                case "Justify":
                    return ExcelVerticalAlignment.Justify;
                default:
                    return ExcelVerticalAlignment.Bottom;
            }
        }

        /// <summary>
        /// 去读样式
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<CellStyle> ReadCellStyle(ExcelWorksheet worksheet)
        {
            var res = new List<CellStyle>();

            var cells = worksheet.Cells;

            foreach (var cell in cells)
            {
                var style = new CellStyle();
                style.StartRow = cell.Start.Row;
                style.StartCol = cell.Start.Column;
                style.EndRow = cell.End.Row;
                style.EndCol = cell.End.Column;
                style.Font = cell.Style.Font.Name;
                var tempColor = cell.Style.Font.Color.Rgb;

                if ( string.IsNullOrEmpty(tempColor) || tempColor.Length < 2)
                {
                    style.FontColor = "#000000";
                }
                else
                {
                    style.FontColor = "#" + tempColor.Substring(2);
                }

                style.Size = (int)cell.Style.Font.Size;
                style.UseBold = cell.Style.Font.Bold;
                style.UseItalic = cell.Style.Font.Italic;
                style.UseUnderLine = cell.Style.Font.UnderLine;
                style.UseStrike = cell.Style.Font.Strike;
                style.UseWrapText = cell.Style.WrapText;
                style.HorizontalAlignment = cell.Style.HorizontalAlignment.ToString();
                style.VerticalAlignment = cell.Style.VerticalAlignment.ToString();

                res.Add(style);
            }

            return res;
        }

    }

    /// <summary>
    /// Merge
    /// </summary>
    public class RangeMerge
    {
        /// <summary>
        /// 开始行号
        /// </summary>
        public int StartRow { get; set; }

        /// <summary>
        /// 开始列号
        /// </summary>
        public int StartCol { get; set; }

        /// <summary>
        /// 结束行号
        /// </summary>
        public int EndRow { get; set; }

        /// <summary>
        /// 结束列号
        /// </summary>
        public int EndCol { get; set; }
        /// <summary>
        /// 是否合并
        /// </summary>
        public bool IsMerged { get; set; }

        /// <summary>
        /// 设置Merge
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetMergeToSheet(ExcelWorksheet worksheet)
        {
            try
            {
                var range = worksheet.Cells[StartRow, StartCol, EndRow, EndCol];
                range.Merge = IsMerged;
            }
            catch (Exception ex)
            {
                var error = ex.ToString();
            }



        }

        /// <summary>
        /// 读取合并单元格
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<RangeMerge> ReadMerges(ExcelWorksheet worksheet)
        {
            var mergedCells = worksheet.MergedCells;
            var mergeList = new List<RangeMerge>();
            foreach (var address in mergedCells)  //string  A10:C10 这个式样的
            {
                var range = worksheet.Cells[address];
                mergeList.Add(new RangeMerge()
                {
                    IsMerged = true,
                    StartRow = range.Start.Row,
                    StartCol = range.Start.Column,
                    EndRow = range.End.Row,
                    EndCol = range.End.Column
                });
            }
            return mergeList;
        }
    }


    /// <summary>
    /// 边框样式
    /// </summary>
    public class BorderStyle
    {
        /// <summary>
        /// 边框形式
        /// OutLine，在范围内设置Range的上下左右
        /// Single，在范围内设置每个格的上下左右
        /// </summary>
        public string CellType { get; set; }

        /// <summary>
        /// 开始行号
        /// </summary>
        public int StartRow { get; set; }

        /// <summary>
        /// 开始列号
        /// </summary>
        public int StartCol { get; set; }

        /// <summary>
        /// 结束行号
        /// </summary>
        public int EndRow { get; set; }

        /// <summary>
        /// 结束列号
        /// </summary>
        public int EndCol { get; set; }

        /// <summary>
        /// 边框样式_上
        /// </summary>
        public string StyleName_Top { get; set; }

        /// <summary>
        /// 边框颜色_上
        /// </summary>
        public string BorderColor_Top { get; set; }

        /// <summary>
        /// 边框样式_下
        /// </summary>
        public string StyleName_Bottom { get; set; }

        /// <summary>
        /// 边框颜色_下
        /// </summary>
        public string BorderColor_Bottom { get; set; }

        /// <summary>
        /// 边框样式_左
        /// </summary>
        public string StyleName_Left { get; set; }

        /// <summary>
        /// 边框颜色_右
        /// </summary>
        public string BorderColor_Left { get; set; }

        /// <summary>
        /// 边框样式_右
        /// </summary>
        public string StyleName_Right { get; set; }

        /// <summary>
        /// 边框颜色_右
        /// </summary>
        public string BorderColor_Right { get; set; }


        /// <summary>
        /// 设置边框样式
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetBorderStyleToSheet(ExcelWorksheet worksheet)
        {
            var range = worksheet.Cells[StartRow, StartCol, EndRow, EndCol];

            if (CellType == "OutLine")
            {
                range.Style.Border.BorderAround(StyleCommon.CastBorderStyleFromStr(StyleName_Top),
                                                StyleCommon.CastColorFromStr(BorderColor_Top));
            }
            else
            {
                range.Style.Border.Top.Style = StyleCommon.CastBorderStyleFromStr(StyleName_Top);
                range.Style.Border.Bottom.Style = StyleCommon.CastBorderStyleFromStr(StyleName_Bottom);
                range.Style.Border.Left.Style = StyleCommon.CastBorderStyleFromStr(StyleName_Left);
                range.Style.Border.Right.Style = StyleCommon.CastBorderStyleFromStr(StyleName_Right);

                if (range.Style.Border.Top.Style != ExcelBorderStyle.None)
                {
                    range.Style.Border.Top.Color.SetColor(StyleCommon.CastColorFromStr(BorderColor_Top));
                }

                if (range.Style.Border.Bottom.Style != ExcelBorderStyle.None)
                {
                    range.Style.Border.Bottom.Color.SetColor(StyleCommon.CastColorFromStr(BorderColor_Bottom));
                }

                if (range.Style.Border.Left.Style != ExcelBorderStyle.None)
                {
                    range.Style.Border.Left.Color.SetColor(StyleCommon.CastColorFromStr(BorderColor_Left));
                }

                if (range.Style.Border.Right.Style != ExcelBorderStyle.None)
                {
                    range.Style.Border.Right.Color.SetColor(StyleCommon.CastColorFromStr(BorderColor_Right));
                }
            }


        }

        /// <summary>
        /// 读取边框样式
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<BorderStyle> ReadBorderStyle(ExcelWorksheet worksheet)
        {
            var list = new List<BorderStyle>();

            var cells = worksheet.Cells;

            foreach (var cell in cells)
            {
                var border = new BorderStyle();
                border.StartRow = cell.Start.Row;
                border.StartCol = cell.Start.Column;
                border.EndRow = cell.End.Row;
                border.EndCol = cell.End.Column;
                border.StyleName_Top = cell.Style.Border.Top.Style.ToString();
                border.StyleName_Bottom = cell.Style.Border.Bottom.Style.ToString();
                border.StyleName_Left = cell.Style.Border.Left.Style.ToString();
                border.StyleName_Right = cell.Style.Border.Right.Style.ToString();

                border.BorderColor_Top = LookupColor(cell.Style.Border.Top.Color.Rgb);
                border.BorderColor_Bottom = LookupColor(cell.Style.Border.Bottom.Color.Rgb);
                border.BorderColor_Left = LookupColor(cell.Style.Border.Left.Color.Rgb);
                border.BorderColor_Right = LookupColor(cell.Style.Border.Right.Color.Rgb);

                list.Add(border);
            }
            return list;
        }

        private static string LookupColor(string rgb)
        {
            if (string.IsNullOrEmpty(rgb) || rgb.Length < 2)
            {
                return "#000000";
            }
            else
            {
                return "#" + rgb.Substring(2);
            }
        }

    }


    /// <summary>
    /// 行样式
    /// </summary>
    public class RowStyle
    {
        /// <summary>
        /// 行号
        /// </summary>
        public int RowNum { get; set; }

        /// <summary>
        /// 行高
        /// </summary>
        public double Height { get; set; }

        /// <summary>
        /// 设置行高
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetHeight(ExcelWorksheet worksheet)
        {
            worksheet.Row(RowNum).Height = Height;

        }


        /// <summary>
        /// 处理行高
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<RowStyle> ReadRowStyle(ExcelWorksheet worksheet)
        {
            var res = new List<RowStyle>();
            if (worksheet.Dimension == null)
            {
                return res;
            }

            int rowStart = worksheet.Dimension.Start.Row;
            int rowEnd = worksheet.Dimension.End.Row;

            for (int i = rowStart; i <= rowEnd; i++)
            {
                var row = worksheet.Row(i);
                var rowStyle = new RowStyle();
                rowStyle.RowNum = i;
                rowStyle.Height = row.Height;
                res.Add(rowStyle);
            }

            return res;
        }

    }

    /// <summary>
    /// 列样式
    /// </summary>
    public class ColStyle
    {
        /// <summary>
        /// 列号
        /// </summary>
        public int ColNum { get; set; }

        /// <summary>
        /// 列宽
        /// </summary>
        public double Width { get; set; }

        /// <summary>
        /// 设置列宽
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetWidth(ExcelWorksheet worksheet)
        {
            worksheet.Column(ColNum).Width = Width;
        }

        /// <summary>
        /// 处理列宽
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static List<ColStyle> ReadColStyle(ExcelWorksheet worksheet)
        {
            var res = new List<ColStyle>();
            if (worksheet.Dimension == null)
            {
                return res;
            }

            int colStart = worksheet.Dimension.Start.Column;
            int colEnd = worksheet.Dimension.End.Column;

            for (int i = colStart; i <= colEnd; i++)
            {
                var col = worksheet.Column(i);
                var colStyle = new ColStyle();
                colStyle.ColNum = i;
                colStyle.Width = col.Width;
                res.Add(colStyle);
            }

            return res;
        }
    }

    /// <summary>
    /// 样式的一些通用方法
    /// </summary>
    public class StyleCommon
    {
        /// <summary>
        /// 边框样式，文本转枚举
        /// </summary>
        /// <param name="BorderStyle"></param>
        /// <returns></returns>
        public static ExcelBorderStyle CastBorderStyleFromStr(string BorderStyle)
        {
            switch (BorderStyle)
            {
                case "None":
                    return ExcelBorderStyle.None;
                case "Hair":
                    return ExcelBorderStyle.Hair;
                case "Dotted":
                    return ExcelBorderStyle.Dotted;
                case "DashDot":
                    return ExcelBorderStyle.DashDot;
                case "Thin":
                    return ExcelBorderStyle.Thin;
                case "DashDotDot":
                    return ExcelBorderStyle.DashDotDot;
                case "Dashed":
                    return ExcelBorderStyle.Dashed;
                case "MediumDashDotDot":
                    return ExcelBorderStyle.MediumDashDotDot;
                case "MediumDashed":
                    return ExcelBorderStyle.MediumDashed;
                case "MediumDashDot":
                    return ExcelBorderStyle.MediumDashDot;
                case "Thick":
                    return ExcelBorderStyle.Thick;
                case "Medium":
                    return ExcelBorderStyle.Medium;
                case "Double":
                    return ExcelBorderStyle.Double;
                default:
                    return ExcelBorderStyle.None;
            }
        }


        /// <summary>
        /// 颜色，文本转System.Drawing.Color
        /// </summary>
        /// <param name="ColorCode"></param>
        /// <returns></returns>
        public static Color CastColorFromStr(string ColorCode)
        {
            if (!ColorCode.StartsWith("#"))
            {
                return Color.Black;
            }
            if (ColorCode.Length != 7 &&
                ColorCode.Length != 9)
            {
                return Color.Black;
            }

            var arr = ColorCode.ToCharArray();
            var r = "00";
            var g = "00";
            var b = "00";
            var a = "00";

            for (int i = 0; i < arr.Length; i++)
            {
                if (i == 1 || i == 2)
                {
                    r += arr[i];
                }
                if (i == 3 || i == 4)
                {
                    g += arr[i];
                }
                if (i == 5 || i == 6)
                {
                    b += arr[i];
                }
                if (i == 7 || i == 8)
                {
                    a += arr[i];
                }
            }

            int rr = Convert.ToInt32(r, 16);
            int gg = Convert.ToInt32(g, 16);
            int bb = Convert.ToInt32(b, 16);
            int aa = Convert.ToInt32(a, 16);

            return Color.FromArgb(aa, rr, gg, bb);
        }
    }
}
