// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using OfficeOpenXml;

namespace TPFun_Excel
{
    /// <summary>
    /// 打印设置
    /// </summary>
    public class PrintSetting
    {
        /// <summary>
        /// 适配单页
        /// </summary>
        public bool FitToPage { get; set; }

        /// <summary>
        /// 打印适配宽还是高
        /// </summary>
        public string FitType { get; set; }

        /// <summary>
        /// 方向
        /// </summary>
        public string Direction { get; set; }

        /// <summary>
        /// 是否设置打印区域
        /// </summary>
        public bool SetPrintArea { get; set; }

        /// <summary>
        /// 打印范围,开始行
        /// </summary>
        public int PrintRowStart { get; set; }

        /// <summary>
        /// 打印范围,结束行
        /// </summary>
        public int PrintRowEnd { get; set; }
        /// <summary>
        /// 打印范围,开始列
        /// </summary>
        public int PrintColStart { get; set; }
        /// <summary>
        /// 打印范围,结束列
        /// </summary>
        public int PrintColEnd { get; set; }

        /// <summary>
        /// 打印设置
        /// </summary>
        /// <param name="worksheet"></param> 
        public void SetPrintToSheet(ExcelWorksheet worksheet)
        {
            var print = worksheet.PrinterSettings;


            if (FitToPage)
            {
                if (FitType == "FitToHeight")
                {
                    print.FitToPage = true;
                    print.FitToHeight = 0;
                }
                if (FitType == "FitToWidth")
                {
                    print.FitToPage = true;
                    print.FitToWidth = 0;
                }
            }
            else
            {
                print.FitToPage = false;
            }

            if (Direction == "Landscape")
            {
                print.Orientation = eOrientation.Landscape; //Landscape横向，Portrait纵向
            }

            if (Direction == "Portrait")
            {
                print.Orientation = eOrientation.Portrait; //Landscape横向，Portrait纵向
            }

            print.PrintArea = null;

            if (SetPrintArea)
            {
                print.PrintArea = worksheet.Cells[PrintRowStart, PrintColStart, PrintRowEnd, PrintColEnd];
            }

        }

        /// <summary>
        /// 读取打印配置
        /// </summary>
        /// <param name="worksheet"></param>
        /// <returns></returns>
        public static PrintSetting ReadPrintSetting(ExcelWorksheet worksheet)
        {
            var printSettings = worksheet.PrinterSettings;

            var res = new PrintSetting();

            res.FitToPage = printSettings.FitToPage;

            if (printSettings.FitToPage)
            {
                if (printSettings.FitToHeight == 0)
                {
                    res.FitType = "FitToHeight";
                }
                if (printSettings.FitToWidth == 0)
                {
                    res.FitType = "FitToWidth";
                }
            }

            res.Direction = printSettings.Orientation.ToString();

            if (printSettings.PrintArea != null)
            {
                res.SetPrintArea = true;
                res.PrintRowStart = printSettings.PrintArea.Start.Row;
                res.PrintRowEnd = printSettings.PrintArea.End.Row;
                res.PrintColStart = printSettings.PrintArea.Start.Column;
                res.PrintColEnd = printSettings.PrintArea.End.Column;
            }
            else
            {
                res.SetPrintArea = false;
            }


            return res;
        }

    }

}
