// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System.Collections.Generic;

namespace TPFun_Excel
{
    /// <summary>
    /// excel文件
    /// </summary>
    public class XlsxFile
    {
        /// <summary>
        /// 文件名
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// 文件的单元格集合
        /// </summary>
        public List<Cell> Cells { get; set; } = new List<Cell>();

    }
}
