<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import type { VNode } from 'vue';
import { NSpace, NDataTable, NButton, NFormItem, NInput, NPagination, NSelect } from 'naive-ui';
import type { DataTableColumns } from 'naive-ui';
import moment from 'moment';
import {
  make_text_NButton,
  make_h_NSpace,
  h_tag,
  make_download_Abutton,
} from '@utility/NaiveHComponent.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { findLabel } from '@utility/OptionsTool.ts';
import { translate } from '@utility/i18n.ts';
import { GetOne, Delete, MultiPagedSearch, GetOptions } from '@request/Basic_Request.ts';
import { confirmDel } from '@common/message/confirmDel.ts';
import Layout_UMD from '@common/layoutIndi/Layout_UMD.vue';
import task_base_Form from './task_base_Form.vue';
import type { Task_base_Class, Task_base_Search } from '@entities/task_base.d.ts';
import {
  get_task_base_status_options,
} from './options_task_base.ts';

const itemName = 'Task_base';

//检索条件
const queryInfo = ref<Task_base_Search>({
  page: 1,
  pageSize: 15,
  task_title: '',
  create_account: '',
  update_account: '',
});

const tableLoading = ref(false); //加载中
const columns = ref<DataTableColumns<Task_base_Class>>([]); //显示的列
const tableData = ref<Task_base_Class[]>([]); //表格数据
const totalCount = ref(0); //数据总数

const task_base_FormRef = useTemplateRef('task_base_FormRef'); //表单控件

const emit = defineEmits([]);
const inPara = defineProps({});

onMounted(() => {
  //注意，加载选项时可能需要异步处理
  //TODO,整理成异步形式
  refresh_task_base_status_options();
  refresh_dict_silo_options(() => {});
  resetColumns();
  initData();
});

//初始化数据
function initData() {
  tableLoading.value = true;
  MultiPagedSearch(queryInfo.value, itemName)
    .then((res) => {
      tableData.value = res.datas;
      totalCount.value = res.totalCount;
      tableLoading.value = false;
    })
    .catch((err) => console.error(err));
}

//重置列
function resetColumns() {
  columns.value = [
    {
      key: '__index',
      title: translate.t('序号'),
      align: 'center',
      width: '50px',
      render(_row: Task_base_Class, index: number) {
        return index + 1;
      },
    },
    //    {
    //      title: translate.t('Id'),
    //      key: 'id',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Task_base_Class, idx: number) {
    //        return val.id;
    //      },
    //    },
    {
      title: translate.t('任务标题'),
      key: 'task_title',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.task_title;
      },
    },
    {
      title: translate.t('库型'),
      key: 'silo_type',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return findLabel(dict_silo_options.value, val.silo_type);
      },
    },
    {
      title: translate.t('储库直径'),
      key: 'silo_diameter',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.silo_diameter;
      },
    },
    {
      title: translate.t('库底板高度'),
      key: 'silo_height',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.silo_height;
      },
    },
    {
      title: translate.t('项目基点x'),
      key: 'task_x',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.task_x;
      },
    },
    {
      title: translate.t('项目基点y'),
      key: 'task_y',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.task_y;
      },
    },
    {
      title: translate.t('项目基点z'),
      key: 'task_z',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.task_z;
      },
    },
    {
      title: translate.t('旋转角度'),
      key: 'rotation_angle',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.rotation_angle;
      },
    },
    {
      title: translate.t('状态'),
      key: 'status',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return findLabel(task_base_status_options.value, val.status);
      },
    },
    {
      title: translate.t('错误信息'),
      key: 'error_msg',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.error_msg;
      },
    },
    //    {
    //      title: translate.t('创建账号'),
    //      key: 'create_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Task_base_Class, idx: number) {
    //        return val.create_account;
    //      },
    //    },
    {
      title: translate.t('创建人'),
      key: 'create_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.create_username;
      },
    },
    {
      title: translate.t('创建时间'),
      key: 'create_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return moment(val.create_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('更新账号'),
    //      key: 'update_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Task_base_Class, idx: number) {
    //        return val.update_account;
    //      },
    //    },
    {
      title: translate.t('更新人'),
      key: 'update_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return val.update_username;
      },
    },
    {
      title: translate.t('更新时间'),
      key: 'update_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Task_base_Class, idx: number) {
        return moment(val.update_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    //    {
    //      title: translate.t('备注'),
    //      key: 'remark',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Task_base_Class, idx: number) {
    //        return val.remark;
    //      },
    //    },
    {
      key: '__actions',
      title: translate.t('操作'),
      width: 160,
      render(row: Task_base_Class) {
        const opts: VNode[] = [];
        opts.push(make_text_NButton(translate.t('编辑'), () => editRow(row)));
        opts.push(
          make_text_NButton(translate.t('删除'), () => confirmDel(translate, () => delRow(row))),
        );
        //opts.push(make_text_NButton(translate.t('选中'), () => pickRow(row)));
        return make_h_NSpace(opts, 'start', false);
      },
    },
  ];
}

//高级查询
function queryList() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  initData();
}
//重置查询
function resetQuery() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  queryInfo.value.task_title = '';
  queryInfo.value.create_account = '';
  queryInfo.value.update_account = '';
  initData();
}

//新任务
function newTask() {
  task_base_FormRef.value?.open('add', {} as Task_base_Class, [dict_silo_options.value]);
}

//编辑
function editRow(row: Task_base_Class) {
  GetOne(row.id, itemName).then((res) => {
    task_base_FormRef.value?.open('edit', res, [dict_silo_options.value]);
  });
}

//删除
function delRow(row: Task_base_Class) {
  Delete([row.id], itemName).then((res) => {
    executeRes(res, translate, () => {
      initData();
    });
  });
}
//翻页
function pageChange(page: number) {
  queryInfo.value.page = page;
  initData();
}
//改变页码
function pageSizeChange(pageSize: number) {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = pageSize;
  initData();
}

////选中行
//function pickRow(row: Task_base_Class) {
//    console.log(row.id);
//}

//task_base_status选项
const task_base_status_options = ref<{ label: string; value: number | string }[]>([]);
//刷新task_base_status选项
function refresh_task_base_status_options() {
  task_base_status_options.value = get_task_base_status_options(translate);
}

//dict_silo选项
const dict_silo_options = ref<{ label: string; value: number | string }[]>([]);
function refresh_dict_silo_options(cb: () => void) {
  GetOptions('Dict_silo').then((res) => {
    dict_silo_options.value = res;
    cb();
  });
}
</script>

<template>
  <Layout_UMD>
    <template #header>
      <NSpace justify="space-between">
        <!-- 高级查询 -->
        <NSpace>
          <NFormItem :label="translate.t('任务标题')" label-placement="left">
            <NInput v-model:value="queryInfo.task_title" />
          </NFormItem>
          <!-- <NFormItem :label="translate.t('创建账号')" label-placement="left">
            <NInput v-model:value="queryInfo.create_account" />
          </NFormItem> -->
          <!-- <NFormItem :label="translate.t('更新账号')" label-placement="left">
            <NInput v-model:value="queryInfo.update_account" />
          </NFormItem> -->
          <NButton type="primary" @click="queryList">{{ translate.t('查询') }}</NButton>
          <NButton @click="resetQuery">{{ translate.t('重置') }}</NButton>
        </NSpace>
        <NSpace>
          <NButton type="primary" @click="newTask">
            {{ translate.t('添加') }}
          </NButton>
        </NSpace>
      </NSpace>
    </template>
    <template #list>
      <NDataTable
        ref="table"
        bordered
        striped
        :loading="tableLoading"
        :columns="columns"
        :data="tableData"
        :style="{ height: `100%` }"
        flex-height
      ></NDataTable>
    </template>
    <template #footer>
      <NSpace>
        <NPagination
          v-model:page="queryInfo.page"
          v-model:page-size="queryInfo.pageSize"
          :item-count="totalCount"
          show-size-picker
          :page-sizes="[15, 30, 45]"
          :on-update:page="pageChange"
          :on-update:page-size="pageSizeChange"
          :prefix="
            ({ itemCount }: { itemCount: number | undefined }) => {
              return translate.t('共') + ' ' + itemCount + ' ' + translate.t('条');
            }
          "
        />
      </NSpace>
    </template>
  </Layout_UMD>
  <task_base_Form ref="task_base_FormRef" @sheetDone="initData()"></task_base_Form>
</template>
<style scoped></style>
