// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System; 

namespace T2ACore;

/// <summary>
/// 通用配置
/// </summary>
public static class Common
{
    /// <summary>
    /// 服务启动时间
    /// </summary>
    public static DateTime ServerStartTime { get; set; }

    /// <summary>
    /// 起始时间 1970-1-1
    /// </summary>
    public static DateTime StartTime { get; set; }
    /// <summary>
    /// 静态文件路径
    /// </summary>
    public static string CurrentWWWPath { get; set; }
    /// <summary>
    /// 服务路径
    /// </summary>
    public static string CurrentDllPath { get; set; }
    /// <summary>
    /// 文件夹层级字符
    /// linux 为 / win 为 \\
    /// </summary>
    public static string LevelStr { get; set; }
    /// <summary>
    /// 换行字符
    /// linux 为 \n win 为 \r\n
    /// </summary>
    public static string EnterStr { get; set; }

}
