// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Security.Cryptography;
using System.Text;

namespace T2ACore;

/// <summary>
/// 通用方法
/// </summary>
public static class FunCommon
{
    /// <summary>
    /// 处理Id、parentId迁移问题
    /// </summary>
    /// <param name="guid"></param>
    /// <param name="timestamp"></param>
    /// <param name="random">随机数，0,1,2。代表替换guid中间(四位数)中的哪一个</param>
    /// <returns></returns>
    public static Guid CYL_GuidChanger(Guid guid, string timestamp, int random)
    {
        try
        {
            long key = Convert.ToInt64(timestamp);
            string strGuid = guid.ToString();

            string prefixChange = strGuid[..8];
            string middle0Change = strGuid[9..13];
            string middle1Change = strGuid[14..18];
            string middle2Change = strGuid[19..23];
            string suffixChange = strGuid[24..];

            long middle0ChangeRes = 0;
            long middle1ChangeRes = 0;
            long middle2ChangeRes = 0;

            switch (random)
            {
                case 0:
                    middle0ChangeRes = Convert.ToInt64(middle0Change, 16) ^ key;
                    middle1ChangeRes = Convert.ToInt64(middle1Change, 16);
                    middle2ChangeRes = Convert.ToInt64(middle2Change, 16);
                    break;

                case 1:
                    middle0ChangeRes = Convert.ToInt64(middle0Change, 16);
                    middle1ChangeRes = Convert.ToInt64(middle1Change, 16) ^ key;
                    middle2ChangeRes = Convert.ToInt64(middle2Change, 16);
                    break;

                case 2:
                    middle0ChangeRes = Convert.ToInt64(middle0Change, 16);
                    middle1ChangeRes = Convert.ToInt64(middle1Change, 16);
                    middle2ChangeRes = Convert.ToInt64(middle2Change, 16) ^ key;
                    break;

                default:
                    break;
            }

            long prefixChangeRes = Convert.ToInt64(prefixChange, 16) ^ key;
            long suffixChangeRes = Convert.ToInt64(suffixChange, 16) ^ key;

            string resStr = prefixChangeRes.ToString("X") +
                            middle0ChangeRes.ToString("X") +
                            middle1ChangeRes.ToString("X") +
                            middle2ChangeRes.ToString("X") +
                            suffixChangeRes.ToString("X");
            resStr = resStr[..32].PadRight(32, 'A');
            resStr = resStr.Insert(8, "-").Insert(13, "-").Insert(18, "-").Insert(23, "-");
            return new Guid(resStr);
        }
        catch (Exception ex)
        {
            string error = ex.ToString();
            return Guid.Empty;
        }
    }

    /// <summary>
    /// 生成有序Guid
    /// wrx 20221029 added
    /// </summary>
    /// <returns></returns>
    public static Guid MakeSortedGuid()
    {
        try
        {
            var now = DateTime.Now;
            var yyyy = now.ToString("yyyy");
            var MM = now.ToString("MM");
            var dd = now.ToString("dd");
            var HH = now.ToString("HH");
            var mm = now.ToString("mm");
            var ss = now.ToString("ss");
            var fff = now.ToString("ffffff");
            var ff1 = fff[..4];
            var ff2 = fff[4..];
            var rand = GetRandomAF09(10);
            var idStr = "CE" + yyyy + MM + "-" + dd + HH + "-" + mm + ss + "-" + ff1 + "-" + ff2 + rand;

            return Guid.Parse(idStr);
        }
        catch (Exception ex)
        {
            string error = ex.ToString();
            return Guid.NewGuid();
        }

    }

    /// <summary>
    /// 生成随机字符串,包括大小写字母和数字
    /// wrx 20221029 added
    /// </summary>
    /// <param name="n">位数</param>
    /// <param name="Number">数字</param>
    /// <param name="Lowercase">小写字母</param>
    /// <param name="Capital">大写字母</param>
    /// <returns></returns>
    public static string GetRandomCharacters(int n = 10,
        bool Number = true, bool Lowercase = false, bool Capital = false)
    {
        StringBuilder tmp = new();
        Random rand = new();
        string characters =
            (Capital ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ" : null) +
            (Number ? "0123456789" : null) +
            (Lowercase ? "abcdefghijklmnopqrstuvwxyz" : null);
        if (characters.Length < 1)
        {
            return null;
        }
        for (int i = 0; i < n; i++)
        {
            tmp.Append(characters[rand.Next(0, characters.Length)]);
        }
        return tmp.ToString();
    }


    /// <summary>
    /// 生成随机字符串ABCDEF0123456789
    /// wrx 20221116 added
    /// </summary>
    /// <param name="n">位数</param> 
    /// <returns></returns>
    public static string GetRandomAF09(int n = 10)
    {
        StringBuilder tmp = new();
        Random rand = new();
        string characters = "ABCDEF0123456789";
        if (characters.Length < 1)
        {
            return null;
        }
        for (int i = 0; i < n; i++)
        {
            tmp.Append(characters[rand.Next(0, characters.Length)]);
        }
        return tmp.ToString();
    }


    /// <summary>
    /// 计算字符串Hash
    /// </summary>
    /// <param name="base64String"></param>
    /// <returns></returns>
    public static string CalculateHash(string base64String)
    {
        byte[] bytes = Convert.FromBase64String(base64String);
        using (SHA256 sha256Hash = SHA256.Create())
        {
            byte[] hashBytes = sha256Hash.ComputeHash(bytes);
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < hashBytes.Length; i++)
            {
                builder.Append(hashBytes[i].ToString("x2"));
            }
            return builder.ToString();
        }
    }

    /// <summary>
    /// 安全截取
    /// </summary>
    /// <param name="input"></param>
    /// <param name="maxLength"></param>
    /// <returns></returns>
    public static string SafeSubstring(string input, int maxLength = 100)
    {
        if (string.IsNullOrEmpty(input))
        {
            return input;
        }

        return input.Length <= maxLength ? input : input.Substring(0, maxLength);
    }


    /// <summary>
    /// 获取标准时间戳，
    /// 以1970-1-1 0点为基准到当前UTC时间的时间戳
    /// </summary>
    /// <returns></returns>
    public static long GetStandardTimeStamp()
    {
        // 创建Unix纪元时间（1970-01-01 00:00:00 UTC）
        //DateTime epochTime = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        // 计算当前时间与纪元时间的时间差
        TimeSpan timeSpan = DateTime.UtcNow - Common.StartTime;

        // 转换为毫秒时间戳（避免浮点精度问题使用整数运算）
        var res = timeSpan.Ticks / TimeSpan.TicksPerMillisecond;

        return res;
    }


}
