// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using FluentValidation;

namespace T2ACore;

/// <summary>
/// file_record验证类
/// cyl 20220826
/// </summary>
public class File_record_Validate : AbstractValidator<File_record_Class>
{
    /// <summary>
    /// 构造函数
    /// </summary>
    public File_record_Validate()
    {
        //设置验证触发级别,遇到第一个失败即停止
        RuleLevelCascadeMode = CascadeMode.Stop;
        ClassLevelCascadeMode = CascadeMode.Stop;
        RuleFor(x => x.File_name)
            .NotNull().NotEmpty()
            .WithName("文件名")
            .WithMessage("不可为空");
        RuleFor(x => x.Bucket_name)
            .NotNull().NotEmpty()
            .WithName("Bucket名称")
            .WithMessage("不可为空");
        RuleFor(x => x.Is_delete)
            .NotNull().NotEmpty()
            .WithName("软删除(10否11是)")
            .WithMessage("不可为空");

    }
}
