// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;

namespace T2ACore;

/// <summary>
/// file_record检索类
/// </summary>
public class File_record_Search
{
    /// <summary>
    /// 父级Id{Search}
    /// </summary>
    public Guid Parent_id { get; set; }

    /// <summary>
    /// 文件名{Search}{Validate:NotEmpty}
    /// </summary>
    public string File_name { get; set; }

    /// <summary>
    /// 文件扩展名{Search}{Distinct}
    /// </summary>
    public string File_ext { get; set; }

    /// <summary>
    /// Bucket名称{Search}{Distinct}{Validate:NotEmpty}
    /// </summary>
    public string Bucket_name { get; set; }

    /// <summary>
    /// 租户{Search}{Distinct}
    /// </summary>
    public string Tenant { get; set; }

    /// <summary>
    /// 创建人账号{Search}
    /// </summary>
    public string Create_account { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }



}

/// <summary>
/// File_record分页检索类
/// </summary>
public class File_record_paged_Search : File_record_Search
{

    /// <summary>
    /// 页码
    /// </summary>
    public int Page { get; set; }

    /// <summary>
    /// 单页数量
    /// </summary>
    public int PageSize { get; set; }
}