// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using Amazon.S3;
using System;
using Newtonsoft.Json;
using SqlSugar;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace T2ACore;

/// <summary>
/// file_record实体
/// </summary> 
[SugarTable("file_record")]
public class File_record_Class
{
    /// <summary>
    /// 主键Id{SortedGUID}
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        ColumnName = "id",
        ColumnDataType = "char",
        ColumnDescription = "主键Id{SortedGUID}",
        Length = 36
    )]
    public Guid Id { get; set; }

    /// <summary>
    /// 父级Id{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "parent_id",
        ColumnDataType = "char",
        ColumnDescription = "父级Id{Search}",
        Length = 36,
        IsNullable = true
    )]
    public Guid Parent_id { get; set; }

    /// <summary>
    /// 排序
    /// </summary>
    [SugarColumn(
        ColumnName = "sort",
        ColumnDataType = "int",
        ColumnDescription = "排序",
        Length = 0,
        IsNullable = true
    )]
    public int Sort { get; set; }

    /// <summary>
    /// 文件名{Search}{Validate:NotEmpty}
    /// </summary>
    [SugarColumn(
        ColumnName = "file_name",
        ColumnDataType = "varchar",
        ColumnDescription = "文件名{Search}{Validate:NotEmpty}",
        Length = 255,
        IsNullable = true
    )]
    public string File_name { get; set; }

    /// <summary>
    /// 文件扩展名{Search}{Distinct}
    /// </summary>
    [SugarColumn(
        ColumnName = "file_ext",
        ColumnDataType = "varchar",
        ColumnDescription = "文件扩展名{Search}{Distinct}",
        Length = 255,
        IsNullable = true
    )]
    public string File_ext { get; set; }

    /// <summary>
    /// 文件完整路径
    /// </summary>
    [SugarColumn(
        ColumnName = "file_path",
        ColumnDataType = "varchar",
        ColumnDescription = "文件完整路径",
        Length = 512,
        IsNullable = true
    )]
    public string File_path { get; set; }

    /// <summary>
    /// Bucket名称{Search}{Distinct}{Validate:NotEmpty}
    /// </summary>
    [SugarColumn(
        ColumnName = "bucket_name",
        ColumnDataType = "varchar",
        ColumnDescription = "Bucket名称{Search}{Distinct}{Validate:NotEmpty}",
        Length = 255,
        IsNullable = true
    )]
    public string Bucket_name { get; set; }

    /// <summary>
    /// MD5编码
    /// </summary>
    [SugarColumn(
        ColumnName = "md5",
        ColumnDataType = "varchar",
        ColumnDescription = "MD5编码",
        Length = 255,
        IsNullable = true
    )]
    public string Md5 { get; set; }

    /// <summary>
    /// 文件长度
    /// </summary>
    [SugarColumn(
        ColumnName = "bytes_length",
        ColumnDataType = "bigint",
        ColumnDescription = "文件长度",
        Length = 0,
        IsNullable = true
    )]
    public long Bytes_length { get; set; }

    /// <summary>
    /// Referer
    /// </summary>
    [SugarColumn(
        ColumnName = "referer",
        ColumnDataType = "varchar",
        ColumnDescription = "Referer",
        Length = 255,
        IsNullable = true
    )]
    public string Referer { get; set; }

    /// <summary>
    /// 上传的Ip地址
    /// </summary>
    [SugarColumn(
        ColumnName = "upload_ip",
        ColumnDataType = "varchar",
        ColumnDescription = "上传的Ip地址",
        Length = 255,
        IsNullable = true
    )]
    public string Upload_ip { get; set; }

    /// <summary>
    /// 软删除(10否11是){Default:10}{Validate:NotEmpty}
    /// </summary>
    [SugarColumn(
        ColumnName = "is_delete",
        ColumnDataType = "int",
        ColumnDescription = "软删除(10否11是){Default:10}{Validate:NotEmpty}",
        Length = 0,
        IsNullable = true
    )]
    public int Is_delete { get; set; } = 10; //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 租户{Search}{Distinct}
    /// </summary>
    [SugarColumn(
        ColumnName = "tenant",
        ColumnDataType = "varchar",
        ColumnDescription = "租户{Search}{Distinct}",
        Length = 255,
        IsNullable = true
    )]
    public string Tenant { get; set; }

    /// <summary>
    /// 创建人账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人账号{Search}",
        Length = 255,
        IsNullable = true
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人姓名",
        Length = 255,
        IsNullable = true
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        Length = 0,
        IsNullable = true
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        Length = 255,
        IsNullable = true
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }


    /// <summary>
    /// 创建台账
    /// </summary>
    /// <param name="bucketName">桶名称</param>
    /// <param name="file">文件</param>
    /// <param name="parentId">父级Id</param>
    /// <param name="account">上传人账号</param>
    /// <param name="userName">上传人姓名</param>
    /// <param name="tenant">上传人租户</param>
    /// <returns></returns>
    public static File_record_Class Create(string bucketName, IFormFile file,
        Guid parentId, string account, string userName, string tenant)
    {
        if (file == null || string.IsNullOrEmpty(bucketName))
        {
            return null;
        }
        if (file.FileName == null)
        {
            return null;
        }

        var id = FunCommon.MakeSortedGuid();

        Stream ms = file.OpenReadStream();

        byte[] bytes = new byte[ms.Length];
        ms.Read(bytes, 0, bytes.Length);
        ms.Seek(0, SeekOrigin.Begin);

        var newModel = new File_record_Class();
        newModel.Id = id;
        newModel.Parent_id = parentId;
        newModel.Sort = 0;
        newModel.File_name = file.FileName;
        newModel.File_ext = file.FileName.Split(".").LastOrDefault();
        newModel.File_path = "/" + id.ToString().ToUpper() + "/" + file.FileName;
        newModel.Bucket_name = bucketName;
        newModel.Md5 = FunOss.GetFileMD5(ms);
        newModel.Bytes_length = file.Length;
        newModel.Referer = ScopeTool.GetReferer();
        newModel.Upload_ip = ScopeTool.GetIPv4();
        newModel.Is_delete = 10;
        newModel.Tenant = tenant;
        newModel.Create_account = account;
        newModel.Create_username = userName;
        newModel.Create_time = FunCommon.GetStandardTimeStamp();
        newModel.Remark = "";
        return newModel;
    }

    /// <summary>
    /// 创建台账
    /// </summary>
    /// <param name="bucketName">桶名称</param>
    /// <param name="fileName">文件名称</param>
    /// <param name="file">文件</param>
    /// <param name="parentId">父级Id</param>
    /// <param name="account">上传人账号</param>
    /// <param name="userName">上传人姓名</param>
    /// <param name="tenant">上传人租户</param>
    /// <returns></returns>
    public static File_record_Class CreateFromBytes(string bucketName, string fileName, byte[] file,
        Guid parentId, string account, string userName, string tenant)
    {
        if (file == null || string.IsNullOrEmpty(bucketName))
        {
            return null;
        }
        if (fileName == null)
        {
            return null;
        }

        var id = FunCommon.MakeSortedGuid();

        Stream ms = new MemoryStream(file);
        byte[] bytes = new byte[ms.Length];
        ms.Read(bytes, 0, bytes.Length);
        ms.Seek(0, SeekOrigin.Begin);

        var newModel = new File_record_Class();
        newModel.Id = id;
        newModel.Parent_id = parentId;
        newModel.Sort = 0;
        newModel.File_name = fileName;
        newModel.File_ext = fileName.Split(".").LastOrDefault();
        newModel.File_path = "/" + id.ToString().ToUpper() + "/" + fileName;
        newModel.Bucket_name = bucketName;
        newModel.Md5 = FunOss.GetFileMD5(ms);
        newModel.Bytes_length = file.Length;
        newModel.Referer = ScopeTool.GetReferer();
        newModel.Upload_ip = ScopeTool.GetIPv4();
        newModel.Is_delete = 10;
        newModel.Tenant = tenant;
        newModel.Create_account = account;
        newModel.Create_username = userName;
        newModel.Create_time = FunCommon.GetStandardTimeStamp();
        newModel.Remark = "";
        return newModel;
    }


    /// <summary>
    /// 创建台账
    /// </summary>
    /// <param name="client">S3客户端，本方法仅支持S3协议</param>
    /// <param name="bucketName">桶名称</param>
    /// <param name="objectName">文件地址</param>
    /// <param name="parentId">父级Id</param>
    /// <param name="account">上传人账号</param>
    /// <param name="userName">上传人姓名</param>
    /// <param name="tenant">上传人租户</param>
    /// <returns></returns>
    public static async Task<File_record_Class> CreateFromS3ObjectName(AmazonS3Client client,
        string bucketName, string objectName, Guid parentId,
        string account, string userName, string tenant)
    {
        if (string.IsNullOrEmpty(bucketName) ||
            string.IsNullOrEmpty(objectName))
        {
            return null;
        }

        var id = FunCommon.MakeSortedGuid();

        var fileName = Path.GetFileName(objectName);

        var newModel = new File_record_Class();
        newModel.Id = id;
        newModel.Parent_id = parentId;
        newModel.Sort = 0;
        newModel.File_name = fileName;
        newModel.File_ext = fileName.Split(".").LastOrDefault();
        newModel.File_path = objectName;
        newModel.Bucket_name = bucketName;

        var response = await client.GetObjectMetadataAsync(bucketName, objectName);

        newModel.Md5 = FunOss.GetETagMD5(response.ETag);
        newModel.Bytes_length = response.ContentLength;
        newModel.Referer = ScopeTool.GetReferer();
        newModel.Upload_ip = ScopeTool.GetIPv4();
        newModel.Is_delete = 10;
        newModel.Tenant = tenant;
        newModel.Create_account = account;
        newModel.Create_username = userName;
        newModel.Create_time = FunCommon.GetStandardTimeStamp();
        newModel.Remark = "";
        return newModel;
    }
}
