// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using SqlSugar;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// file_record树形类
/// </summary>
[SugarTable("file_record")]
public class File_record_InTree : File_record_Class
{
    /// <summary>
    /// 子集合
    /// </summary>
    [SugarColumn(IsIgnore = true)]
    public List<File_record_InTree> Children { get; set; }
    /// <summary>
    /// 由Class转为Tree型
    /// </summary>
    /// <param name="inClass"></param>
    /// <returns></returns>
    public static File_record_InTree Cast(File_record_Class inClass)
    {
        var inTree = new File_record_InTree();
        inTree.Id = inClass.Id;
        inTree.Parent_id = inClass.Parent_id;
        inTree.Sort = inClass.Sort;
        inTree.File_name = inClass.File_name;
        inTree.File_ext = inClass.File_ext;
        inTree.File_path = inClass.File_path;
        inTree.Bucket_name = inClass.Bucket_name;
        inTree.Md5 = inClass.Md5;
        inTree.Bytes_length = inClass.Bytes_length;
        inTree.Referer = inClass.Referer;
        inTree.Upload_ip = inClass.Upload_ip;
        inTree.Is_delete = inClass.Is_delete;
        inTree.Tenant = inClass.Tenant;
        inTree.Create_account = inClass.Create_account;
        inTree.Create_username = inClass.Create_username;
        inTree.Create_time = inClass.Create_time;
        inTree.Remark = inClass.Remark;
        inTree.Children = new List<File_record_InTree>();
        return inTree;
    }

}
