// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126
using CSRedis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace T2ACore;

/// <summary>
/// Redis缓存
/// </summary>
public class CacheRedis : ICache
{
    private readonly CSRedisClient csredis;

    /// <summary>
    /// 构造函数
    /// </summary>
    public CacheRedis()
    {
        csredis = new CSRedisClient(Config.RedisConfig.RedisLink);
    }

    /// <summary>
    /// 获取缓存实例
    /// </summary>
    /// <returns></returns>
    public object GetCache()
    {
        return csredis;
    }

    /// <summary>
    /// 插入缓存
    /// </summary>
    /// <param name="key">缓存key</param>
    /// <param name="obj">缓存对象</param>
    /// <returns></returns>
    public object Insert(string key, object obj)
    {
        return csredis.Set(key, obj);
    }

    /// <summary>
    /// 插入缓存
    /// </summary>
    /// <param name="key">缓存key</param>
    /// <param name="obj">缓存对象</param>
    /// <param name="expiry">过期时间(绝对时间)</param>
    /// <returns></returns>
    public object Insert(string key, object obj, DateTime expiry)
    {
        TimeSpan ts = expiry - DateTime.Now;
        return csredis.Set(key, obj, ts);
    }

    /// <summary>
    /// 获取缓存对象
    /// </summary>
    /// <param name="key">缓存key</param>
    /// <returns></returns>
    public object Get(string key)
    {
        return csredis.Get(key);
    }

    /// <summary>
    /// 模糊获取缓存对象
    /// </summary>
    /// <param name="keyPattern">缓存key，带通配符</param>
    /// <returns></returns>
    public List<object> BlurGet(string keyPattern)
    {
        var list = new List<object>();
        var keyList = GetAllKeys(keyPattern);
        foreach (var key in keyList)
        {
            list.Add(csredis.Get(key));
        }
        return list;
    }

    /// <summary>
    /// 移出缓存对象
    /// </summary>
    /// <param name="key">缓存key</param>
    public void Remove(params string[] key)
    {
        csredis.Del(key);
    }

    /// <summary>
    /// 模糊删除缓存对象
    /// </summary>
    /// <param name="keyPattern">缓存key，带通配符</param>
    /// <returns></returns>
    public void BlurRemove(string keyPattern)
    {
        try
        {
            var keyList = GetAllKeys(keyPattern).ToArray();
            Remove(keyList);
        }
        catch (Exception)
        {

            throw;
        }

    }

    /// <summary>
    /// 返回所有Keys
    /// </summary>
    /// <returns></returns>
    public List<string> GetAllKeys(string pattern)
    {
        try
        {
            return csredis.Keys(pattern).ToList();
        }
        catch (Exception)
        {

            throw;
        }

    }

    /// <summary>
    /// 从缓存获取实体
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="key"></param> 
    /// <returns></returns>
    public T GetFromCache<T>(string key)
    {
        return csredis.Get<T>(key);
    }

    /// <summary>
    /// 将键值增加 value 
    /// 20210317 LJY添加
    /// </summary>
    /// <param name="key"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    public long IncrBy(string key, long value = 1)
    {
        return csredis.IncrBy(key, value);
    }


}

