namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230418

using System;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using T2ACore;

/// <summary>
/// About控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
//[TPOKAdmin]
public class AboutController : ControllerBase
{
    /// <summary>
    /// 获取当前版本
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<string> GetSystemVersion()
    {
        Assembly assembly = Assembly.GetExecutingAssembly();
        var res = assembly.GetName().Version.ToString();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取部署时间
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<DateTime> GetDeployTime()
    {
        return TPResponse.New(Common.ServerStartTime);
    }

}

