namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230418

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using T2ACore;

/// <summary>
/// Auth_assets控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOKAdmin]
public class AuthController : ControllerBase
{
    private readonly IAuthBusiness AuthBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public AuthController(IAuthBusiness auth)
    {
        AuthBusiness = auth;
    }

#if DEBUG

    /// <summary>
    /// 初始化测试数据
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<bool> InitTestData()
    {
        var res = AuthBusiness.InitTestData();
        return TPResponse.New(res);
    }
#endif

    /// <summary>
    /// 添加系统角色
    /// </summary>
    /// <param name="regionType">配置中的维度编号</param>
    /// <param name="roles"></param>
    /// <returns></returns>
    [HttpPost("{regionType}")]
    public TPResponse<int> AddSysRole([FromRoute] int regionType, [FromBody] List<Req_NewRole> roles)
    {
        var (account, username) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var (region, regionTitle) = AuthCommon.GetRegion(regionType);

        if (string.IsNullOrEmpty(region))
        {
            return TPResponse.Bad<int>("错误的角色维度");
        }

        var roleToAdd = new List<Auth_role_Class>();

        foreach (var role in roles)
        {
            if (role.Id == Guid.Empty)
            {
                role.Id = Guid.NewGuid();
                role.Parent_id = Guid.Empty;
            }
            var tableRow = role.Cast(tenant, account, username, region, regionTitle);
            roleToAdd.Add(tableRow);
        }
        var res = AuthBusiness.Add(roleToAdd);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 修改角色编码或角色名，同时更新资源表
    /// </summary>
    /// <param name="roles"></param>
    /// <returns></returns>
    [HttpPut]
    public TPResponse<bool> UpdateSysRole([FromBody] List<Auth_role_Class> roles)
    {
        var (account, username) = ScopeUser.GetUserAccountName();
        var res = AuthBusiness.UpdateSysRole(roles, account, username);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 删除角色
    /// </summary>
    /// <param name="roleIds"></param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<int> DelSysRole([FromBody] Guid[] roleIds)
    {
        return TPResponse.New(AuthBusiness.DeleteSysRole(roleIds));
    }

    ////////////////////////////////////////////////////////////////
    // 处理鉴权资源
    ////////////////////////////////////////////////////////////////

    /// <summary>
    /// 获取所有的Controller方法
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<ControllerFunction>> GetAllControllerFunctions()
    {
        var res = AuthCommon.GetControllerFunctions();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 给一群人添加一个角色
    /// </summary>
    /// <param name="userAccounts"></param>
    /// <param name="roleType"></param>
    /// <param name="roleCode"></param>
    /// <param name="UserBusiness"></param>
    /// <returns></returns>
    [HttpPost("{roleType}/{roleCode}")]
    public TPResponse<int> AddRoleForUsers([FromRoute] int roleType,
        [FromRoute] string roleCode, [FromBody] List<string> userAccounts,
        [FromServices] IUser_Business UserBusiness)
    {
        var (optAccount, optUserName) = ScopeUser.GetUserAccountName();
        var optTenant = ScopeUser.GetUserTenant();
        var (region, regionTitle) = AuthCommon.GetRegion(roleType);

        //这里保证userAccounts只能是账号信息
        var users = UserBusiness.SearchBy_Accounts(userAccounts);

        var assets = new List<Auth_assets_Class>();
        foreach (var user in users)
        {
            if (user.Tenant != optTenant)
            {
                continue;
            }

            var asset = Auth_assets_Class.CastForUser(
                optAccount, optUserName, optTenant,
                region, user.Tenant, roleCode);

            assets.Add(asset);
        }
        return TPResponse.New(AuthBusiness.Add(assets));
    }

    /// <summary>
    /// 添加角色继承关系的一组角色资源
    /// TODO 避免直接给人员添加
    /// </summary>
    /// <param name="roleType">角色维度</param>
    /// <param name="roleGroup">继承关系的角色组</param>
    /// <param name="UserBusiness"></param>
    /// <returns></returns>
    [HttpPost("{roleType}")]
    public TPResponse<int> AddRoles([FromRoute] int roleType,
        [FromBody] List<Req_RoleHaving> roleGroup,
        [FromServices] IUser_Business UserBusiness)
    {
        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();
        var (region, regionTitle) = AuthCommon.GetRegion(roleType);

        var userAccounts = UserBusiness
            .SearchBy_Tenant(tenant)
            .Select(x => x.Account)
            .ToList();

        var assetsToAdd = new List<Auth_assets_Class>();
        foreach (var group in roleGroup)
        {
            if (userAccounts.Contains(group.RoleCode))
            {
                return TPResponse.Bad<int>("不允许为个人" + group.RoleCode + "添加角色组");
            }

            if (userAccounts.Contains(group.HavingRole))
            {
                return TPResponse.Bad<int>("不允许个人账号" + group.HavingRole + "成为角色");
            }

            var asset = group.Cast(account, userName, tenant, region);
            if (asset != null)
            {
                assetsToAdd.Add(asset);
            }
        }
        return TPResponse.New(AuthBusiness.Add(assetsToAdd));

    }

    /// <summary>
    /// 删除一组用户角色
    /// </summary>
    /// <param name="userAccounts">账号集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<int> DelRolesForUsers([FromBody] List<string> userAccounts)
    {
        var tenant = ScopeUser.GetUserTenant();
        var res = AuthBusiness.DeleteRolesForUsers(userAccounts, tenant); //此方法有Value4=="Person"的限制
        return TPResponse.New(res);
    }

    /// <summary>
    /// 删除某个角色拥有的角色
    /// </summary>
    /// <param name="roleType"></param>
    /// <param name="roleCode"></param>
    /// <returns></returns>
    [HttpDelete("{roleType}/{roleCode}")]
    public TPResponse<int> DelRolesForRole(
        [FromRoute] int roleType, [FromRoute] string roleCode)
    {
        var tenant = ScopeUser.GetUserTenant();
        var (region, regionTitle) = AuthCommon.GetRegion(roleType);
        var res = AuthBusiness.DeleteRolesForRole(region, roleCode, tenant);//此方法有Value4==null的限制
        return TPResponse.New(res);
    }

    /// <summary>
    /// 重建缓存
    /// TODO 同时清理全部缓存
    /// </summary>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<int> RestartAssets()
    {
        return TPResponse.New(0);
    }


    /// <summary>
    /// 处理资源
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assetType">资源类型，与appsettings匹配</param>
    /// <param name="patternList">资源特征码</param>
    /// <returns></returns>
    private (bool Status, string Msg, int Result) ExecuteAssets(
        string roleCode, int assetType, List<List<string>> patternList)
    {
        var (optAccount, optUserName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var role = AuthBusiness.SearchBy_RoleCode_Tenant(roleCode, tenant);

        if (role.Count < 1)
        {
            return (false, "该角色编码不存在", -1);
        }

        var (type, asset) = AuthCommon.GetAssetsType(assetType); //此处需要跟appsettings中的资源数组匹配

        var assetsToAdd = new List<Auth_assets_Class>();

        foreach (var patterns in patternList)
        {
            var newAsset = Auth_assets_Class.CastFromAsset(
                optAccount, optUserName, tenant, type,
                roleCode, asset, patterns);
            assetsToAdd.Add(newAsset);
        }

        var res = AuthBusiness.Add(assetsToAdd);
        return (true, "OK", res);

    }

    /// <summary>
    /// 示例，为某个角色添加菜单资源
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="menuCodes">实际的资源</param>
    /// <returns></returns>
    [HttpPost("{roleCode}")]
    public TPResponse<int> AddAssetsForRole_Menu([FromRoute] string roleCode,
        [FromBody] List<string> menuCodes)
    {
        var patternList = new List<List<string>>();
        foreach (var menuCode in menuCodes)
        {
            patternList.Add(new List<string> { menuCode });
        }

        var (status, msg, res) = ExecuteAssets(roleCode, 0, patternList);

        return status
            ? TPResponse.New(res)
            : TPResponse.Bad<int>(msg);
    }

    /// <summary>
    /// 示例，为某个角色添加接口资源
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assets">实际的资源</param>
    /// <returns></returns>
    [HttpPost("{roleCode}")]
    public TPResponse<int> AddAssetsForRole_Controller([FromRoute] string roleCode,
        [FromBody] List<ControllerFunction> assets)
    {
        var patternList = new List<List<string>>();
        foreach (var func in assets)
        {
            patternList.Add(new List<string> { func.Method, func.Route });
        }

        var (status, msg, res) = ExecuteAssets(roleCode, 1, patternList);

        return status
            ? TPResponse.New(res)
            : TPResponse.Bad<int>(msg);
    }

    /// <summary>
    /// 示例，为某个角色添加资源
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assets">实际的资源</param>
    /// <returns></returns>
    [HttpPost("{roleCode}")]
    public TPResponse<int> AddAssetsForRole_XXX([FromRoute] string roleCode, [FromBody] List<object> assets)
    {
        var patternList = new List<List<string>>();
        //TODO 此处需要处理assets

        //参数"2",此处需要跟appsettings中的资源数组匹配
        var (status, msg, res) = ExecuteAssets(roleCode, 2, patternList);

        return status
            ? TPResponse.New(res)
            : TPResponse.Bad<int>(msg);
    }


    /// <summary>
    /// 处理删除资源操作
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assetType">资源类型</param>
    /// <returns></returns>
    private (bool Status, string Msg, string AType, string Tenant, string Asset) ExecuteDelAssets(
        string roleCode, int assetType)
    {
        var tenant = ScopeUser.GetUserTenant();
        var role = AuthBusiness.SearchBy_RoleCode_Tenant(roleCode, tenant);

        if (role.Count < 1)
        {
            return (false, "角色编码不存在", "", "", "");
        }

        var (type, asset) = AuthCommon.GetAssetsType(assetType);

        return (true, "OK", type, tenant, asset);
    }


    /// <summary>
    /// 为角色删除权限资源
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assetType">资源类型</param>
    /// <returns></returns>
    [HttpDelete("{roleCode}/{assetType}")]
    public TPResponse<int> DelAssetsForRole([FromRoute] string roleCode, [FromRoute] int assetType)
    {
        var (status, msg, type, tenant, asset) = ExecuteDelAssets(roleCode, assetType);
        if (!status)
        {
            return TPResponse.Bad<int>(msg);
        }

        var res = AuthBusiness.DeleteAssetsForRole(type, roleCode, tenant, asset);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 为角色删除权限资源，指定资源特征值
    /// </summary>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assetType">资源类型</param>
    /// <param name="patterns">特征值</param>
    /// <returns></returns>
    [HttpDelete("{roleCode}/{assetType}")]
    public TPResponse<int> DelAssetsForRoleWithPatterns([FromRoute] string roleCode,
        [FromRoute] int assetType, [FromBody] List<List<string>> patterns)
    {
        var (status, msg, type, tenant, asset) = ExecuteDelAssets(roleCode, assetType);
        if (!status)
        {
            return TPResponse.Bad<int>(msg);
        }

        var res = AuthBusiness.DeleteAssetsForRole(type, roleCode, tenant, asset, patterns);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据账号获取全部角色，拍平数据
    /// </summary>
    /// <param name="account"></param>
    /// <returns></returns>
    [HttpGet("{account}")]
    public TPResponse<List<RoleList>> GetAllRolesListForUser([FromRoute] string account)
    {
        var res = AuthBusiness.GetRolesListForUser(account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据账号获取全部角色，树形数据
    /// </summary>
    /// <param name="account"></param>
    /// <returns></returns>
    [HttpGet("{account}")]
    public TPResponse<List<RoleTree>> GetAllRolesTreeForUser([FromRoute] string account)
    {
        var res = AuthBusiness.GetRolesTreeForUser(account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据账号获取按不同角色维度有权限的资源
    /// </summary>
    /// <param name="account"></param>
    /// <returns></returns>
    [HttpGet("{account}")]
    public TPResponse<List<Res_AssetGroup>> GetAssetsGroupsForUser([FromRoute] string account)
    {
        var res = AuthBusiness.GetAssetsForUser(account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据账号获取按不同角色维度，组合之后，有权限的资源
    /// </summary>
    /// <param name="account"></param>
    /// <param name="assetExecuter"></param>
    /// <returns></returns>
    [HttpGet("{account}")]
    public TPResponse<List<Res_Asset>> GetAllAssetsForUser(
        [FromRoute] string account, [FromServices] IAssetExecuter assetExecuter)
    {
        var groups = AuthBusiness.GetAssetsForUser(account);
        var res = assetExecuter.GetAssetsResult(groups);
        return TPResponse.New(res);
    }

    //public TPResponse<int> EnforceTest() { }

}
