namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20231209

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using T2ACore;
using TPFun_Excel; 

/// <summary>
/// 外部接口控制器例子
/// 这里接口紧为示意，具体项目应该在具体接口处调用业务方法
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOKAdmin]
public class Demo_ExcelController : ControllerBase
{
#if DEBUG

    /// <summary>
    /// 通过文件生成表格
    /// 用于跨服务之间发送
    /// </summary>
    /// <param name="importFile"></param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Cell>> ExcelCallerGetAll(IFormCollection importFile)
    {
        var fileExt = importFile.Files[0].FileName.EndsWith(".xlsx");
        if (!fileExt)
        {
            return TPResponse.Bad<List<Cell>>("only xlsx allowed");
        }

        var (status, msg, cells, fileName) = XlsxReader.GetAll(importFile);

        if (status)
        {
            return TPResponse.New(cells);
        }
        else
        {
            return TPResponse.Bad<List<Cell>>(msg, null);
        }
    }

    /// <summary>
    /// 将cells写入xlsx文件
    /// 用于跨服务之间发送
    /// </summary>
    /// <param name="cells"></param>
    /// <returns></returns>
    /// <exception cref="Exception"></exception>
    [HttpPost]
    public IActionResult ExcelWriteToFile([FromBody] List<Cell> cells)
    {
        if (cells == null)
        {
            throw new Exception("List is null!");
        }

        var (status, msg, ms) = XlsxWriter.WriteToFile(cells);

        if (status)
        {
            var dt = DateTime.Now.ToString("yyyy-MM-dd_HH:mm:ss.fff");
            return File(ms, "application/octet-stream", "export" + dt + ".xlsx");
        }
        else
        {
            return new JsonResult(new { status, msg });
        }

    }

    /// <summary>
    /// 将cells写入xlsx文件,带样式
    /// 用于跨服务之间发送
    /// </summary>
    /// <param name="cells">带样式的单元格</param>
    /// <returns></returns>
    /// <exception cref="Exception"></exception>
    [HttpPost]
    public IActionResult ExcelWriteToFileWithSytle([FromBody] List<CellsWithStyle> cells)
    {
        if (cells == null)
        {
            throw new Exception("List is null!");
        }

        var (status, msg, ms) = XlsxWriter.WriteToFileWithSytle(cells);

        if (status)
        {
            var dt = DateTime.Now.ToString("yyyy-MM-dd_HH:mm:ss.fff");
            return File(ms, "application/octet-stream", "export" + dt + ".xlsx");
        }
        else
        {
            return new JsonResult(new { status, msg });
        }

    }
#endif
}

