namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20231209

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TPFun_Cad;
using T2ACore;

/// <summary>
/// 外部接口控制器例子
/// 这里接口紧为示意，具体项目应该在具体接口处调用业务方法
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOKAdmin]
public class Demo_CadController : ControllerBase
{
#if DEBUG

    /// <summary>
    /// 获取图纸信息,转为JSON
    /// 用于跨服务之间发送
    /// </summary>
    /// <param name="importFile">文件</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<DxfLayout> CadDxfGetJSON(
        IFormCollection importFile)
    {
        if (importFile.Files[0] == null)
        {
            return TPResponse.Bad<DxfLayout>("no file");
        }

        var fileStream = importFile.Files[0].OpenReadStream();
        var LayoutData = DxfReader.AnalysisDxfDocument(fileStream);
        return TPResponse.New(LayoutData);
    }

#endif
}

