namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using T2ACore;

/// <summary>
/// Language控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
public class LanguageController : ControllerBase
{
    private readonly ILanguage_Business LanguageBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public LanguageController(ILanguage_Business inDI)
    {
        LanguageBusiness = inDI;
    }


    /// <summary>
    /// 获取字典全部数据,按照ZH,EN,RU,DE 格式返回
    /// </summary>
    /// <returns></returns>
    /// <exception cref="Exception"></exception>
    [HttpGet]
    public TPResponse<LanDict> GetAllLanguage()
    {
        if (LanCache.Dictionary == null)
        {
            LanCache.Dictionary = ReloadLanguages();
        }
        return TPResponse.New("ok", LanCache.Dictionary);
    }

    /// <summary>
    /// 重新获取字典全部数据,按照ZH,EN,RU,DE 格式返回
    /// </summary>
    /// <returns></returns>
    /// <exception cref="Exception"></exception>
    [HttpGet]
    public TPResponse<LanDict> ReloadAllLanguage()
    {
        LanCache.Dictionary = ReloadLanguages();
        return TPResponse.New("ok", LanCache.Dictionary);
    }

    private LanDict ReloadLanguages()
    {
        var res = LanguageBusiness.GetAllWithoutCache();
        var dict = new LanDict();
        dict.ZH = new Dictionary<string, string>();
        dict.DE = new Dictionary<string, string>();
        dict.EN = new Dictionary<string, string>();
        dict.RU = new Dictionary<string, string>();
        dict.ES = new Dictionary<string, string>();
        dict.PT = new Dictionary<string, string>();

        foreach (Language_Class item in res)
        {
            dict.ZH.Add(item.Zh, item.Zh);
            dict.DE.Add(item.Zh, item.De);
            dict.EN.Add(item.Zh, item.En);
            dict.RU.Add(item.Zh, item.Ru);
            dict.ES.Add(item.Zh, item.Es);
            dict.PT.Add(item.Zh, item.Pt);
        }
        return dict;
    }

    /// <summary>
    /// 获取所有实体
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    [TPOKAdmin]
    public TPResponse<List<Language_Class>> GetAllLanguages([FromQuery] string zh)
    {
        var res = LanguageBusiness.GetAll();

        if (!string.IsNullOrEmpty(zh))
        {
            res = res.FindAll(x => x.Key.Contains(zh));
        }

        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<Language_Class> Get([FromRoute] string inId)
    {
        var res = LanguageBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取所有实体
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<Language_Class>> GetAll()
    {
        var res = LanguageBusiness.GetAll();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取所有实体分页数据
    /// </summary>
    /// <param name="pageNum">第几页</param>
    /// <param name="pageSize">单页数量</param>
    /// <returns></returns>
    [HttpGet("{pageNum}/{pageSize}")]
    public TPResponse<PagedResponse<Language_Class>> GetAllPaged(
        [FromRoute] int pageNum, [FromRoute] int pageSize)
    {
        var (totalCount, datas) = LanguageBusiness.GetAllPaged(pageNum, pageSize);
        var res = PagedResponse.New(totalCount, datas);
        return TPResponse.New(res);
    }
    /// <summary>
    /// 根据Key查询
    /// </summary>
    /// <param name="inSearch_Key">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Key}")]
    public TPResponse<List<Language_Class>> Search_Key([FromRoute] string inSearch_Key)
    {
        var res = LanguageBusiness.SearchBy_Key(inSearch_Key);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    [TPOKAdmin]
    public TPResponse<Res_2Para> Add([FromBody] Language_Class inEntity)
    {
        if (string.IsNullOrEmpty(inEntity.Key))
        {
            return TPResponse.New(Res_2Para.New(false, "未输入主键中文"));
        }

        var find = LanguageBusiness.GetOne(inEntity.Key);
        if (find == null)
        {
            inEntity.Zh = inEntity.Key;
            var res = LanguageBusiness.Add(inEntity);
            return TPResponse.New(Res_2Para.New(res, "操作完成"));
        }
        else
        {
            return TPResponse.New(Res_2Para.New(false, "【" + inEntity.Key + "】已存在"));
        }


    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    public TPResponse<Res_2Para> Update([FromBody] Language_Class inEntity)
    {
        if (string.IsNullOrEmpty(inEntity.Key))
        {
            return TPResponse.New(Res_2Para.New(false, "未输入主键中文"));
        }

        var find = LanguageBusiness.GetOne(inEntity.Key);
        if (find == null)
        {
            return TPResponse.New(Res_2Para.New(false, "【" + inEntity.Key + "】未找到"));
        }
        else
        {
            inEntity.Zh = inEntity.Key;
            var res = LanguageBusiness.Update(inEntity);
            return TPResponse.New(Res_2Para.New(res, "操作完成"));
        }
         
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<Res_2Para> Delete([FromBody] string[] arr)
    {
        var res = LanguageBusiness.DeleteByIds(arr);
        return TPResponse.New(Res_2Para.New(true, res + "条已删除"));
    }
}
