namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230418

using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using T2ACore; 

/// <summary>
/// 日志控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOKAdmin]
public class LogController : ControllerBase
{
    /// <summary>
    /// 获取昨日日志原文
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public IActionResult DownloadLastDayLog()
    {
        var (logPath, fileName) = GetLastDayLogPath();
        if (System.IO.File.Exists(logPath))
        {
            var fileBytes = System.IO.File.ReadAllBytes(logPath);
            return File(new MemoryStream(fileBytes), "application/octet-stream", fileName);
        }
        else
        {
            return new JsonResult(TPResponse.New("未找到日志文件"));
        }
    }

    /// <summary>
    /// 获取昨日日志人员访问情况
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<UserRequestInfo>> GetLastDayUserRequest()
    {
        var (logPath, fileName) = GetLastDayLogPath();
        if (System.IO.File.Exists(logPath))
        {
            var fileContent = System.IO.File.ReadAllText(logPath);
            var pieces = fileContent.Split("[INFO]").ToList().FindAll(x => x.Contains("操作人账号")); 

            var logres = new List<HttpLogMsg>();
            foreach (var piece in pieces)
            {
                var lines = piece.Split("\r\n");
                var logMsg = new HttpLogMsg(); 
                logMsg.StartTime = GetInfo(lines, "开始时间:");
                logMsg.OperationTime = GetInfo(lines, "操作时间:");
                logMsg.OperationAccount = GetInfo(lines, "操作人账号:");
                logMsg.OperationName = GetInfo(lines, "操作人:");
                logMsg.IpAddress = GetInfo(lines, "用户Ip:");
                logMsg.AccessApiUrl = GetInfo(lines, "请求接口:");
                logMsg.Method = GetInfo(lines, "请求方法:");
                logMsg.Params = GetInfo(lines, "请求参数:");
                logMsg.ReqResultCode = GetInfo(lines, "请求结果代码:");

                logres.Add(logMsg);
            }

            var userReqs = logres.GroupBy(x => x.OperationAccount);

            var res = new List<UserRequestInfo>();
            foreach (var userReq in userReqs)
            {
                var uReqInfo = new UserRequestInfo();
                uReqInfo.Account = userReq.Key;
                uReqInfo.UserName = userReq.ToList()[0].OperationName;
                uReqInfo.RequestTimeAmount = userReq.ToList().Count;
                res.Add(uReqInfo);
            }

            return TPResponse.New(res.OrderBy(x => x.RequestTimeAmount).ToList());
        }
        else
        {
            return TPResponse.Bad<List<UserRequestInfo>>("未找到日志文件", null);
        }
    }

    private static (string, string) GetLastDayLogPath()
    {
        var dateStr = DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd");

#if DEBUG
        string fileName = "DDPPro-business-" + dateStr + ".log";
        string logPath = Path.Combine(Common.CurrentDllPath, "ProjectLogs", dateStr, fileName);
#else
        string fileName = "dotnet-business-" + dateStr + ".log";
        string logPath = Path.Combine(Common.CurrentDllPath, "ProjectLogs", "0Archive", dateStr, fileName);
#endif

        return (logPath, fileName);
    }

    private static string GetInfo(string[] lines, string pattern)
    {
        return lines.ToList().Find(x => x.StartsWith(pattern))?.Replace(pattern, "");
    }

}

/// <summary>
/// 用户登录情况
/// </summary>
public class UserRequestInfo
{
    /// <summary>
    /// 账号
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 请求次数
    /// </summary>
    public int RequestTimeAmount { get; set; }
}


