namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20240724 补充单独登录

using System;
using T2ACore;
using Microsoft.AspNetCore.Mvc;

/// <summary>
/// 登录控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]")]
[ApiExplorerSettings(GroupName = "Sys")]
public class LoginController : ControllerBase
{
    /// <summary> 
    /// 登录
    /// </summary> 
    /// <param name="info"></param>
    /// <param name="AuthBusiness"></param>
    /// <param name="userBusiness"></param>
    /// <returns></returns> 
    [HttpPost("")]
    public TPResponse<LoginResponse> Login([FromBody] LoginInfo info,
        [FromServices] IAuthBusiness AuthBusiness,
        [FromServices] IUser_Business userBusiness)
    {
        bool status = false;
        string msg = "";
        string token = "";

        if (Config.BaseConfig.UseLoginLoginAuth)
        {
            (status, msg, token, _) = userBusiness
                .Login(info.Account, info.Password);
        }
        else
        {
            (status, msg, token) = FunHttp_TotalLogin.Login(info);
        }

        if (status)
        {
            var user = UserInfo.GetFromToken(token);
            var login = LoginResponse.OK(msg, token, user.Account, user.UserName,
                Config.BaseConfig.AdminList.Contains(user.Account));
            return TPResponse.New(login);
        }
        else
        {
            var bad = LoginResponse.Fail(msg);
            return TPResponse.New(bad);
        }
    }

    /// <summary> 
    /// 获取用户信息
    /// </summary>  
    /// <param name="AuthBusiness"></param>
    /// <returns></returns> 
    [HttpPost("GetUserInfo")]
    [TPOK]
    public TPResponse<LoginResponse> GetUserInfo([FromServices] IAuthBusiness AuthBusiness)
    {
        var (account, username) = ScopeUser.GetUserAccountName();
        var info = LoginResponse.OK("OK", "", account, username,
            Config.BaseConfig.AdminList.Contains(account));
        return TPResponse.New(info);
    }

    /// <summary>
    /// 修改人员状态 
    /// </summary>
    /// <param name="userBusiness"></param>
    /// <param name="account"></param>
    /// <param name="status"></param>
    /// <returns></returns>
    [HttpPost("ChangeStatus")]
    [TPOKAdmin]
    public TPResponse<bool> ChangeStatus([FromServices] IUser_Business userBusiness,
        [FromQuery] string account, [FromQuery] int status)
    {
        var users = userBusiness.SearchBy_Account(account);
        if (users == null)
        {
            return TPResponse.Bad("NoUsers", false);
        }

        var user = users[0];

        if (user == null)
        {
            return TPResponse.Bad("NoUser", false);
        }

        user.Status = status;
        user.Update_time = FunCommon.GetStandardTimeStamp();
        user.Apply_time = FunCommon.GetStandardTimeStamp();
        user.Handle_account = account;

        var res = userBusiness.Update(user);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 修改密码
    /// </summary>
    /// <param name="userBusiness"></param>
    /// <param name="pass"></param>
    /// <returns></returns>
    [HttpPut("ModifyPassword")]
    [TPOK]
    public TPResponse<bool> ModifyPassword(
        [FromServices] IUser_Business userBusiness,
        [FromBody] ModifyPassData pass)
    {
        string tp_token = HttpContext.Request.Cookies[Config.BaseConfig.TokenString];
        UserInfo userinfo = UserInfo.GetFromToken(tp_token);

        var (status, msg) = userBusiness.ModifyPassword(userinfo.Account,
            pass.Password, pass.NewPassword1, pass.NewPassword2);

        if (status) //成功修改
        {
            HttpContext.Response.Cookies.Delete(Config.BaseConfig.TokenString);
        }

        return TPResponse.New(status);
    }


    /// <summary>
    /// 添加用户 
    /// </summary>
    /// <param name="userBusiness"></param>
    /// <param name="rtUser"></param>
    /// <returns></returns>
    [HttpPost("AddNewUser")]
#if DEBUG

#else
    [TPOKAdmin]
#endif
    public TPResponse<AddUserData> AddNewUser(
        [FromServices] IUser_Business userBusiness,
        [FromBody] User_Class rtUser)
    {
        var res = new AddUserData();
        if (string.IsNullOrWhiteSpace(rtUser.Account))
        {
            res.Account = rtUser.Account;
            res.Status = false;
            res.UserId = rtUser.UserId;
            res.Msg = "账号必填";
            return TPResponse.New(res);
        }

        var finds = userBusiness.SearchBy_Account(rtUser.Account);
        if (finds.Count > 0)
        {
            res.Account = rtUser.Account;
            res.Status = false;
            res.UserId = rtUser.UserId;
            res.Msg = "账号被占用";
            return TPResponse.New(res);
        }

        var (account, username) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        //var newUser = new User_Class();
        //newUser.Id
        rtUser.UserId = FunCommon.MakeSortedGuid();
        rtUser.Create_account = account;
        rtUser.Create_username = username;
        rtUser.Create_time = FunCommon.GetStandardTimeStamp();
        rtUser.Update_account = account;
        rtUser.Update_username = username;
        rtUser.Update_time = FunCommon.GetStandardTimeStamp();
        rtUser.Tenant = tenant;
        rtUser.Apply_time = FunCommon.GetStandardTimeStamp();

        var (status, msg) = userBusiness.AddNewUser(rtUser);

        userBusiness.RestorePassword(account, Config.BaseConfig.InitPassword);

        res.Account = rtUser.Account;
        res.Status = status;
        res.UserId = rtUser.UserId;
        res.Msg = msg;
        return TPResponse.New(res);
    }


    /// <summary>
    /// 修改用户 
    /// </summary>
    /// <param name="userBusiness"></param>
    /// <param name="rtUser"></param>
    /// <returns></returns>
    [HttpPut("UpdateUser")]
#if DEBUG

#else
    [TPOKAdmin]
#endif
    public TPResponse<Res_2Para> UpdateUser(
        [FromServices] IUser_Business userBusiness,
        [FromBody] User_Class rtUser)
    {
        if (string.IsNullOrWhiteSpace(rtUser.Account))
        {
            return TPResponse.Bad("账号是必须的",
                Res_2Para.New(false, "账号是必须的"));
        }

        var (account, username) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        rtUser.Update_account = account;
        rtUser.Update_username = username;
        rtUser.Update_time = FunCommon.GetStandardTimeStamp();
        rtUser.Tenant = tenant;
        rtUser.Apply_time = FunCommon.GetStandardTimeStamp();

        var (status, msg) = userBusiness.UpdateUser(rtUser);

        return TPResponse.New(Res_2Para.New(status, msg));
    }


    /// <summary>
    /// 验证token
    /// </summary>
    /// <returns></returns>
    [TPOK]
    [HttpPost("TokenTest")]
    public TPResponse<bool> TokenTest()
    {
        return TPResponse.New(true);
    }



    /// <summary>
    /// 管理员给用户重置密码
    /// </summary>
    /// <param name="userBusiness"></param>
    /// <param name="pass"></param>
    /// <returns></returns>
    [HttpPost("RestorePassword")]
#if DEBUG

#else
    [TPOKAdmin]
#endif
    public TPResponse<Res_2Para> RestorePassword(
        [FromServices] IUser_Business userBusiness,
        [FromBody] LoginInfo pass)
    {
        var (status, msg) = userBusiness.RestorePassword(pass.Account, Config.BaseConfig.InitPassword);
        return TPResponse.New(Res_2Para.New(status, msg));
    }

#if DEBUG
    /// <summary>
    /// 管理员给用户重置密码
    /// </summary>
    /// <param name="userBusiness"></param> 
    /// <returns></returns>
    [HttpPost("RestoreAllPassword")]
    public TPResponse<bool> RestoreAllPassword([FromServices] IUser_Business userBusiness)
    {
        var (account, _) = ScopeUser.GetUserAccountName();

        var sysUsers = userBusiness.GetAll();
        //var list = new List<(bool, string)>();
        var res = false;
        foreach (var user in sysUsers)
        {
            var (status, msg) = userBusiness.RestorePassword(user.Account, Config.BaseConfig.InitPassword);
            res = res && status;
        }

        var sysUsers2 = userBusiness.GetAll();
        foreach (var user in sysUsers2)
        {
            user.Status = 11;
            user.Update_time = FunCommon.GetStandardTimeStamp();
            user.Apply_time = FunCommon.GetStandardTimeStamp();
            user.Handle_account = account;
            userBusiness.Update(user);
        }

        return TPResponse.New(res);
    }
#endif

}

/// <summary>
/// 登录信息返回值
/// </summary>
public class LoginResponse
{
    /// <summary>
    /// 正常状态
    /// </summary> 
    /// <param name="msg"></param>
    /// <param name="token"></param>
    /// <param name="account"></param>
    /// <param name="userName"></param>
    /// <param name="isAdmin"></param>
    /// <returns></returns>
    public static LoginResponse OK(string msg, string token, string account, string userName, bool isAdmin)
    {
        return new LoginResponse
        {
            Status = true,
            Msg = msg,
            Token = token,
            Account = account,
            UserName = userName,
            IsAdmin = isAdmin
        };
    }

    /// <summary>
    /// 登录失败状态
    /// </summary> 
    /// <param name="msg"></param> 
    /// <returns></returns>
    public static LoginResponse Fail(string msg)
    {
        return new LoginResponse
        {
            Status = false,
            Msg = msg,
            Token = "",
            Account = "",
            UserName = "",
            IsAdmin = false
        };
    }

    /// <summary>
    /// 登录状态
    /// </summary>
    public bool Status { get; set; }

    /// <summary>
    /// 登录信息
    /// </summary> 
    public string Msg { get; set; }

    /// <summary>
    /// Token
    /// </summary>
    public string Token { get; set; }

    /// <summary>
    /// 账号
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 用户名
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 是否为管理员
    /// </summary>
    public bool IsAdmin { get; set; }
}

