// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using T2ACore;

namespace PTools_PSilo.Controllers;

/// <summary>
/// Menu控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
public class MenuController : ControllerBase
{
    private readonly IMenu_Business MenuBusiness;
    /// <summary>
    /// Menu构造函数
    /// </summary>
    public MenuController(IMenu_Business inDI)
    {
        MenuBusiness = inDI;
    }

    /// <summary>
    /// 获取系统菜单树，Children
    /// </summary> 
    /// <returns></returns>
    [HttpGet]
    [TPOKAdmin]
    public TPResponse<Res_MenuInTree> GetSysMenusTree()
    {
        var (account, username) = ScopeUser.GetUserAccountName();
        var res = new List<Menu_InTree>();
        var menu_menu = new Menu_InTree();
        menu_menu.Code = "Sys_menu";
        menu_menu.Label = "菜单管理";
        menu_menu.Path = "Sys_menu";
        menu_menu.Alias = "菜单管理";
        menu_menu.Sort = 1;
        res.Add(menu_menu);

        var menu_language = new Menu_InTree();
        menu_language.Code = "Sys_language";
        menu_language.Label = "多语言";
        menu_language.Path = "Sys_language";
        menu_language.Alias = "多语言";
        menu_language.Sort = 2;
        res.Add(menu_language);

        var menu_file = new Menu_InTree();
        menu_file.Code = "File_record";
        menu_file.Label = "文件记录";
        menu_file.Path = "File_record";
        menu_file.Alias = "文件记录";
        menu_file.Sort = 3;
        res.Add(menu_file);

        //var menu_auth_role = new Menu_InTree();
        //menu_auth_role.Code = "Auth_role";
        //menu_auth_role.Label = "角色定义";
        //menu_auth_role.Path = "Auth_role";
        //menu_auth_role.Alias = "角色定义";
        //menu_auth_role.Sort = 4;
        //res.Add(menu_auth_role);

        //var menu_tenant = new Menu_InTree();
        //menu_tenant.Code = "Sys_tenant";
        //menu_tenant.Label = "租户管理";
        //menu_tenant.Path = "Sys_tenant";
        //menu_tenant.Alias = "租户管理";
        //menu_tenant.Sort = 5;
        //res.Add(menu_tenant);

        //var menu_user = new Menu_InTree();
        //menu_user.Code = "Sys_user";
        //menu_user.Label = "人员管理";
        //menu_user.Path = "Sys_user";
        //menu_user.Alias = "人员管理";
        //menu_user.Sort = 6;
        //res.Add(menu_user);

        //var menu_assets = new Menu_InTree();
        //menu_assets.Code = "Auth_assets";
        //menu_assets.Label = "权限配置";
        //menu_assets.Path = "Auth_assets";
        //menu_assets.Alias = "权限配置";
        //menu_assets.Sort = 7;
        //res.Add(menu_assets);
        res = [.. res.OrderBy(x => x.Sort)];

        return TPResponse.New(new Res_MenuInTree()
        {
            Status = true,
            Msg = "Admin",
            UserName = username,
            Datas = res,
        });
    }
    /// <summary>
    /// 获取管理菜单树，Children
    /// </summary> 
    /// <returns></returns>
    [HttpGet]
    [TPOK]
    public TPResponse<Res_MenuInTree> GetAdminMenusTree()
    {
        var (account, username) = ScopeUser.GetUserAccountName();
#if DEBUG
        account = "1713";
        username = "Admin";
#endif
        var res = new List<Menu_InTree>();
        var menu_dict_silo = new Menu_InTree();
        menu_dict_silo.Code =  "dict_silo";
        menu_dict_silo.Label = "库型";
        menu_dict_silo.Path =  "dict_silo";
        menu_dict_silo.Alias = "库型";
        menu_dict_silo.Sort = 1;
        res.Add(menu_dict_silo);

        var menu_rfa_resource = new Menu_InTree();
        menu_rfa_resource.Code =  "rfa_resource";
        menu_rfa_resource.Label = "族资源";
        menu_rfa_resource.Path =  "rfa_resource";
        menu_rfa_resource.Alias = "族资源";
        menu_rfa_resource.Sort = 2;
        res.Add(menu_rfa_resource);

        var menu_task_base = new Menu_InTree();
        menu_task_base.Code =  "task_base";
        menu_task_base.Label = "建模任务";
        menu_task_base.Path =  "task_base";
        menu_task_base.Alias = "建模任务";
        menu_task_base.Sort = 3;
        res.Add(menu_task_base);

        var menu_task_result = new Menu_InTree();
        menu_task_result.Code =  "task_result";
        menu_task_result.Label = "任务结果";
        menu_task_result.Path =  "task_result";
        menu_task_result.Alias = "任务结果";
        menu_task_result.Sort = 4;
        res.Add(menu_task_result);

        var menu_template_silo = new Menu_InTree();
        menu_template_silo.Code =  "template_silo";
        menu_template_silo.Label = "库型模板";
        menu_template_silo.Path =  "template_silo";
        menu_template_silo.Alias = "库型模板";
        menu_template_silo.Sort = 5;
        res.Add(menu_template_silo);

        res = [.. res.OrderBy(x => x.Sort)];

        return TPResponse.New(new Res_MenuInTree()
        {
            Status = true,
            Msg = "Admin",
            UserName = username,
            Datas = res,
        });
    }

    /// <summary>
    /// 获取菜单树，Children
    /// </summary>
    /// <param name="AuthBusiness"></param>
    /// <param name="assetExecuter"></param>
    /// <returns></returns>
    [HttpGet]
    [TPOK]
    public TPResponse<Res_MenuInTree> GetMenusTree(
        [FromServices] IAuthBusiness AuthBusiness,
        [FromServices] IAssetExecuter assetExecuter)
    {
        var (account, username) = ScopeUser.GetUserAccountName();
        var (test, msg, keys) = GetMenuKeys(AuthBusiness, assetExecuter);
        if (test)
        {
            var res = new List<Menu_InTree>();
            if (msg == "OK")
            {
                res = MenuBusiness.GetTreeWithKeys(keys);
            }
            else if (msg == "All")
            {
                res = MenuBusiness.GetTree();
            }

            return TPResponse.New(new Res_MenuInTree()
            {
                Status = true,
                Msg = msg,
                UserName = username,
                Datas = res,
            });
        }
        else
        {
            return TPResponse.New(new Res_MenuInTree()
            {
                Status = false,
                Msg = msg,
                UserName = username,
                Datas = null,
            });
        }
    }


    /// <summary>
    /// 获取菜单，平铺数据
    /// </summary>
    /// <param name="menuSearch"></param>
    /// <param name="AuthBusiness"></param>
    /// <param name="assetExecuter"></param>
    /// <returns></returns>
    [HttpPost]
    [TPOK]
    public TPResponse<List<Menu_Class>> GetMenus(
        [FromBody] Menu_Search menuSearch,
        [FromServices] IAuthBusiness AuthBusiness,
        [FromServices] IAssetExecuter assetExecuter)
    {
        var (test, msg, keys) = GetMenuKeys(AuthBusiness, assetExecuter);

        if (test)
        {
            var res = new List<Menu_Class>();
            if (msg == "OK")
            {
                res = MenuBusiness.SearchBy_Codes(keys);
            }
            else if (msg == "All")
            {
                res = MenuBusiness.GetAll();
            }

            if (!string.IsNullOrEmpty(menuSearch.Code))
            {
                res = res.FindAll(x => x.Code == menuSearch.Code);
            }
            if (!string.IsNullOrEmpty(menuSearch.Label))
            {
                res = res.FindAll(x => x.Label.Contains(menuSearch.Label));
            }

            res = res.OrderBy(x => x.Sort).ThenBy(x => x.Parent_id).ToList();

            return TPResponse.New(res);
        }
        else
        {
            return TPResponse.Bad<List<Menu_Class>>(msg, null);
        }

    }

    /// <summary>
    /// 获取有权限的菜单Key
    /// </summary>
    /// <param name="AuthBusiness"></param>
    /// <param name="assetExecuter"></param>
    /// <returns></returns>
    private static (bool Status, string Msg, List<string> MenuKeys) GetMenuKeys(
        IAuthBusiness AuthBusiness, IAssetExecuter assetExecuter)
    {
        if (!Config.BaseConfig.UsingAuth)
        {
            return (true, "All", null);
        }

        var (account, userName) = ScopeUser.GetUserAccountName();
        var groups = AuthBusiness.GetAssetsForUser(account);
        var assets = assetExecuter.GetAssetsResult(groups);
        if (assets == null)
        {
            return (false, "无权限", null);
        }
        else
        {
            var menuAssets = assets.FindAll(x => x.AssetName == "Menu");
            var keys = new List<string>();
            foreach (var item in menuAssets)
            {
                keys.AddRange(item.Patterns);
            }
            return (true, "OK", keys);
        }
    }


    /// <summary>
    /// 获取单个菜单
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    [TPOKAdmin]
    public TPResponse<Menu_Class> Get([FromRoute] Guid inId)
    {
        var res = MenuBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    [TPOKAdmin]
    public TPResponse<Res_2Para> Add([FromBody] Menu_Class inEntity)
    {
        if (inEntity.Id == Guid.Empty)
        {
            inEntity.Id = FunCommon.MakeSortedGuid();
        }
        var res = MenuBusiness.Add(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    [TPOKAdmin]
    public TPResponse<Res_2Para> Update([FromBody] Menu_Class inEntity)
    {
        //添加一些判断，修改操作主键很重要
        var res = MenuBusiness.Update(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    [TPOKAdmin]
    public TPResponse<Res_2Para> Delete([FromBody] Guid[] arr)
    {
        var subMenus = MenuBusiness.SearchBy_Parent_ids([.. arr]);
        if (subMenus.Count > 0)
        {
            var menuNames = subMenus.Select(x => x.Label);
            var msg = "删除的菜单拥有以下子菜单【" + string.Join(",", menuNames) + "】，删除失败";
            return TPResponse.New(Res_2Para.New(false, msg));
        }
        else
        {
            var res = MenuBusiness.DeleteByIds(arr);
            var msg = res == arr.Length ? "操作成功" : "操作失败";
            return TPResponse.New(Res_2Para.New(res == arr.Length, msg));
        }


    }

#if DEBUG

    /// <summary>
    /// 创建菜单视图
    /// </summary>
    /// <returns></returns>
    [HttpPost]
    [Tags("创建菜单视图")]
    public TPResponse<string> MakeViewsByMenus()
    {
        var codeDir = Common.CurrentDllPath.Replace("\\Backend_cs\\bin\\Debug\\net8.0\\", "") +
                      "\\Frontend\\src\\views\\";
        Directory.CreateDirectory(codeDir);

        var menus = MenuBusiness.GetAll()
            .OrderBy(x => x.Sort).ToList();

        var list1 = new List<string>();
        var list2 = new List<string>();

        foreach (var menu in menus)
        {
            var menuPattern = "P" + menu.Sort.ToString() + "_" + menu.Code;

            var subPath = codeDir + menuPattern + "\\";
            Directory.CreateDirectory(subPath);

            if (!System.IO.File.Exists(subPath + menuPattern + "_req.js"))
            {
                var jsContent = "import request from '@utility/request';";
                System.IO.File.WriteAllText(subPath + menuPattern + "_req.js", jsContent);
            }

            if (!System.IO.File.Exists(subPath + menuPattern + ".vue"))
            {
                var vueContent = "<script setup></script>\r\n<template></template>\r\n<style scoped></style>";
                System.IO.File.WriteAllText(subPath + menuPattern + ".vue", vueContent);
            }

            list1.Add("import " + menuPattern + " from '../views/" + menuPattern + "/" + menuPattern + ".vue';");
            list2.Add("<" + menuPattern + " v-else-if=\"menuKey == '" + menu.Code + "'\"></" + menuPattern + ">");

        }

        list1.Add("");
        list1.AddRange(list2);
        System.IO.File.WriteAllLines(codeDir + "GenCode.txt", list1);

        return TPResponse.New(codeDir);
    }

    /// <summary>
    /// 获取全部菜单
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    [TPOKAdmin]
    public TPResponse<List<Menu_Class>> GetAll()
    {
        var res = MenuBusiness.GetAll();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取树形
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    [TPOKAdmin]
    public TPResponse<List<Menu_InTree>> GetTree()
    {
        var res = MenuBusiness.GetTree();
        if (res == null)
        {
            return TPResponse.New(new List<Menu_InTree>());
        }
        return TPResponse.New(res);
    }


#endif
}
