namespace PTools_PSilo.Controllers;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230323

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using T2ACore;

/// <summary>
/// 文件上传控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOKAdmin]
public class OssController : ControllerBase
{
    /// <summary>
    /// 分页高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <param name="fileRecordBusiness">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<File_record_Class>> MultiPagedSearch(
        [FromBody] File_record_paged_Search inSearchModel,
        [FromServices] IFile_record_Business fileRecordBusiness)
    {
        var (total, datas) = fileRecordBusiness.MultiPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <param name="fileRecordBusiness"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<File_record_Class> Get([FromRoute] Guid inId,
        [FromServices] IFile_record_Business fileRecordBusiness)
    {
        var res = fileRecordBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

#if DEBUG

    private readonly IFileMange_Business FileMangeBusiness;

    /// <summary>
    /// 构造函数
    /// </summary>
    public OssController(IFileMange_Business fileMangeBusiness)
    {

        FileMangeBusiness = fileMangeBusiness;
    }

    /// <summary>
    /// 接收到文件以流的形式上传
    /// </summary>
    /// <param name="uploadFile"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadSingleFile(IFormFile uploadFile)
    {
        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var res = await FileMangeBusiness.UploadFile(uploadFile, account, userName, tenant);

        return res == null
            ? TPResponse.Bad<Res_UploadFile>("failed")
            : TPResponse.New(res);
    }

    /// <summary>
    /// 接收到文件以流的形式上传
    /// </summary>
    /// <param name="formCollection"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadFile(IFormCollection formCollection)
    {
        var files = formCollection.Files;
        if (files.Count < 1)
        {
            return TPResponse.Bad<Res_UploadFile>("No File");
        }
        if (files.Count > 1)
        {
            return TPResponse.Bad<Res_UploadFile>("Only 1 File Allowed");
        }

        IFormFile uploadFile = files.FirstOrDefault();

        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var res = await FileMangeBusiness.UploadFile(uploadFile, account, userName, tenant);

        return res == null
            ? TPResponse.Bad<Res_UploadFile>("failed")
            : TPResponse.New(res);
    }

    /// <summary>
    /// 接收到文件以流的形式上传
    /// </summary>
    /// <param name="inUpload"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadFileFromBytes(Req_FileUpLoadPara inUpload)
    {
        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var res = await FileMangeBusiness.UploadFileByBytes(inUpload.FileContent,
            inUpload.FileName, inUpload.ContentType, account, userName, tenant);

        return res == null
            ? TPResponse.Bad<Res_UploadFile>("failed")
            : TPResponse.New(res);
    }

    /// <summary>
    /// 接收到多个文件以流的形式上传
    /// </summary>
    /// <param name="formCollection"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFiles>> UploadFiles(IFormCollection formCollection)
    {
        var files = formCollection.Files;

        if (files.Count < 1)
        {
            return TPResponse.Bad<Res_UploadFiles>("No File");
        }

        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var res = await FileMangeBusiness.UploadFiles(files, account, userName, tenant);

        return TPResponse.New(res);
    }

    /// <summary>
    /// 接收一个压缩文件，并进行一层解压
    /// </summary>
    /// <param name="formCollection"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadZipFile(IFormCollection formCollection)
    {
        var files = formCollection.Files;
        if (files.Count < 1)
        {
            return TPResponse.Bad<Res_UploadFile>("No File");
        }
        if (files.Count > 1)
        {
            return TPResponse.Bad<Res_UploadFile>("Only 1 File Allowed");
        }

        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var uploadZip = files.FirstOrDefault();

        //TODO 需要确认此处是否需要返回Bucket

        var res = await FileMangeBusiness.UploadZipFile(uploadZip, account, userName, tenant);

        return res == null
            ? TPResponse.Bad<Res_UploadFile>("failed")
            : TPResponse.New(res);
    }

    /// <summary>
    /// 以流的方式获取文件
    /// </summary>
    /// <param name="fileReq"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult> GetObjectStream([FromBody] Req_RequestFile fileReq)
    {
        string fileName = Path.GetFileName(fileReq.FullPath);
        var ext = Path.GetExtension(fileReq.FullPath); //扩展名

        //TODO 校验申请文件人的租户是否与资源所属租户一致

        var (stream, meg) = await FileMangeBusiness.GetObjectStreamOss(
            fileReq.FullPath, Config.OssConfig.BucketName);
        return File(stream, FunOss.GetContentType(ext), fileName);
    }

    /// <summary>
    /// 以流的方式获取文件
    /// </summary>
    /// <param name="remaining"></param>
    /// <param name="fileBusiness"></param>
    /// <returns></returns>
    [HttpGet("{*remaining}")]
    public async Task<IActionResult> Download(
        [FromRoute] string remaining,
        [FromServices] IFileMange_Business fileBusiness)
    {
        var filePath = remaining.Replace("%2F", "//");

        var fileInfo = new FileInfo(filePath);
        var (ms, msg) = await fileBusiness.GetObjectStreamOss(
            filePath, Config.OssConfig.BucketName);

        //TODO 校验申请文件人的租户是否与资源所属租户一致

        if (msg == "ok")
        {
            return File(ms, FunOss.GetContentType(fileInfo.Name), fileInfo.Name);
        }
        else
        {
            return new JsonResult(new { msg });
        }
    }

    /// <summary>
    /// 获取文件
    /// </summary>
    /// <param name="remaining"></param>
    /// <param name="fileBusiness"></param>
    /// <returns></returns>
    [HttpGet("{*remaining}")]
    public async Task<TPResponse<Res_File<string>>> GetFile(
        [FromRoute] string remaining,
        [FromServices] IFileMange_Business fileBusiness)
    {
        var filePath = remaining.Replace("%2F", "//");

        var fileInfo = new FileInfo(filePath);
        var (ms, msg) = await fileBusiness.GetObjectStreamOss(
            filePath, Config.OssConfig.BucketName);

        if (msg == "ok")
        {
            return TPResponse.New(Res_File<string>.New(fileInfo.Name, ms, ""));
        }
        else
        {
            return TPResponse.New(Res_File<string>.Bad(msg, null, ""));
        }
    }


    /// <summary>
    /// 清空桶
    /// </summary>
    /// <returns></returns>
    [HttpDelete]
    public async Task<TPResponse<Res_2Para>> ClearBucket()
    {
        var res = await FileMangeBusiness.ClearBucket();
        return TPResponse.New(Res_2Para.New(res.Status, res.Msg));
    }


#endif
}

