namespace PTools_PSilo.Controllers;
// This file is generated by TABLE2API.
// If you met a bug, please tell me, thanks!
// wrx 20240105
// 注意：
//   1.使用本接口上传大文件时，需要在Program.cs中开启大文件支持
//   2.缓存推荐使用Redis

using System;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using T2ACore;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System.Collections.Generic;

/// <summary>
/// Animation控制器
/// </summary>
[ApiController]
[Route("/T2ACore/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Sys")]
[TPOK]
public class UploadFileController : ControllerBase
{

    #region 文件相关
    /// <summary>
    /// 接收到文件以流的形式上传
    /// </summary>
    /// <param name="fileBusiness"></param>
    /// <param name="formCollection"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadFile(
        [FromServices] IFileMange_Business fileBusiness,
        [FromForm] IFormCollection formCollection)
    {
        var files = formCollection.Files;
        if (files.Count < 1)
        {
            return TPResponse.Bad<Res_UploadFile>("No File");
        }
        if (files.Count > 1)
        {
            return TPResponse.Bad<Res_UploadFile>("Only 1 File Allowed");
        }

        IFormFile uploadFile = files.FirstOrDefault();

        var (account, userName) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        Res_UploadFile res;
        if (uploadFile.FileName.EndsWith("zip"))
        {
            //TODO 需要确认此处是否需要返回Bucket
            res = await fileBusiness.UploadZipFile(uploadFile, account, userName, tenant);
        }
        else
        {
            res = await fileBusiness.UploadFile(uploadFile, account, userName, tenant);
        }

        return res == null
            ? TPResponse.Bad<Res_UploadFile>("failed")
            : TPResponse.New(res);
    }

    /// <summary>
    /// 接收到文件分块
    /// </summary>
    /// <param name="cache"></param>
    /// <param name="chunk"></param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<bool> UploadChunk(
        [FromServices] ICache cache,
        [FromBody] FileChunk chunk)
    {
        var taskIdStr = chunk.TaskId.ToString().ToUpper();
        cache.Insert(
            "UploadChunk_" + taskIdStr + "_" + chunk.Sort,
            chunk.FileChunkContent, DateTime.Now.AddHours(24));
        return TPResponse.New(true);
    }

    /// <summary>
    /// 接收到文件分块,完成
    /// </summary>
    /// <param name="fileBusiness"></param>
    /// <param name="cache"></param>
    /// <param name="chunkFinish"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadChunkEnd(
        [FromServices] IFileMange_Business fileBusiness,
        [FromServices] ICache cache,
        [FromBody] FileChunkFinish chunkFinish)
    {
        var taskIdStr = chunkFinish.TaskId.ToString().ToUpper();
        //var fileContent = "";

        var calHash = "";
        var allBytes = new List<byte>();
        for (int i = 0; i < chunkFinish.Total; i++)
        {
            var key = "UploadChunk_" + taskIdStr + "_" + i.ToString();
            var dataInCache = cache.Get(key).ToString();
            byte[] chunkBytes = Convert.FromBase64String(dataInCache);
            allBytes.AddRange(chunkBytes);
            //fileContent += dataInCache;
            calHash += FunCommon.CalculateHash(dataInCache);
        }

        //var calHash = ToolCommon.CalculateHash(fileContent);

        //清除缓存
        cache.BlurRemove("UploadChunk_" + taskIdStr + "_*");

        if (calHash != chunkFinish.HashCode)
        {
            return TPResponse.Bad<Res_UploadFile>("哈希不符，请重新上传");
        }
        else
        {
            var (account, userName) = ScopeUser.GetUserAccountName();
            var tenant = ScopeUser.GetUserTenant();

            Res_UploadFile res;
            //var bytes = Convert.FromBase64String(fileContent);

            if (!chunkFinish.FileName.EndsWith("zip"))
            {
                res = await fileBusiness.UploadFileByBytes(allBytes.ToArray(),
                    chunkFinish.FileName, "application/octet-stream",
                    account, userName, tenant);
            }
            else
            {
                res = await fileBusiness.UploadZipFileByBytes(allBytes.ToArray(),
                    chunkFinish.FileName, "application/octet-stream",
                    account, userName, tenant);
            }

            return res == null
                ? TPResponse.Bad<Res_UploadFile>("failed")
                : TPResponse.New(res);
        }
    }

    /// <summary>
    /// 开启大文件直接给到oss
    /// </summary>
    /// <param name="fileBusiness"></param>
    /// <param name="chunkStart"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<string>> UploadChunkDirectStart(
        [FromServices] IFileMange_Business fileBusiness,
        [FromBody] FileChunkStart chunkStart)
    {
        var taskIdStr = chunkStart.TaskId.ToString().ToUpper();  //前端随机出来的id
        var objectName = taskIdStr + "/" + chunkStart.FileName;

        var uploadId = await fileBusiness.CreateUploadId(objectName);

        return TPResponse.New(uploadId);
    }


    /// <summary>
    /// 接收到文件分块,直接给到oss
    /// </summary>
    /// <param name="fileBusiness"></param>
    /// <param name="chunk"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<bool>> UploadChunkDirect(
        [FromServices] IFileMange_Business fileBusiness,
        [FromBody] FileChunk chunk)
    {
        var taskIdStr = chunk.TaskId.ToString().ToUpper();  //前端随机出来的id
        var objectName = taskIdStr + "/" + chunk.FileName;
        byte[] chunkBytes = Convert.FromBase64String(chunk.FileChunkContent);

        FunConsole.Log("第" + chunk.Sort + "个分块大小：" + 
            chunkBytes.Length, ConsoleColor.Green);
        var (status, msg) = await fileBusiness.UploadChunk(objectName,
            chunk.UploadId, chunkBytes, chunk.Sort, chunk.Total);

        if (!status)
        {
            FunConsole.Log(msg, ConsoleColor.Red);
        }

        return TPResponse.New(status);
    }

    /// <summary>
    /// 接收到文件分块,完成
    /// </summary>
    /// <param name="fileBusiness"></param> 
    /// <param name="chunkFinish"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<TPResponse<Res_UploadFile>> UploadChunkDirectEnd(
        [FromServices] IFileMange_Business fileBusiness,
        [FromBody] FileChunkFinish chunkFinish)
    {
        var taskIdStr = chunkFinish.TaskId.ToString().ToUpper();//前端随机出来的id，跟单个分片的Id一样

        var objectName = taskIdStr + "/" + chunkFinish.FileName;

        var (account, username) = ScopeUser.GetUserAccountName();
        var tenant = ScopeUser.GetUserTenant();

        var res = await fileBusiness.UploadChunkEnd(
            objectName, chunkFinish.UploadId, account, username, tenant);

        if (!res.Status)
        {
            TPResponse.Bad<Res_UploadFile>(res.Msg);
        }

        return TPResponse.New(res);
    }

    #endregion 文件相关

}
