<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220101
defineProps({
    msg: String,
});

const pngPath = '/' + import.meta.env.VITE_NAMESPACE + '/logo.png';
</script>

<template>
    <div id="container">
        <img alt="BIM" :src="pngPath" />
        <h1>{{ msg }}</h1>
    </div>
</template>
<style scoped>
#container {
    text-align: center;
}
</style>
