// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using SqlSugar;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// Auth_assets实体
/// </summary> 
[SugarTable("auth_assets")]
public class Auth_assets_Class
{
    /// <summary>
    /// Id
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        IsIdentity = true,
        ColumnName = "Id",
        ColumnDataType = "int",
        ColumnDescription = "Id",
        Length = 0
    )]
    public int Id { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建账号{Search}",
        Length = 255,
        IsNullable = true 
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人姓名",
        Length = 255,
        IsNullable = true 
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        Length = 0,
        IsNullable = true 
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        Length = 255,
        IsNullable = true 
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 分类(g,p)
    /// </summary>
    [SugarColumn(
        ColumnName = "Section",
        ColumnDataType = "varchar",
        ColumnDescription = "分类(g,p)",
        Length = 255,
        IsNullable = true 
    )]
    public string Section { get; set; }

    /// <summary>
    /// 类型
    /// </summary>
    [SugarColumn(
        ColumnName = "Type",
        ColumnDataType = "varchar",
        ColumnDescription = "类型(g,g2,g3,p,p2,p3)",
        Length = 255,
        IsNullable = true 
    )]
    public string Type { get; set; }

    /// <summary>
    /// 账号或角色编码
    /// </summary>
    [SugarColumn(
        ColumnName = "Value1",
        ColumnDataType = "varchar",
        ColumnDescription = "账号或角色编码",
        Length = 255,
        IsNullable = true 
    )]
    public string Value1 { get; set; }

    /// <summary>
    /// 所拥有的角色编码或租户
    /// </summary>
    [SugarColumn(
        ColumnName = "Value2",
        ColumnDataType = "varchar",
        ColumnDescription = "所拥有的角色编码或租户",
        Length = 255,
        IsNullable = true 
    )]
    public string Value2 { get; set; }

    /// <summary>
    /// 租户或资源类别（Menu，Controller）
    /// </summary>
    [SugarColumn(
        ColumnName = "Value3",
        ColumnDataType = "varchar",
        ColumnDescription = "租户或资源类别（Menu，Controller）",
        Length = 255,
        IsNullable = true 
    )]
    public string Value3 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value4",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value4 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value5",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value5 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value6",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value6 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value7",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value7 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value8",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value8 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value9",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value9 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value10",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value10 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value11",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value11 { get; set; }

    /// <summary>
    /// 特征值
    /// </summary>
    [SugarColumn(
        ColumnName = "Value12",
        ColumnDataType = "varchar",
        ColumnDescription = "特征值",
        Length = 255,
        IsNullable = true 
    )]
    public string Value12 { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

    /// <summary>
    /// 由人员构造资源类
    /// </summary>
    /// <param name="optAccount"></param>
    /// <param name="optUserName"></param>
    /// <param name="tenant"></param>
    /// <param name="region"></param>
    /// <param name="account"></param>
    /// <param name="roleCode"></param>
    /// <returns></returns>
    public static Auth_assets_Class CastForUser(
        string optAccount, string optUserName, string tenant,
        string region, string account, string roleCode)
    {
        var asset = new Auth_assets_Class();
        asset.Create_account = optAccount;
        asset.Create_username = optUserName;
        asset.Create_time = FunCommon.GetStandardTimeStamp();
        asset.Section = "g";
        asset.Type = region;
        asset.Value1 = account;
        asset.Value2 = roleCode;
        asset.Value3 = tenant;
        asset.Value4 = "Person";
        return asset;
    }

    /// <summary>
    /// 由资源创建
    /// </summary>
    /// <param name="optAccount"></param>
    /// <param name="optUserName"></param>
    /// <param name="tenant"></param>
    /// <param name="assetType"></param>
    /// <param name="roleCode"></param>
    /// <param name="pType"></param>
    /// <param name="patterns"></param>
    /// <returns></returns>
    public static Auth_assets_Class CastFromAsset(
        string optAccount, string optUserName, string tenant,
        string assetType, string roleCode, string pType,
        List<string> patterns)
    {
        var newAsset = new Auth_assets_Class();
        newAsset.Create_account = optAccount;
        newAsset.Create_username = optUserName;
        newAsset.Create_time = FunCommon.GetStandardTimeStamp();
        newAsset.Section = "p";
        newAsset.Type = assetType;
        newAsset.Value1 = roleCode;
        newAsset.Value2 = tenant;
        newAsset.Value3 = pType;

        for (int i = 0; i < patterns.Count; i++)
        {
            var proInfo = AuthCommon.GetAssetPatternName(i);
            proInfo.SetValue(newAsset, patterns[i]);
        }
        return newAsset;

    }

    /// <summary>
    /// 创建测试数据
    /// </summary> 
    /// <param name="assetType">类型(g,g2,g3)</param>
    /// <param name="accountOrRoleCode">账号或角色编码</param>
    /// <param name="havingRoleCode">拥有的角色编码</param> 
    /// <param name="isUser">是用户</param> 
    /// <returns></returns>
    public static Auth_assets_Class TestDataMaker_G(string assetType,
        string accountOrRoleCode, string havingRoleCode, bool isUser = false)
    {
        var res = new Auth_assets_Class();
        res.Create_account = "1713";
        res.Create_username = "wrx";
        res.Create_time = FunCommon.GetStandardTimeStamp();
        res.Section = "g";
        res.Type = assetType; // "g",
        res.Value1 = accountOrRoleCode; // "1713",
        res.Value2 = havingRoleCode; // "dev2",
        res.Value3 = "Default";

        if (isUser)
        {
            res.Value4 = "Person";
        }

        return res;
    }

    /// <summary>
    /// 创建测试数据
    /// </summary> 
    /// <param name="assetType">类型(p,p2,p3)</param>
    /// <param name="roleCode">角色编码</param>
    /// <param name="assetTitle">资源类型名称(Menu, Controller)</param> 
    /// <param name="patterns">特征值</param> 
    /// <returns></returns>
    public static Auth_assets_Class TestDataMaker_P(string assetType,
        string roleCode, string assetTitle, params string[] patterns)
    {
        var res = new Auth_assets_Class();
        res.Create_account = "1713";
        res.Create_username = "wrx";
        res.Create_time = FunCommon.GetStandardTimeStamp();
        res.Section = "p";
        res.Type = assetType; // "p",
        res.Value1 = roleCode; // "dev2",
        res.Value2 = "Default";
        res.Value3 = assetTitle; //Menu,Controller  
        for (int i = 0; i < patterns.Length; i++)
        {
            var pattern = patterns[i];
            var proInfo = AuthCommon.GetAssetPatternName(i + 4);
            proInfo.SetValue(res, pattern);
        }

        return res;
    }



}
