<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220722
import { NCard } from 'naive-ui';
import Theme from '../theme/theme.vue';

defineExpose({ DoMenuRefresh }); // 将方法暴露出来

//刷新菜单
function DoMenuRefresh() {}
</script>
<template>
    <Theme>
        <NCard :bordered="true" id="layoutCard">
            <slot name="main">内容</slot>
        </NCard>
    </Theme>
</template>
<style>
#layoutCard {
    height: 100%;
}
</style>
