// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20230922

using System;
using SqlSugar;
using System.Linq;
using System.Collections.Generic;
using T2ACore;
using Microsoft.Extensions.Logging;

namespace PTools_PSilo;

/// <summary>
/// Rfa_resource业务类
/// </summary>
public partial class Rfa_resource_Business : IRfa_resource_Business
{

    private readonly ILogger<Rfa_resource_Business> _logger;
    private readonly IDBHelper dbHelper;
    private readonly string connId;
    private readonly string CacheKey = "_Rfa_resource_AllData";
    private readonly ICache CacheFunc;

    /// <summary>
    /// 构造函数
    /// </summary>
    public Rfa_resource_Business(IDBHelper inDI, ICache inDI2,
        ILogger<Rfa_resource_Business> logger)
    {
        _logger = logger;
        dbHelper = inDI;
        CacheFunc = inDI2;
        connId = ScopeUser.GetUserTenant();
    }
    ///////////////////////////////////////////////////////////
    //  以下为新增代码
    ///////////////////////////////////////////////////////////



}
