// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20230922

using System;
using SqlSugar;
using System.Linq;
using System.Collections.Generic;
using T2ACore;
using Microsoft.Extensions.Logging;

namespace PTools_PSilo;

/// <summary>
/// Task_base业务类
/// </summary>
public partial class Task_base_Business : ITask_base_Business
{

    private readonly ILogger<Task_base_Business> _logger;
    private readonly IDBHelper dbHelper;
    private readonly string connId;
    private readonly string CacheKey = "_Task_base_AllData";
    private readonly ICache CacheFunc;
    private readonly IDict_silo_Business DictSiloBusiness;
    private readonly IRfa_resource_Business RfaResourceBusiness;
    private readonly ITask_result_Business TaskResultBusiness;

    /// <summary>
    /// 构造函数
    /// </summary>
    public Task_base_Business(IDBHelper inDI, ICache inDI2,
        IDict_silo_Business dictSiloBusiness,
        IRfa_resource_Business rfaResourceBusiness,
        ITask_result_Business taskResultBusiness,
        ILogger<Task_base_Business> logger)
    {
        _logger = logger;
        dbHelper = inDI;
        CacheFunc = inDI2;
        DictSiloBusiness = dictSiloBusiness;
        RfaResourceBusiness = rfaResourceBusiness;
        TaskResultBusiness = taskResultBusiness;
        connId = ScopeUser.GetUserTenant();
    }
    ///////////////////////////////////////////////////////////
    //  以下为新增代码
    ///////////////////////////////////////////////////////////

    /// <summary>
    /// 根据任务Id计算族放置结果
    /// </summary>
    /// <param name="taskId">任务Id</param>
    /// <returns>族放置计算结果</returns>
    public (bool, string, SiloResult) Calculate(Guid taskId)
    {
        Task_base_Class task = GetOne(taskId);
        if (task == null)
        {
            return (false, "未找到建模任务：" + taskId, null);
            // throw new InvalidOperationException("未找到建模任务：" + taskId);
        }

        //Guid dictSiloId = Guid.Parse(task.Silo_type);
        //Dict_silo_Class dictSilo = dictSiloBusiness.GetOne(dictSiloId);
        //if (dictSilo == null)
        //{
        //    throw new InvalidOperationException("未找到库型字典：" + task.Silo_type);
        //}

        Dict_silo_Class dictSilo = DictSiloBusiness.GetOne(task.Dict_silo_id);
        if (dictSilo == null)
        {
            return (false, "未找到库型：" + task.Dict_silo_id, null);
        }

        List<Rfa_resource_Class> rfas = RfaResourceBusiness.SearchBy_Dict_silo_id(task.Dict_silo_id);
        SiloResult res = SiloCalculator.Calculate(task, dictSilo, rfas);
        List<Task_result_Class> taskResults = new List<Task_result_Class>(res.Placements.Count);
        foreach (SiloPlacement placement in res.Placements)
        {
            taskResults.Add(Task_result_Class.Cast(placement, task.Id));
        }
        TaskResultBusiness.Add(taskResults);

        return (true, "OK", res);
    }

}
