// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20230922

using System;
using SqlSugar;
using System.Linq;
using System.Collections.Generic;
using T2ACore;
using Microsoft.Extensions.Logging;

namespace PTools_PSilo;

/// <summary>
/// Template_silo业务类
/// </summary>
public partial class Template_silo_Business : ITemplate_silo_Business
{

    private readonly ILogger<Template_silo_Business> _logger;
    private readonly IDBHelper dbHelper;
    private readonly string connId;
    private readonly string CacheKey = "_Template_silo_AllData";
    private readonly ICache CacheFunc;

    /// <summary>
    /// 构造函数
    /// </summary>
    public Template_silo_Business(IDBHelper inDI, ICache inDI2,
        ILogger<Template_silo_Business> logger)
    {
        _logger = logger;
        dbHelper = inDI;
        CacheFunc = inDI2;
        connId = ScopeUser.GetUserTenant();
    }
    ///////////////////////////////////////////////////////////
    //  以下为新增代码
    ///////////////////////////////////////////////////////////



}
