namespace PTools_PSilo;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230323

using System.Collections.Generic;
using System.Linq;
using T2ACore;
 
/// <summary>
/// 构造鉴权模型处理方法
/// </summary>
public class AssetExecuter : IAssetExecuter
{
    /// <summary>
    /// 处理逻辑（例子）
    /// </summary>
    /// <param name="groups"></param>
    /// <returns></returns>
    /// <exception cref="System.NotImplementedException"></exception>
    public List<Res_Asset> GetAssetsResult(List<Res_AssetGroup> groups)
    {
        //角色有两个维度，组织机构，岗位，其资源应取交集
        var g = groups.Find(x => x.RoleRegion == "g");
        var g2 = groups.Find(x => x.RoleRegion == "g2");

        if (g == null ||
            g2 == null)
        {
            return null;
        }

        var res = g.Assets.Intersect(g2.Assets, new AssetCompare());

        return res.ToList();
    }
}
