namespace PTools_PSilo;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126
 
using Newtonsoft.Json.Linq;
using RestSharp; 
using T2ACore;

/// <summary>
/// Http通用方法
/// </summary>
public static class FunHttp
{

    /// <summary>
    /// 自由格式，发送企业微信消息
    /// cyl added 20220620
    /// </summary>
    /// <param name="eWeChatAppId">企业微信自建应用AppId</param>
    /// <param name="msgType">消息类型</param>
    /// <param name="inContent">消息内容</param>
    /// <param name="enableAccountTrans">是否开启账号转义(账号转义成企业微信Id)</param>
    /// <param name="tp_token">系统token</param>
    /// <param name="totalURL">白名单URL</param>
    /// <returns></returns>
    public static string FreestylePushData(string eWeChatAppId, string msgType,
        string inContent, bool enableAccountTrans, string tp_token, string totalURL)
    {
        var options = new RestClientOptions(Config.BaseConfig.AuthPath + "/EWeChat/FreestylePushData")
        {
            ThrowOnAnyError = false,
        };

        var client = new RestClient(options);

        var request = new RestRequest().AddHeader("Content-Type", "application/json")
            .AddCookie("tp_token", tp_token, "/", Config.BaseConfig.AuthDomain)
            .AddCookie("RemoteURL", totalURL, "/", Config.BaseConfig.AuthDomain)
            .AddQueryParameter("eWeChatAppId", eWeChatAppId)
            .AddQueryParameter("msgType", msgType)
            .AddQueryParameter("enableAccountTrans", enableAccountTrans.ToString())
            .AddJsonBody(inContent);
        request.Method = Method.Post;
        var response = client.ExecuteAsync(request).GetAwaiter().GetResult();
        return response.Content;
    }

    /// <summary>
    /// 企业微信发送通知
    /// </summary>
    /// <param name="inTemplateId">模板Id</param>
    /// <param name="tp_token">令牌</param>
    /// <param name="inToUsers">要发给谁，逗号隔开的账号</param>
    /// <param name="inContent">发送的内容变量值</param>
    /// <returns></returns>
    public static string PushData(string inTemplateId,
        string tp_token, string inToUsers, JObject inContent)
    {
        var jo = new JObject();
        jo["touser"] = inToUsers; //逗号隔开
        jo["content"] = inContent;

        var url = Config.BaseConfig.AuthPath +
            "/EWeChat/PushData" +
            "?templateId=" + inTemplateId;

        var options = new RestClientOptions(url)
        {
            ThrowOnAnyError = false,
        };

        var client = new RestClient(options);

        var request = new RestRequest()
            .AddCookie("tp_token", tp_token, "/", Config.BaseConfig.AuthDomain)
            .AddHeader("Content-Type", "application/json")
            .AddJsonBody(jo);
        request.Method = Method.Post;
        var response = client.ExecuteAsync(request).GetAwaiter().GetResult();
        return response.Content;
    }

    /// <summary>
    /// 验证Token
    /// </summary>
    /// <param name="tp_token"></param>
    /// <param name="totalURL"></param>
    /// <returns></returns>
    public static string CheckToken(string tp_token, string totalURL)
    {
        var options = new RestClientOptions(Config.BaseConfig.AuthPath + "/TokenTest")
        {
            ThrowOnAnyError = false,
        };

        var client = new RestClient(options);

        var request = new RestRequest()
            .AddHeader("Content-Type", "application/json")
            .AddCookie("tp_token", tp_token, "/", Config.BaseConfig.AuthDomain)
            .AddCookie("RemoteURL", totalURL, "/", Config.BaseConfig.AuthDomain);
        request.Method = Method.Post;
        var response = client.ExecuteAsync(request).GetAwaiter().GetResult();
        return response.Content;
    }

}
