<script lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220101
import { defineComponent } from 'vue';
import { useDialog } from 'naive-ui';
export default defineComponent({
    setup() {
        window.$dialog = useDialog();
    },
});
</script>
<template></template>
