<script lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220101
import { useMessage } from 'naive-ui';
import { defineComponent } from 'vue';

export default defineComponent({
    setup() {
        // 将 Naive UI 的 Message 方法挂载到全局 window 对象上，方便在任何地方调用
        window.$message = useMessage();
    },
});
</script>
<template></template>
