<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20221202
import { NResult, NImage } from 'naive-ui';
import img404 from '../../../src/assets/images/404.png';
import { translate } from '@utility/i18n.js';
</script>
<template>
    <NResult :title="translate.t('您访问的页面不存在')">
        <template #icon>
            <n-image width="1162" :src="img404" />
        </template>
    </NResult>
</template>
<style scoped></style>
