<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220101
import { NModal } from 'naive-ui';
import { onMounted, ref } from 'vue';

const inPara = defineProps({
  show: Boolean, //是否显示
  title: String, //标题
  inWidth: String, //宽度
});
const ww = ref({});
const emit = defineEmits(['modalClose']);

onMounted(() => {
  if (inPara.inWidth == undefined) {
    ww.value = { width: '30%', minWidth: '500px' };
  } else {
    ww.value = { width: '30%', minWidth: inPara.inWidth };
  }
});

function modalClose() {
  emit('modalClose');
}
</script>
<template>
  <n-modal
    :show="inPara.show"
    preset="card"
    :style="ww"
    :title="inPara.title"
    :on-update:show="modalClose"
  >
    <slot></slot>
  </n-modal>
</template>
<style scope></style>
