// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using Newtonsoft.Json; 

namespace T2ACore;

/// <summary>
/// Auth_assets检索类
/// </summary>
public partial class Auth_assets_Search
{
    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    public string Create_account { get; set; } 

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    { 
        return JsonConvert.SerializeObject(this);
    }

  

}
