// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json; 

namespace T2ACore;

/// <summary>
/// auth_role检索类
/// </summary>
public partial class Auth_role_Search
{
    /// <summary>
    /// 父级节点{Search}
    /// </summary>
    public Guid Parent_id { get; set; } 

    /// <summary>
    /// 角色编码{Search}
    /// </summary>
    public string Role_code { get; set; } 

    /// <summary>
    /// 角色租户编码{Search}
    /// </summary>
    public string Role_tenant_code { get; set; } 

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    public string Create_account { get; set; } 

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    public string Update_account { get; set; } 

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    { 
        return JsonConvert.SerializeObject(this);
    }

 

}
