// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using SqlSugar;

namespace T2ACore;

/// <summary>
/// tenant实体
/// </summary> 
[SugarTable("sys_tenant")]
public class Tenant_Class
{
    /// <summary>
    /// Id
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        ColumnName = "id",
        ColumnDataType = "char",
        ColumnDescription = "Id",
        Length = 36
    )]
    public Guid Id { get; set; }

    /// <summary>
    /// 编码{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "code",
        ColumnDataType = "varchar",
        ColumnDescription = "编码{Search}",
        Length = 50,
        IsNullable = true
    )]
    public string Code { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [SugarColumn(
        ColumnName = "title",
        ColumnDataType = "varchar",
        ColumnDescription = "名称",
        Length = 50,
        IsNullable = true
    )]
    public string Title { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建账号{Search}",
        Length = 50,
        IsNullable = true
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人姓名",
        Length = 50,
        IsNullable = true
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        Length = 0,
        IsNullable = true
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_account",
        ColumnDataType = "varchar",
        ColumnDescription = "更新账号{Search}",
        Length = 50,
        IsNullable = true
    )]
    public string Update_account { get; set; }

    /// <summary>
    /// 更新人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "update_username",
        ColumnDataType = "varchar",
        ColumnDescription = "更新人姓名",
        Length = 50,
        IsNullable = true
    )]
    public string Update_username { get; set; }

    /// <summary>
    /// 更新时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_time",
        ColumnDataType = "bigint",
        ColumnDescription = "更新时间{Default:Now}",
        Length = 0,
        IsNullable = true
    )]
    public long Update_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        Length = 255,
        IsNullable = true
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }




}
