// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using SqlSugar;

namespace T2ACore;

/// <summary>
/// user实体
/// </summary> 
[SugarTable("sys_user")]
public class User_Class
{
    /// <summary>
    /// 主键Id
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        IsIdentity = true,
        ColumnName = "id",
        ColumnDataType = "int",
        ColumnDescription = "主键Id",
        Length = 0
    )]
    public int Id { get; set; }

    /// <summary>
    /// 人员Id{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "userId",
        ColumnDataType = "char",
        ColumnDescription = "人员Id{Search}",
        Length = 36,
        IsNullable = false 
    )]
    public Guid UserId { get; set; }

    /// <summary>
    /// 租户编码{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "tenant",
        ColumnDataType = "varchar",
        ColumnDescription = "租户编码{Search}",
        Length = 50,
        IsNullable = true 
    )]
    public string Tenant { get; set; }

    /// <summary>
    /// 账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "account",
        ColumnDataType = "varchar",
        ColumnDescription = "账号{Search}",
        Length = 50,
        IsNullable = false 
    )]
    public string Account { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "userName",
        ColumnDataType = "varchar",
        ColumnDescription = "姓名",
        Length = 50,
        IsNullable = false 
    )]
    public string UserName { get; set; }


    /// <summary>
    /// 密码
    /// </summary>
    [SugarColumn(
        ColumnName = "password",
        ColumnDataType = "varchar",
        ColumnDescription = "密码",
        IsNullable = true,
        Length = 50
    )]
    public string Password { get; set; }

    /// <summary>
    /// 状态(10冻结，11正常)
    /// </summary>
    [SugarColumn(
        ColumnName = "status",
        ColumnDataType = "int",
        ColumnDescription = "状态(10冻结，11正常)",
        IsNullable = true,
        Length = 0
    )]
    public int Status { get; set; }

    /// <summary>
    /// 性别(10女，11男)
    /// </summary>
    [SugarColumn(
        ColumnName = "sex",
        ColumnDataType = "int",
        ColumnDescription = "性别(10女，11男)",
        IsNullable = true,
        Length = 0
    )]
    public int Sex { get; set; }

    /// <summary>
    /// 公司
    /// </summary>
    [SugarColumn(
        ColumnName = "company",
        ColumnDataType = "varchar",
        ColumnDescription = "公司",
        IsNullable = true,
        Length = 255
    )]
    public string Company { get; set; }

    /// <summary>
    /// 手机号
    /// </summary>
    [SugarColumn(
        ColumnName = "phone",
        ColumnDataType = "varchar",
        ColumnDescription = "手机号",
        IsNullable = true,
        Length = 50
    )]
    public string Phone { get; set; }

    /// <summary>
    /// 头像
    /// </summary>
    [SugarColumn(
        ColumnName = "pic_text",
        ColumnDataType = "text",
        ColumnDescription = "头像",
        IsNullable = true,
        Length = 65535
    )]
    public string Pic_text { get; set; }

    /// <summary>
    /// 审核状态(00待处理，10不通过，11通过)
    /// </summary>
    [SugarColumn(
        ColumnName = "process_status",
        ColumnDataType = "int",
        ColumnDescription = "审核状态(00待处理，10不通过，11通过)",
        IsNullable = true,
        Length = 0
    )]
    public int Process_status { get; set; }

    /// <summary>
    /// 申请时间
    /// </summary>
    [SugarColumn(
        ColumnName = "apply_time",
        ColumnDataType = "bigint",
        ColumnDescription = "申请时间",
        IsNullable = true,
        Length = 0
    )]
    public long Apply_time { get; set; } = FunCommon.GetStandardTimeStamp();

    /// <summary>
    /// 处理人
    /// </summary>
    [SugarColumn(
        ColumnName = "handle_account",
        ColumnDataType = "varchar",
        ColumnDescription = "处理人",
        IsNullable = true,
        Length = 50
    )]
    public string Handle_account { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人姓名",
        IsNullable = true,
        Length = 50
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_account",
        ColumnDataType = "varchar",
        ColumnDescription = "更新账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Update_account { get; set; }

    /// <summary>
    /// 更新人姓名
    /// </summary>
    [SugarColumn(
        ColumnName = "update_username",
        ColumnDataType = "varchar",
        ColumnDescription = "更新人姓名",
        IsNullable = true,
        Length = 50
    )]
    public string Update_username { get; set; }

    /// <summary>
    /// 更新时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_time",
        ColumnDataType = "bigint",
        ColumnDescription = "更新时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Update_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        IsNullable = true,
        Length = 50
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }



}
