// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;

namespace T2ACore;

/// <summary>
/// user检索类
/// </summary>
public class User_Search
{
    /// <summary>
    /// 人员Id{Search}
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// 租户编码{Search}
    /// </summary>
    public string Tenant { get; set; }

    /// <summary>
    /// 账号{Search}
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    public string Create_account { get; set; }

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    public string Update_account { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

}

/// <summary>
/// sys_user分页检索类
/// </summary>
public class Sys_user_paged_Search : User_Search
{

    /// <summary>
    /// 页码
    /// </summary>
    public int Page { get; set; }

    /// <summary>
    /// 单页数量
    /// </summary>
    public int PageSize { get; set; }
}
