<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20230131
//注意：不建议多个布局形式进行嵌套
//左右分两段，用于内容布局
//    —————————————————————————————
//    |      |                    |
//    |      |                    |
//    |   1  |         2          |
//    |      |                    |
//    |______|____________________|

const inPara = defineProps({
    LeftWidth: String, //左边宽度
    ColumnGap: String, //列间距
    RowGap: String, //行间距
});
</script>
<template>
    <div class="Indi4-layout">
        <div class="Indi4-left">
            <slot name="left">1</slot>
        </div>
        <div class="Indi4-right">
            <slot name="right">2</slot>
        </div>
    </div>
</template>
<style scoped>
.Indi4-layout {
    display: grid;
    grid-template-rows: 100%;
    grid-template-columns: v-bind('inPara.LeftWidth') auto;
    width: 100%;
    height: 100%;
    row-gap: v-bind('inPara.RowGap');
    column-gap: v-bind('inPara.ColumnGap');
}

.Indi4-left {
    place-content: space-around space-evenly;
    grid-column: 1 / 2;
    grid-row: 1 / 2;
    background-color: var(--tp-contentCard);
    padding: 20px;
}

.Indi4-right {
    place-content: space-around space-evenly;
    grid-column: 2 / 3;
    grid-row: 1 / 2;
    background-color: var(--tp-contentCard);
    padding: 20px;
}
</style>
