<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import type { VNode } from 'vue';
import { NSpace, NDataTable, NButton, NFormItem, NInput, NPagination, NSelect } from 'naive-ui';
import type { DataTableColumns } from 'naive-ui';
import moment from 'moment';
import {
  make_text_NButton,
  make_h_NSpace,
  h_tag,
  make_download_Abutton,
} from '@utility/NaiveHComponent.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { findLabel } from '@utility/OptionsTool.ts';
import { translate } from '@utility/i18n.ts';
import { GetOne, Delete, MultiPagedSearch, GetOptions } from '@request/Basic_Request.ts';
import { confirmDel } from '@common/message/confirmDel.ts';
import Layout_UMD from '@common/layoutIndi/Layout_UMD.vue';
import auth_assets_Form from './auth_assets_Form.vue';
import type { Auth_assets_Class, Auth_assets_Search } from './auth_assets.d.ts';

const itemName = 'Auth_assets';

//检索条件
const queryInfo = ref<Auth_assets_Search>({
  page: 1,
  pageSize: 15,
  create_account: '',
});

const tableLoading = ref(false); //加载中
const columns = ref<DataTableColumns<Auth_assets_Class>>([]); //显示的列
const tableData = ref<Auth_assets_Class[]>([]); //表格数据
const totalCount = ref(0); //数据总数

const auth_assets_FormRef = useTemplateRef('auth_assets_FormRef'); //表单控件
const emit = defineEmits([]);
const inPara = defineProps({});

onMounted(() => {
  //注意，加载选项时可能需要异步处理
  //TODO,整理成异步形式
  resetColumns();
  initData();
});

//初始化数据
function initData() {
  tableLoading.value = true;
  MultiPagedSearch(queryInfo.value, itemName)
    .then((res) => {
      tableData.value = res.datas;
      totalCount.value = res.totalCount;
      tableLoading.value = false;
    })
    .catch((err) => console.error(err));
}

//重置列
function resetColumns() {
  columns.value = [
    {
      key: '__index',
      title: translate.t('序号'),
      align: 'center',
      width: '50px',
      render(_row: Auth_assets_Class, index: number) {
        return index + 1;
      },
    },
    // {
    //   title: translate.t('Id'),
    //   key: 'id',
    //   width: '100px',
    //   ellipsis: {
    //     tooltip: true,
    //   },
    //   sorter: 'default',
    //   render(val: Auth_assets_Class, idx: number) {
    //     return val.Id;
    //   },
    // },
    //    {
    //      title: translate.t('创建账号'),
    //      key: 'create_account',
    //      width: '100px',
    //      ellipsis: {
    //        tooltip: true,
    //      },
    //      sorter: 'default',
    //      render(val: Auth_assets_Class, idx: number) {
    //        return val.create_account;
    //      },
    //    },
    {
      title: translate.t('创建人姓名'),
      key: 'create_username',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.create_username;
      },
    },
    {
      title: translate.t('创建时间'),
      key: 'create_time',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return moment(val.create_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
      },
    },
    {
      title: translate.t('备注'),
      key: 'remark',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.remark;
      },
    },
    {
      title: translate.t('分类(g,p)'),
      key: 'section',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Section;
      },
    },
    {
      title: translate.t('类型(g,g2,g3,p,p2,p3)'),
      key: 'type',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Type;
      },
    },
    {
      title: translate.t('账号或角色编码'),
      key: 'value1',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value1;
      },
    },
    {
      title: translate.t('所拥有的角色编码或租户'),
      key: 'value2',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value2;
      },
    },
    {
      title: translate.t('租户或资源类别（Menu，Controller）'),
      key: 'value3',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value3;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value4',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value4;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value5',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value5;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value6',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value6;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value7',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value7;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value8',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value8;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value9',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value9;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value10',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value10;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value11',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value11;
      },
    },
    {
      title: translate.t('特征值'),
      key: 'value12',
      width: '100px',
      ellipsis: {
        tooltip: true,
      },
      sorter: 'default',
      render(val: Auth_assets_Class, idx: number) {
        return val.Value12;
      },
    },
    {
      key: '__actions',
      title: translate.t('操作'),
      width: 160,
      render(row: Auth_assets_Class) {
        const opts: VNode[] = [];
        opts.push(make_text_NButton(translate.t('编辑'), () => editRow(row)));
        opts.push(
          make_text_NButton(translate.t('删除'), () => confirmDel(translate, () => delRow(row))),
        );
        //opts.push(make_text_NButton(translate.t('选中'), () => pickRow(row)));
        return make_h_NSpace(opts, 'start', false);
      },
    },
  ];
}

//高级查询
function queryList() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  initData();
}
//重置查询
function resetQuery() {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = 15;
  queryInfo.value.create_account = '';
  initData();
}

//新任务
function newTask() {
  auth_assets_FormRef.value?.open('add', {} as Auth_assets_Class, []);
}

//编辑
function editRow(row: Auth_assets_Class) {
  GetOne(row.Id.toString(), itemName).then((res) => {
    auth_assets_FormRef.value?.open('edit', res, []);
  });
}

//删除
function delRow(row: Auth_assets_Class) {
  Delete([row.Id.toString()], itemName).then((res) => {
    executeRes(res, translate, () => {
      initData();
    });
  });
}
//翻页
function pageChange(page: number) {
  queryInfo.value.page = page;
  initData();
}
//改变页码
function pageSizeChange(pageSize: number) {
  queryInfo.value.page = 1;
  queryInfo.value.pageSize = pageSize;
  initData();
}

////选中行
//function pickRow(row: Auth_assets_Class) {
//    console.log(row.id);
//}
</script>

<template>
  <Layout_UMD>
    <template #header>
      <NSpace justify="space-between">
        <!-- 高级查询 -->
        <NSpace>
          <!-- <NFormItem :label="translate.t('创建账号')" label-placement="left">
            <NInput v-model:value="queryInfo.create_account" />
          </NFormItem> -->
          <NButton type="primary" @click="queryList">{{ translate.t('查询') }}</NButton>
          <NButton @click="resetQuery">{{ translate.t('重置') }}</NButton>
        </NSpace>
        <NSpace>
          <NButton type="primary" @click="newTask">
            {{ translate.t('添加') }}
          </NButton>
        </NSpace>
      </NSpace>
    </template>
    <template #list>
      <NDataTable
        ref="table"
        bordered
        striped
        :loading="tableLoading"
        :columns="columns"
        :data="tableData"
        :style="{ height: `100%` }"
        flex-height
      ></NDataTable>
    </template>
    <template #footer>
      <NSpace>
        <NPagination
          v-model:page="queryInfo.page"
          v-model:page-size="queryInfo.pageSize"
          :item-count="totalCount"
          show-size-picker
          :page-sizes="[15, 30, 45]"
          :on-update:page="pageChange"
          :on-update:page-size="pageSizeChange"
          :prefix="
            ({ itemCount }: { itemCount: number | undefined }) => {
              return translate.t('共') + ' ' + (itemCount || 0) + ' ' + translate.t('条');
            }
          "
        />
      </NSpace>
    </template>
  </Layout_UMD>
  <auth_assets_Form ref="auth_assets_FormRef" @sheetDone="initData()"></auth_assets_Form>
</template>
<style scoped></style>
