<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20221202
import { NResult, NImage } from 'naive-ui';
import img500 from '../../assets/images/500.png';
import { translate } from '@utility/i18n.ts';
</script>
<template>
  <NResult :title="translate.t('内部错误')">
    <template #icon>
      <n-image width="1162" :src="img500" />
    </template>
  </NResult>
</template>
<style scoped></style>
