// This file is generated by TABLE2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using T2ACore;

namespace PTools_PSilo.Controllers;
/// <summary>
/// Dict_silo控制器
/// </summary>
[ApiController]
[Route("/PTools_PSilo/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Gen")]
public class Dict_siloGenController : ControllerBase
{
    private readonly IDict_silo_Business Dict_siloBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public Dict_siloGenController(IDict_silo_Business inDI)
    {
        Dict_siloBusiness = inDI;
    }

    /// <summary>
    /// 获取所有实体
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<Dict_silo_Class>> GetAll()
    {
        var res = Dict_siloBusiness.GetAll();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<Dict_silo_Class> Get([FromRoute] Guid inId)
    {
        var res = Dict_siloBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取实体
    /// </summary>
    /// <param name="arr"></param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Dict_silo_Class>> Get([FromBody] Guid[] arr)
    {
        var res = Dict_siloBusiness.GetByIds(arr);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取所有实体分页数据
    /// </summary>
    /// <param name="pageNum">第几页</param>
    /// <param name="pageSize">单页数量</param>
    /// <returns></returns>
    [HttpGet("{pageNum}/{pageSize}")]
    public TPResponse<PagedResponse<Dict_silo_Class>> GetAllPaged([FromRoute] int pageNum, [FromRoute] int pageSize)
    {
        var (tatal, datas) = Dict_siloBusiness.GetAllPaged(pageNum, pageSize);
        var res = PagedResponse.New(tatal, datas);
        return TPResponse.New(res);
    }
    /// <summary>
    /// 根据Silo_type查询
    /// </summary>
    /// <param name="inSearch_Silo_type">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Silo_type}")]
    public TPResponse<List<Dict_silo_Class>> Search_Silo_type([FromRoute] string inSearch_Silo_type)
    {
        var res = Dict_siloBusiness.SearchBy_Silo_type(inSearch_Silo_type);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Silo_diameter查询
    /// </summary>
    /// <param name="inSearch_Silo_diameter">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Silo_diameter}")]
    public TPResponse<List<Dict_silo_Class>> Search_Silo_diameter([FromRoute] string inSearch_Silo_diameter)
    {
        var res = Dict_siloBusiness.SearchBy_Silo_diameter(inSearch_Silo_diameter);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Silo_name查询
    /// </summary>
    /// <param name="inSearch_Silo_name">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Silo_name}")]
    public TPResponse<List<Dict_silo_Class>> Search_Silo_name([FromRoute] string inSearch_Silo_name)
    {
        var res = Dict_siloBusiness.SearchBy_Silo_name(inSearch_Silo_name);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Using_type查询
    /// </summary>
    /// <param name="inSearch_Using_type">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Using_type}")]
    public TPResponse<List<Dict_silo_Class>> Search_Using_type([FromRoute] string inSearch_Using_type)
    {
        var res = Dict_siloBusiness.SearchBy_Using_type(inSearch_Using_type);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Create_account}")]
    public TPResponse<List<Dict_silo_Class>> Search_Create_account([FromRoute] string inSearch_Create_account)
    {
        var res = Dict_siloBusiness.SearchBy_Create_account(inSearch_Create_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Update_account}")]
    public TPResponse<List<Dict_silo_Class>> Search_Update_account([FromRoute] string inSearch_Update_account)
    {
        var res = Dict_siloBusiness.SearchBy_Update_account(inSearch_Update_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Dict_silo_Class>> MultiSearch([FromBody] Dict_silo_Search inSearchModel)
    {
        var res = Dict_siloBusiness.MultiSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Dict_silo_Class>> BlurSearch([FromBody]Dict_silo_Search inSearchModel)
    {
        var res = Dict_siloBusiness.BlurSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Dict_silo_Class>> MultiPagedSearch(
        [FromBody] Dict_silo_paged_Search inSearchModel)
    {
        var (total, datas) = Dict_siloBusiness.MultiPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Dict_silo_Class>> BlurPagedSearch(
        [FromBody]Dict_silo_paged_Search inSearchModel)
    {
        var (total, datas) = Dict_siloBusiness.BlurPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 以dict_silo生成选项
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<SelectOption<Guid>>> GetOptions()
    {
        var datas = Dict_siloBusiness.GetAll().DistinctBy(x => x.Id);
        var res = new List<SelectOption<Guid>>();
        foreach (var data in datas)
        {
            var option = SelectOption<Guid>.New(data.Silo_name, data.Id);
            res.Add(option);
        }
        return TPResponse.New(res);
    }
    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    public TPResponse<Res_2Para> Add([FromBody] Dict_silo_Class inEntity)
    {
        //添加一些判断，如：if (inEntity.Id == Guid.Empty) inEntity.Id = FunCommon.MakeSortedGuid();
        if (inEntity.Id == Guid.Empty)
        {
            inEntity.Id = FunCommon.MakeSortedGuid();
        }
        var res = Dict_siloBusiness.Add(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 添加一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<Res_2Para> AddBatch([FromBody] List<Dict_silo_Class> inSet)
    {
        //添加一些判断，如：
        foreach (var item in inSet)
        {
            if (item.Id == Guid.Empty) item.Id = Guid.NewGuid();
        }
        var res = Dict_siloBusiness.Add(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    public TPResponse<Res_2Para> Update([FromBody] Dict_silo_Class inEntity)
    {
        //添加一些判断，修改操作主键很重要
        var res = Dict_siloBusiness.Update(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 修改一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPut]
    public TPResponse<Res_2Para> UpdateBatch([FromBody] List<Dict_silo_Class> inSet)
    {
        //添加一些判断，修改操作主键很重要
        var res = Dict_siloBusiness.Update(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<Res_2Para> Delete([FromBody] Guid[] arr)
    {
        var res = Dict_siloBusiness.DeleteByIds(arr);
        var msg = res == arr.Length ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == arr.Length, msg));
    }

}
