// This file is generated by TABLE2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using T2ACore;

namespace PTools_PSilo.Controllers;
/// <summary>
/// Task_base控制器
/// </summary>
[ApiController]
[Route("/PTools_PSilo/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Gen")]
public class Task_baseGenController : ControllerBase
{
    private readonly ITask_base_Business Task_baseBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public Task_baseGenController(ITask_base_Business inDI)
    {
        Task_baseBusiness = inDI;
    }

    /// <summary>
    /// 获取所有实体
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<Task_base_Class>> GetAll()
    {
        var res = Task_baseBusiness.GetAll();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<Task_base_Class> Get([FromRoute] Guid inId)
    {
        var res = Task_baseBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取实体
    /// </summary>
    /// <param name="arr"></param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_base_Class>> Get([FromBody] Guid[] arr)
    {
        var res = Task_baseBusiness.GetByIds(arr);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取所有实体分页数据
    /// </summary>
    /// <param name="pageNum">第几页</param>
    /// <param name="pageSize">单页数量</param>
    /// <returns></returns>
    [HttpGet("{pageNum}/{pageSize}")]
    public TPResponse<PagedResponse<Task_base_Class>> GetAllPaged([FromRoute] int pageNum, [FromRoute] int pageSize)
    {
        var (tatal, datas) = Task_baseBusiness.GetAllPaged(pageNum, pageSize);
        var res = PagedResponse.New(tatal, datas);
        return TPResponse.New(res);
    }
    /// <summary>
    /// 根据Task_title查询
    /// </summary>
    /// <param name="inSearch_Task_title">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Task_title}")]
    public TPResponse<List<Task_base_Class>> Search_Task_title([FromRoute] string inSearch_Task_title)
    {
        var res = Task_baseBusiness.SearchBy_Task_title(inSearch_Task_title);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Create_account}")]
    public TPResponse<List<Task_base_Class>> Search_Create_account([FromRoute] string inSearch_Create_account)
    {
        var res = Task_baseBusiness.SearchBy_Create_account(inSearch_Create_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Update_account}")]
    public TPResponse<List<Task_base_Class>> Search_Update_account([FromRoute] string inSearch_Update_account)
    {
        var res = Task_baseBusiness.SearchBy_Update_account(inSearch_Update_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_base_Class>> MultiSearch([FromBody] Task_base_Search inSearchModel)
    {
        var res = Task_baseBusiness.MultiSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_base_Class>> BlurSearch([FromBody]Task_base_Search inSearchModel)
    {
        var res = Task_baseBusiness.BlurSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Task_base_Class>> MultiPagedSearch(
        [FromBody] Task_base_paged_Search inSearchModel)
    {
        var (total, datas) = Task_baseBusiness.MultiPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Task_base_Class>> BlurPagedSearch(
        [FromBody]Task_base_paged_Search inSearchModel)
    {
        var (total, datas) = Task_baseBusiness.BlurPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 以task_base生成选项
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<SelectOption<Guid>>> GetOptions()
    {
        var datas = Task_baseBusiness.GetAll().DistinctBy(x => x.Id);
        var res = new List<SelectOption<Guid>>();
        foreach (var data in datas)
        {
            var option = SelectOption<Guid>.New(data.Task_title, data.Id);
            res.Add(option);
        }
        return TPResponse.New(res);
    }
    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    public TPResponse<Res_2Para> Add([FromBody] Task_base_Class inEntity)
    {
        //添加一些判断，如：if (inEntity.Id == Guid.Empty) inEntity.Id = FunCommon.MakeSortedGuid();
        if (inEntity.Id == Guid.Empty)
        {
            inEntity.Id = FunCommon.MakeSortedGuid();
        }
        var res = Task_baseBusiness.Add(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 添加一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<Res_2Para> AddBatch([FromBody] List<Task_base_Class> inSet)
    {
        //添加一些判断，如：
        foreach (var item in inSet)
        {
            if (item.Id == Guid.Empty) item.Id = Guid.NewGuid();
        }
        var res = Task_baseBusiness.Add(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    public TPResponse<Res_2Para> Update([FromBody] Task_base_Class inEntity)
    {
        //添加一些判断，修改操作主键很重要
        var res = Task_baseBusiness.Update(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 修改一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPut]
    public TPResponse<Res_2Para> UpdateBatch([FromBody] List<Task_base_Class> inSet)
    {
        //添加一些判断，修改操作主键很重要
        var res = Task_baseBusiness.Update(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<Res_2Para> Delete([FromBody] Guid[] arr)
    {
        var res = Task_baseBusiness.DeleteByIds(arr);
        var msg = res == arr.Length ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == arr.Length, msg));
    }

}
