// This file is generated by TABLE2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using T2ACore;

namespace PTools_PSilo.Controllers;
/// <summary>
/// Task_result控制器
/// </summary>
[ApiController]
[Route("/PTools_PSilo/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Gen")]
public class Task_resultGenController : ControllerBase
{
    private readonly ITask_result_Business Task_resultBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public Task_resultGenController(ITask_result_Business inDI)
    {
        Task_resultBusiness = inDI;
    }

    /// <summary>
    /// 获取所有实体
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<Task_result_Class>> GetAll()
    {
        var res = Task_resultBusiness.GetAll();
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<Task_result_Class> Get([FromRoute] Guid inId)
    {
        var res = Task_resultBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据主键获取实体
    /// </summary>
    /// <param name="arr"></param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_result_Class>> Get([FromBody] Guid[] arr)
    {
        var res = Task_resultBusiness.GetByIds(arr);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 获取所有实体分页数据
    /// </summary>
    /// <param name="pageNum">第几页</param>
    /// <param name="pageSize">单页数量</param>
    /// <returns></returns>
    [HttpGet("{pageNum}/{pageSize}")]
    public TPResponse<PagedResponse<Task_result_Class>> GetAllPaged([FromRoute] int pageNum, [FromRoute] int pageSize)
    {
        var (tatal, datas) = Task_resultBusiness.GetAllPaged(pageNum, pageSize);
        var res = PagedResponse.New(tatal, datas);
        return TPResponse.New(res);
    }
    /// <summary>
    /// 根据Task_base_id查询
    /// </summary>
    /// <param name="inSearch_Task_base_id">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Task_base_id}")]
    public TPResponse<List<Task_result_Class>> Search_Task_base_id([FromRoute] Guid inSearch_Task_base_id)
    {
        var res = Task_resultBusiness.SearchBy_Task_base_id(inSearch_Task_base_id);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Layout_title查询
    /// </summary>
    /// <param name="inSearch_Layout_title">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Layout_title}")]
    public TPResponse<List<Task_result_Class>> Search_Layout_title([FromRoute] string inSearch_Layout_title)
    {
        var res = Task_resultBusiness.SearchBy_Layout_title(inSearch_Layout_title);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Rfa_resource_id查询
    /// </summary>
    /// <param name="inSearch_Rfa_resource_id">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Rfa_resource_id}")]
    public TPResponse<List<Task_result_Class>> Search_Rfa_resource_id([FromRoute] Guid inSearch_Rfa_resource_id)
    {
        var res = Task_resultBusiness.SearchBy_Rfa_resource_id(inSearch_Rfa_resource_id);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Create_account}")]
    public TPResponse<List<Task_result_Class>> Search_Create_account([FromRoute] string inSearch_Create_account)
    {
        var res = Task_resultBusiness.SearchBy_Create_account(inSearch_Create_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Update_account}")]
    public TPResponse<List<Task_result_Class>> Search_Update_account([FromRoute] string inSearch_Update_account)
    {
        var res = Task_resultBusiness.SearchBy_Update_account(inSearch_Update_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_result_Class>> MultiSearch([FromBody] Task_result_Search inSearchModel)
    {
        var res = Task_resultBusiness.MultiSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<List<Task_result_Class>> BlurSearch([FromBody]Task_result_Search inSearchModel)
    {
        var res = Task_resultBusiness.BlurSearch(inSearchModel);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Task_result_Class>> MultiPagedSearch(
        [FromBody] Task_result_paged_Search inSearchModel)
    {
        var (total, datas) = Task_resultBusiness.MultiPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 分页高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Task_result_Class>> BlurPagedSearch(
        [FromBody]Task_result_paged_Search inSearchModel)
    {
        var (total, datas) = Task_resultBusiness.BlurPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    public TPResponse<Res_2Para> Add([FromBody] Task_result_Class inEntity)
    {
        //添加一些判断，如：if (inEntity.Id == Guid.Empty) inEntity.Id = FunCommon.MakeSortedGuid();
        if (inEntity.Id == Guid.Empty)
        {
            inEntity.Id = FunCommon.MakeSortedGuid();
        }
        var res = Task_resultBusiness.Add(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 添加一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<Res_2Para> AddBatch([FromBody] List<Task_result_Class> inSet)
    {
        //添加一些判断，如：
        foreach (var item in inSet)
        {
            if (item.Id == Guid.Empty) item.Id = Guid.NewGuid();
        }
        var res = Task_resultBusiness.Add(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    public TPResponse<Res_2Para> Update([FromBody] Task_result_Class inEntity)
    {
        //添加一些判断，修改操作主键很重要
        var res = Task_resultBusiness.Update(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 修改一批实体
    /// </summary>
    /// <param name="inSet">一批实体</param>
    /// <returns></returns>
    [HttpPut]
    public TPResponse<Res_2Para> UpdateBatch([FromBody] List<Task_result_Class> inSet)
    {
        //添加一些判断，修改操作主键很重要
        var res = Task_resultBusiness.Update(inSet);
        var msg = res == inSet.Count ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == inSet.Count, msg));
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<Res_2Para> Delete([FromBody] Guid[] arr)
    {
        var res = Task_resultBusiness.DeleteByIds(arr);
        var msg = res == arr.Length ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == arr.Length, msg));
    }

}
