// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20221130

using System;
using SqlSugar;
using System.Collections.Generic; 

namespace T2ACore;

/// <summary>
/// Language业务类
/// </summary>
public class Language_Business : ILanguage_Business
{

    private readonly static string CacheKey = "Language_AllData";
    private readonly ICache CacheFunc;
    private readonly IDBHelper dbHelper;

    /// <summary>
    /// 构造函数
    /// </summary>
    public Language_Business(IDBHelper inDI, ICache inDI2)
    {
        dbHelper = inDI;
        CacheFunc = inDI2;
    }

    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    public bool CreateTable()
    {
        try
        {
            dbHelper.GetDB("System").CodeFirst.InitTables<Language_Class>();
            return true;
        }
        catch (Exception)
        {
            throw;
        }
    }

    /////////////////////////////////////////////////////////// 
    //  以下为生成代码
    /////////////////////////////////////////////////////////// 

    #region 查询
    /// <summary> 
    /// 获取所有实体 
    /// </summary> 
    /// <returns></returns> 
    public List<Language_Class> GetAll()
    {
        var cacheData = CacheFunc.GetFromCache<List<Language_Class>>(CacheKey);
        if (cacheData == null || cacheData.Count < 1)
        {
            var newData = dbHelper.QueryList<Language_Class>("System");
            CacheFunc.Insert(CacheKey, newData);
            return newData;
        }
        else
        {
            return cacheData;
        }
    }

    /// <summary> 
    /// 获取所有实体 
    /// </summary> 
    /// <returns></returns> 
    public List<Language_Class> GetAllWithoutCache()
    {
        return dbHelper.QueryList<Language_Class>("System"); 
    }

    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    /// <returns></returns>
    public int GetAllCount()
    {
        return dbHelper.QueryCount<Language_Class>("System", (x) => true);
    }

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    /// <param name="pageIndex"></param>
    /// <param name="pageSize"></param>
    /// <returns></returns>
    public (int TotalCount, List<Language_Class> Datas) GetAllPaged(int pageIndex, int pageSize)
    {
        return dbHelper.QueryPageList<Language_Class>("System",
            (x) => true, (x) => new
            {
                x.Key
            }, default, pageIndex, pageSize);
    }
    /// <summary> 
    /// 根据主键得到一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public List<Language_Class> GetByIds(string[] inSet)
    {
        return dbHelper.QueryByIds<Language_Class, string>("System", inSet);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public Language_Class GetOneFromAll(string id)
    {
        return GetAll().Find(p => p.Key == id);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public Language_Class GetOne(string id)
    {
        return dbHelper.QueryOne<Language_Class, string>("System", id);
    }

    /// <summary>
    /// 根据key查询
    /// </summary>
    /// <param name="inSearch_Key">查询字段</param>
    /// <returns></returns>
    public List<Language_Class> SearchBy_Key(string inSearch_Key)
    {
        return dbHelper.QueryListByClause<Language_Class>("System",
            (x) => x.Key == inSearch_Key,
            (x) => x.Key, default);
    }

    /// <summary>
    /// 根据create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    public List<Language_Class> SearchBy_Create_account(string inSearch_Create_account)
    {
        return dbHelper.QueryListByClause<Language_Class>("System",
            (x) => x.Create_account == inSearch_Create_account,
            (x) => x.Create_account, default);
    }

    /// <summary>
    /// 根据update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    public List<Language_Class> SearchBy_Update_account(string inSearch_Update_account)
    {
        return dbHelper.QueryListByClause<Language_Class>("System",
            (x) => x.Update_account == inSearch_Update_account,
            (x) => x.Update_account, default);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<Language_Class> MultiSearch(Language_Search inSearchModel)
    {
        var exp = Expressionable.Create<Language_Class>();
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Key)), x => x.Key.Contains(inSearchModel.Key));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Update_account)), x => x.Update_account.Contains(inSearchModel.Update_account));
        return dbHelper.QueryListByClause("System", exp.ToExpression(), x => x.Key);
    }
    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<Language_Class> BlurSearch(Language_Search inSearchModel)
    {
        var exp = Expressionable.Create<Language_Class>();
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Key)), x => x.Key.Contains(inSearchModel.Key));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Update_account)), x => x.Update_account.Contains(inSearchModel.Update_account));
        return dbHelper.QueryListByClause("System", exp.ToExpression(), x => x.Key);
    }
    #endregion 查询

    #region 添加
    /// <summary> 
    /// 添加一个实体 
    /// </summary> 
    /// <param name="inEntity"></param> 
    /// <returns></returns> 
    public bool Add(Language_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.AddOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 添加一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public int Add(List<Language_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.AddBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }
    #endregion 添加

    #region 修改
    /// <summary> 
    /// 修改一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param> 
    /// <returns></returns> 
    public bool Update(Language_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.UpdateOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 修改一批实体 
    /// </summary> 
    /// <param name="inSet">实体</param> 
    /// <returns></returns> 
    public int Update(List<Language_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.UpdateBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }
    #endregion 修改

    #region 删除
    /// <summary> 
    /// 删除一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param>
    /// <returns></returns> 
    public bool Delete(Language_Class inEntity)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteOne("System", inEntity);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 删除一批实体 
    /// </summary> 
    /// <param name="inSet">实体集合</param>
    /// <returns></returns> 
    public int Delete(List<Language_Class> inSet)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteBatch("System", inSet);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 根据主键删除一个实体 
    /// </summary> 
    /// <param name="inId">主键</param>
    /// <returns></returns> 
    public bool DeleteById(string inId)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteOneById<Language_Class, string>("System", inId);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    /// <summary> 
    /// 根据主键删除一批实体 
    /// </summary> 
    /// <param name="inArr">主键集合</param>
    /// <returns></returns> 
    public int DeleteByIds(string[] inArr)
    {
        CacheFunc.Remove(CacheKey);
        var res = dbHelper.DeleteBatchByIds<Language_Class, string>("System", inArr);
        CacheFunc.Remove(CacheKey);
        return res;
    }

    #endregion 删除
}
