// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;

namespace T2ACore;

/// <summary>
/// menu检索类
/// </summary>
public class Menu_Search
{
    /// <summary>
    /// 父级Id{Search}
    /// </summary>
    public Guid Parent_id { get; set; }

    /// <summary>
    /// 菜单编号{Search}
    /// </summary>
    public string Code { get; set; }

    /// <summary>
    /// 菜单名{Search}
    /// </summary>
    public string Label { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    public string Create_account { get; set; }

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    public string Update_account { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

}
