// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// tenant业务类接口
/// </summary>
public interface ITenant_Business
{

    /////////////////////////////////////////////////////////// 
    //  以下为生成代码
    /////////////////////////////////////////////////////////// 

    /// <summary>
    /// 查询所有实体
    /// </summary>
    public List<Tenant_Class> GetAll();
    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    public int GetAllCount();

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    public (int TotalCount, List<Tenant_Class> Datas) GetAllPaged(int pageIndex, int pageSize);
    /// <summary>
    /// 查询多个实体
    /// </summary>
    public List<Tenant_Class> GetByIds(Guid[] inSet);
    /// <summary>
    /// 通过检索全部实体查询一个实体
    /// </summary>
    public Tenant_Class GetOneFromAll(Guid id);
    /// <summary>
    /// 查询一个实体
    /// </summary>
    public Tenant_Class GetOne(Guid id);
    /// <summary>
    /// 根据Code查询
    /// </summary>
    public List<Tenant_Class> SearchBy_Code(string inSearch_Code);
    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    public List<Tenant_Class> SearchBy_Create_account(string inSearch_Create_account);
    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    public List<Tenant_Class> SearchBy_Update_account(string inSearch_Update_account);
    /// <summary>
    /// 高级查询
    /// </summary>
    public List<Tenant_Class> MultiSearch(Tenant_Search inSearchModel);

    /// <summary>
    /// 高级模糊查询
    /// </summary>
    public List<Tenant_Class> BlurSearch(Tenant_Search inSearchModel);


    /// <summary>
    /// 添加一个实体
    /// </summary>
    public bool Add(Tenant_Class inEntity);
    /// <summary>
    /// 添加一批实体
    /// </summary>
    public int Add(List<Tenant_Class> inSet);

    /// <summary>
    /// 修改一个实体
    /// </summary>
    public bool Update(Tenant_Class inEntity);
    /// <summary>
    /// 修改一批实体
    /// </summary>
    public int Update(List<Tenant_Class> inSet);

    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool Delete(Tenant_Class inEntity);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int Delete(List<Tenant_Class> inSet);
    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool DeleteById(Guid inId);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int DeleteByIds(Guid[] inArr);

    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    public bool CreateTable();

    /////////////////////////////////////////////////////////// 
    //  以下为新建代码
    /////////////////////////////////////////////////////////// 


}
