// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// user业务类接口
/// </summary>
public interface IUser_Business
{

    ///////////////////////////////////////////////////////////
    //  以下为生成代码
    ///////////////////////////////////////////////////////////

    /// <summary>
    /// 查询所有实体
    /// </summary>
    public List<User_Class> GetAll();
    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    public int GetAllCount();

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    public (int TotalCount, List<User_Class> Datas) GetAllPaged(int pageIndex, int pageSize);
    /// <summary>
    /// 查询多个实体
    /// </summary>
    public List<User_Class> GetByIds(int[] inSet);
    /// <summary>
    /// 通过检索全部实体查询一个实体
    /// </summary>
    public User_Class GetOneFromAll(int id);
    /// <summary>
    /// 查询一个实体
    /// </summary>
    public User_Class GetOne(int id);
    /// <summary>
    /// 根据UserId查询
    /// </summary>
    public List<User_Class> SearchBy_UserId(Guid inSearch_UserId);
    /// <summary>
    /// 根据UserId集合查询
    /// </summary>
    public List<User_Class> SearchBy_UserIds(List<Guid> inSearch_UserIds);
    /// <summary>
    /// 根据Tenant查询
    /// </summary>
    public List<User_Class> SearchBy_Tenant(string inSearch_Tenant);
    /// <summary>
    /// 根据Tenant集合查询
    /// </summary>
    public List<User_Class> SearchBy_Tenants(List<string> inSearch_Tenants);
    /// <summary>
    /// 根据Account查询
    /// </summary>
    public List<User_Class> SearchBy_Account(string inSearch_Account);
    /// <summary>
    /// 根据Account集合查询
    /// </summary>
    public List<User_Class> SearchBy_Accounts(List<string> inSearch_Accounts);
    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    public List<User_Class> SearchBy_Create_account(string inSearch_Create_account);
    /// <summary>
    /// 根据Create_account集合查询
    /// </summary>
    public List<User_Class> SearchBy_Create_accounts(List<string> inSearch_Create_accounts);
    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    public List<User_Class> SearchBy_Update_account(string inSearch_Update_account);
    /// <summary>
    /// 根据Update_account集合查询
    /// </summary>
    public List<User_Class> SearchBy_Update_accounts(List<string> inSearch_Update_accounts);
    /// <summary>
    /// 高级查询
    /// </summary>
    public List<User_Class> MultiSearch(User_Search inSearchModel);

    /// <summary>
    /// 高级模糊查询
    /// </summary>
    public List<User_Class> BlurSearch(User_Search inSearchModel);

    /// <summary>
    /// 高级分页查询
    /// </summary>
    public (int, List<User_Class>) MultiPagedSearch(Sys_user_paged_Search inSearchModel);

    /// <summary>
    /// 高级模糊分页查询
    /// </summary>
    public (int, List<User_Class>) BlurPagedSearch(Sys_user_paged_Search inSearchModel);


    /// <summary>
    /// 添加一个实体
    /// </summary>
    public bool Add(User_Class inEntity);
    /// <summary>
    /// 添加一批实体
    /// </summary>
    public int Add(List<User_Class> inSet);

    /// <summary>
    /// 修改一个实体
    /// </summary>
    public bool Update(User_Class inEntity);
    /// <summary>
    /// 修改一批实体
    /// </summary>
    public int Update(List<User_Class> inSet);

    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool Delete(User_Class inEntity);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int Delete(List<User_Class> inSet);
    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool DeleteById(int inId);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int DeleteByIds(int[] inArr);
     

    /////////////////////////////////////////////////////////// 
    //  以下为新建代码
    /////////////////////////////////////////////////////////// 

    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    public bool CreateTable();
     
    /// <summary>
    /// 如果没有数据的情况下，添加数据
    /// </summary>
    /// <param name="inEntity"></param>
    /// <returns></returns>
    int AddIfNoData(User_Class inEntity);
     
    /// <summary>
    /// 登录
    /// </summary>
    /// <param name="account"></param>
    /// <param name="inPassword"></param>
    /// <returns></returns>
    (bool Status, string Msg, string Token, User_Class User) Login(string account, string inPassword);

    /// <summary>
    /// 
    /// </summary>
    /// <param name="inAccount"></param>
    /// <param name="inPassword"></param>
    /// <param name="inPassword1"></param>
    /// <param name="inPassword2"></param>
    /// <returns></returns>
    (bool Status, string Msg) ModifyPassword(string inAccount, string inPassword, string inPassword1, string inPassword2);

    /// <summary>
    /// 
    /// </summary>
    /// <param name="newUser"></param>
    /// <returns></returns>
    (bool Status, string Msg) AddNewUser(User_Class newUser);

    /// <summary>
    /// 
    /// </summary>
    /// <param name="inAccount"></param>
    /// <param name="newPass"></param>
    /// <returns></returns>
    (bool Status, string Msg) RestorePassword(string inAccount, string newPass);

    /// <summary>
    /// 
    /// </summary>
    /// <param name="user"></param>
    /// <returns></returns>
    (bool, string) UpdateUser(User_Class user);
}
