// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using Microsoft.AspNetCore.Http;

namespace T2ACore;

/// <summary>
/// 处理当次访问请求的工具
/// </summary>
public class ScopeUser
{
    private static IHttpContextAccessor _accessor;

    /// <summary>
    /// 配置HttpContext
    /// </summary>
    /// <param name="accessor"></param>
    public static void ConfigureHttpContext(IHttpContextAccessor accessor)
    {
        _accessor = accessor;
    }

    /// <summary>
    /// 获取当前用户 账号 姓名，默认空值
    /// </summary>
    /// <returns></returns>
    public static (string Account, string UserName) GetUserAccountName()
    {
        var account = "";
        var username = "";
        var user = GetUserInfo();
        if (user != null)
        {
            account = user.Account;
            username = user.UserName;
        }
        return (account, username);
    }

    /// <summary>
    /// 得到当前Token
    /// </summary>
    /// <returns></returns>
    public static string GetToken()
    {
        string tokenStr = Config.BaseConfig.TokenString; //tp_token

        if (_accessor == null)
        {
            return "";
        }

        var context = _accessor.HttpContext;
        if (null == context)
        {
            return string.Empty;
        }
        string token = context.Request.Cookies[tokenStr];
        if (string.IsNullOrEmpty(token))
        {
            token = context.Request.Headers[tokenStr];
        }
        return token;
    }

    /// <summary>
    /// 得到当前UserInfo
    /// </summary>
    /// <returns></returns>
    public static UserInfo GetUserInfo()
    {
        var token = GetToken();
        if (string.IsNullOrEmpty(token))
        {
            return null;
        }

        var res = UserInfo.GetFromToken(token);

        return res;
    }

    /// <summary>
    /// 获取用户租户信息
    /// </summary>
    /// <returns></returns>
    public static string GetUserTenant()
    {
        if (_accessor == null)
        {
            return "Default";
        }

        var context = _accessor.HttpContext;
        if (null == context)
        {
            // return string.Empty;
            return "Default";
        }

        var tenant = context.Items["tenant"]?.ToString();

        return string.IsNullOrEmpty(tenant) ? "Default" : tenant;
    }
}
