// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Text;

namespace T2ACore;

/// <summary>
/// 处理当次访问请求的工具
/// </summary>
public class ScopeTool
{
    private static IHttpContextAccessor _accessor;

    /// <summary>
    /// 配置HttpContext
    /// </summary>
    /// <param name="accessor"></param>
    public static void ConfigureHttpContext(IHttpContextAccessor accessor)
    {
        _accessor = accessor;
    }

    /// <summary>
    /// Http中Body内容
    /// </summary>
    public static string BodyContent { get; set; }

    /// <summary>
    /// 跟踪信息
    /// </summary>
    public static List<string> TraceList { get; set; } = new List<string>();

    /// <summary>
    /// 得到当前请求的URL
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    public static string GetURL(HttpRequest request = null)
    {
        if (null == request)
        {
            var context = _accessor.HttpContext;
            request = null != context ? context.Request : null;
        }
        if (null == request)
        {
            return string.Empty;
        }
        return new StringBuilder()
            .Append(request.PathBase)
            .Append(request.Path)
            .Append(request.QueryString)
            .ToString();
    }

    /// <summary>
    /// 得到当前请求的Domain
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    public static string GetDomain(HttpRequest request = null)
    {
        if (null == request)
        {
            var context = _accessor.HttpContext;
            request = null != context ? context.Request : null;
        }
        if (null == request)
        {
            return string.Empty;
        }
        return request.Host.Host.ToString();
    }
    /// <summary>
    /// 得到当前请求的绝对URL
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    public static string GetAbsoluteURL(HttpRequest request = null)
    {
        if (null == request)
        {
            var context = _accessor.HttpContext;
            request = null != context ? context.Request : null;
        }
        if (null == request)
        {
            return string.Empty;
        }
        return new StringBuilder()
            .Append(request.Scheme)
            .Append("://")
            .Append(request.Host)
            .Append(request.PathBase)
            .Append(request.Path)
            .Append(request.QueryString)
            .ToString();
    }

    /// <summary>
    /// 得到当前请求主机
    /// </summary>
    /// <param name="request"></param>
    /// <returns></returns>
    public static string GetHttpHost(HttpRequest request = null)
    {
        if (null == request)
        {
            var context = _accessor.HttpContext;
            request = null != context ? context.Request : null;
        }
        if (null == request)
        {
            return string.Empty;
        }
        return new StringBuilder()
            .Append(request.Scheme)
            .Append("://")
            .Append(request.Host)
            .Append(request.PathBase)
            .ToString();
    }

    /// <summary>
    /// 得到访问IP
    /// </summary>
    public static string GetIPv4()
    {
        var context = _accessor.HttpContext;
        if (null == context)
        {
            return string.Empty;
        }
        return context.Connection.RemoteIpAddress.MapToIPv4().ToString();
    }

    /// <summary>
    /// 得到访问Agent
    /// </summary>
    /// <returns></returns>
    public static string GetBrowseAgent()
    {
        var context = _accessor.HttpContext;
        if (null == context)
        {
            return string.Empty;
        }
        return context.Request.Headers["User-Agent"];
    }

    /// <summary>
    /// 得到上一个请求的URL地址
    /// </summary>
    /// <returns></returns>
    public static string GetReferer()
    {
        var context = _accessor.HttpContext;
        if (null == context)
        {
            return string.Empty;
        }
        return context.Request.Headers["Referer"];
    }

    /// <summary>
    /// 获取当前站点部署的URL
    /// </summary>
    /// <returns></returns>
    public static string GetSiteHost()
    {
        string protocol = _accessor.HttpContext.Request.IsHttps
                          ? "https"
                          : "http";

        return null == _accessor
               ? string.Empty
               : protocol + "://" + _accessor.HttpContext.Request.Host.Value + "/";
    }
}
