<script>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220101
import { useMessage } from 'naive-ui';
import { defineComponent } from 'vue';

export default defineComponent({
    setup() {
        window.$message = useMessage();
    },
});
</script>
<template></template>
