<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20230131
//注意：不建议多个布局形式进行嵌套
//只有一个，用于内容布局
//    ————————————————————————
//    |                      |
//    |                      |
//    |           1          |
//    |                      |
//    |______________________|
</script>
<template>
  <div class="Indi5-layout">
    <div class="Indi5-single">
      <slot name="single">1</slot>
    </div>
  </div>
</template>
<style scoped>
.Indi5-layout {
  display: grid;
  grid-template-columns: 100%;
  grid-template-rows: 100%;
  width: 100%;
  height: 100%;
}

.Indi5-single {
  place-content: space-around space-evenly;
  grid-column: 1 / 2;
  grid-row: 1 / 2;
  background-color: var(--tp-contentCard);
  padding: 20px;
}
</style>
