<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20230131
//注意：不建议多个布局形式进行嵌套
//上下分两段，用于内容布局
//    —————————————————————————————
//    |            1              |
//    |———————————————————————————|
//    |                           |
//    |            2              |
//    |___________________________|
//    |            3              |
//    |___________________________|

const inPara = defineProps({
  HeaderHeight: String, //1部分高度
  ColumnGap: String, //列间距
  RowGap: String, //行间距
});
</script>
<template>
  <div class="umd-layout">
    <div class="umd-header">
      <slot name="header">1</slot>
    </div>
    <div class="umd-main">
      <slot name="list">2</slot>
    </div>
    <div class="umd-footer">
      <slot name="footer">3</slot>
    </div>
  </div>
</template>
<style scoped>
.umd-layout {
  display: grid;
  grid-template-columns: 100%;
  grid-template-rows: v-bind('inPara.HeaderHeight?? "74px"') auto 74px;
  width: 100%;
  height: 100%;
  row-gap: v-bind('inPara.RowGap');
  column-gap: v-bind('inPara.ColumnGap');
}

.umd-header {
  place-content: space-around space-evenly;
  grid-column: 1 / 2;
  grid-row: 1 / 2;
  background-color: var(--tp-contentCard);
  padding: 20px;
}

.umd-main {
  place-content: space-around space-evenly;
  grid-column: 1 / 2;
  grid-row: 2 / 3;
  overflow: auto;
  background-color: var(--tp-contentCard);
  padding-left: 20px;
  padding-right: 20px;
}

.umd-footer {
  place-content: space-around space-evenly;
  grid-column: 1 / 2;
  grid-row: 3 / 4;
  background-color: var(--tp-contentCard);
  padding: 20px;
}
</style>
