namespace PTools_PSilo;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using NLog.Web;
using T2ACore;
using NLog;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.AspNetCore.StaticFiles;
using Exceptionless;

/// <summary>
/// 程序入口
/// </summary>
public class Program
{
    /// <summary>
    /// 程序入口
    /// </summary>
    /// <param name="args"></param>
    public static void Main(string[] args)
    {
        Common.ServerStartTime = DateTime.Now;
        var mainLogger = LogManager.Setup()
            .LoadConfigurationFromAppSettings()
            .GetCurrentClassLogger();
        try
        {
            mainLogger.Info("Program init...");

            string corsStr = "*";

            // var builder = WebApplication.CreateSlimBuilder(args); //.net8写法
            var builder = WebApplication.CreateBuilder(args);

            InitServices(builder, corsStr);

            var app = builder.Build();

            InitPipeLine(builder, app, corsStr);

            app.Run();
        }
        catch (Exception ex)
        {
            mainLogger.Fatal(ex, "Main Process exit...");
        }
        finally
        {
            NLog.LogManager.Shutdown();
        }
    }


    /// <summary>
    /// 初始化服务
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="corsStr"></param>
    private static void InitServices(WebApplicationBuilder builder, string corsStr)
    {
        //设置上传文件请求的大小限制，如果需要的话
        //builder.Services.Configure<KestrelServerOptions>(options =>
        //{
        //    options.Limits.MaxRequestBodySize = 1024 * 1024 * 1000;// 1G
        //    options.Limits.MaxRequestBufferSize = 1024 * 1024 * 1000;
        //});

        //builder.Services.Configure<FormOptions>(options =>
        //{
        //    options.MultipartBodyLengthLimit = 1024 * 1024 * 1000;
        //});

        //初始化配置
        builder.InitAppSettings();

        //初始化设置
        StarterConfig.InitFunCommonData();

        //服务注册
        builder.Services.AddHttpContextAccessor();
        var mvc = builder.Services.AddControllersWithViews();
        builder.Services.AddSession();
        builder.Services.AddHealthChecks();
        builder.Services.AddEndpointsApiExplorer();

        //Swagger
        builder.AddSwaggerService();

        //Fluent Validation
        builder.AddValidationService(mvc);

        //cors
        builder.AddCorsService(corsStr);

        //SignalR注册服务
        builder.Services.AddSignalR();

        // NLog注册
        builder.AddLogging();

        //框架依赖注入
        builder.ServiceAdd();

        //业务依赖注入
        builder.BusinessServiceStart();
    }

    /// <summary>
    /// 初始化管道
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="app"></param>
    /// <param name="corsStr"></param>
    private static void InitPipeLine(WebApplicationBuilder builder, WebApplication app, string corsStr)
    {
        // 使用 http 日志
        // app.UseHttpLogging();

        //自动刷新appsettings cyl
        app.ReloadAppSettings(builder);

        app.UseExceptionless();

        //服务管道
        //注意管道顺序，本模板为官网顺序，可按需求自行调整

        //WWWROOT路径
        Common.CurrentWWWPath = app.Environment.WebRootPath;

        //全局异常处理
        app.UseExceptionService();
        var logService = app.Services.GetRequiredService<ILoggerFactory>();
        T2ACore.Logger.Initialize(logService);
        //app.UseDeveloperExceptionPage();

        app.UseSwaggerService();

        //全局Http日志,放在异常处理之后，保证触发异常则不再trace
        app.UseMiddleware<HttpTraceMiddleware>();

        app.UseHttpsRedirection();
        //app.UseCookiePolicy();

        //鉴权中间件
        app.UseMiddleware<TPWebMiddleware>();
        //app.UseMiddleware<TPWeb_IndiMiddleware>();

        app.UseRouting();
        //app.UseRequestLocalization();

        //处理跨域
        app.UseCors(corsStr);

        ScopeTool.ConfigureHttpContext(app.Services
            .GetRequiredService<IHttpContextAccessor>());

        ScopeUser.ConfigureHttpContext(app.Services
            .GetRequiredService<IHttpContextAccessor>());

        app.UseAuthentication();
        //app.UseAuthorization();
        //app.UseSession();
        //app.UseResponseCompression();
        //app.UseResponseCaching();

        app.MapControllers();

        //var provider = new FileExtensionContentTypeProvider();
        //provider.Mappings[".dds"] = "application/octet-stream";

        //app.UseStaticFiles(new StaticFileOptions
        //{
        //    ContentTypeProvider = provider
        //});

        app.UseStaticFiles();

        //SignalR
        app.MapHub<MessageHub>("/" + ConstPara.NAMESPACE + "/MessageHub");
        //健康检查
        app.MapHealthChecks("/" + ConstPara.NAMESPACE + "/health");

    }
}

