// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace T2ACore;

/// <summary>
/// Token中的人员信息
/// </summary>
public class UserInfo
{
    /// <summary>
    /// 获取User
    /// </summary>
    /// <returns></returns>
    public User_Class GetUserFromToken()
    {
        if (this == null)
        {
            return null;
        }

        var user = new User_Class();
        user.Id = default;
        user.UserId = this.UserId;
        user.UserName = this.UserName;
        user.Account = this.Account;
        return user;
    }


    /// <summary>
    /// 验证人是否过期
    /// </summary>
    /// <returns></returns>
    public bool IsExp()
    {
        return exp < DateTime.Now;
    }
    /// <summary>
    /// 验证token是否过期
    /// </summary>
    /// <param name="token"></param>
    /// <returns></returns>
    public static bool IsExp(string token)
    {
        var user = GetFromToken(token);
        return user.exp < DateTime.Now;
    }
    /// <summary>
    /// 创建人员信息类
    /// </summary>
    /// <param name="token"></param>
    public static UserInfo GetFromToken(string token)
    {
        if (string.IsNullOrEmpty(token))
        {
            return null;
        }

        try
        {
            string payload = token.Split('.')[1];
            payload = payload.Replace('_', '/').Replace('-', '+');
            switch (payload.Length % 4)
            {
                case 2: payload += "=="; break;
                case 3: payload += "="; break;
            }
            var decode = Convert.FromBase64String(payload);
            var info = System.Text.Encoding.UTF8.GetString(decode);
            var jo = (JObject)JsonConvert.DeserializeObject(info);

            var res = new UserInfo();
            res.UserId = Guid.TryParse(jo["id"].ToString(), out Guid resId)
                         ? resId : Guid.Empty;
            res.UserName = jo["name"].ToString();
            res.Account = jo["client_id"].ToString();
            //res.Mobile = jo["phone_number"] == null ? "" : jo["phone_number"].ToString();
            //res.Email = jo["email"] == null ? "" : jo["email"].ToString();
            //res.EWeChatId = jo["EWeChatId"] == null ? "" : jo["EWeChatId"].ToString(); 
            //res.Gender = jo["gender"] == null ? "" : jo["gender"].ToString();   
            res.Tenant = jo["Tenant"] == null ? "" : jo["Tenant"].ToString();
            res.aud = jo["aud"].ToString();
            res.iat = Common.StartTime.AddSeconds(double.Parse(jo["iat"].ToString()));
            res.exp = Common.StartTime.AddSeconds(double.Parse(jo["exp"].ToString()));
            res.nbf = Common.StartTime.AddSeconds(double.Parse(jo["nbf"].ToString()));
            return res;
        }
        catch (Exception ex)
        {
            string error = ex.ToString();
            return null;
        }

    }

    /// <summary>
    /// 账号 client_id
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 姓名 name
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 用户Id id
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// 手机号 phone_number
    /// </summary>
    public string Mobile { get; set; }

    /// <summary>
    /// 邮箱 email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 性别 gender
    /// </summary>
    public string Gender { get; set; }

    /// <summary>
    /// 企业微信Id EWeChatId
    /// </summary>
    public string EWeChatId { get; set; }

    /// <summary>
    /// 租户
    /// </summary>
    public string Tenant { get; set; }

    /// <summary>
    /// 用户
    /// </summary>
    public string aud { get; set; }

    /// <summary>
    /// 到期时间
    /// </summary>
    public DateTime exp { get; set; }

    /// <summary>
    /// 发布时间
    /// </summary>
    public DateTime iat { get; set; }

    /// <summary>
    /// 在此之前不可用
    /// </summary>
    public DateTime nbf { get; set; }

}
