/*
 * This file is generated by SwaggerCenter.
 * If you met a bug, please tell me, thanks!
 * wrx 20220101
 * In addition, it is recommended to delete unnecessary methods
 * before publishing to avoid exposing all interfaces
 */

export default function GetMenu() {
    return [
        {
            label: '一级菜单1',
            key: 'L1_1',
            icon: () => {
                return '';
            },
            menuPath: 'L1_1',
            menuPathLabel: '一级菜单1',
        },
        {
            label: '一级菜单2',
            key: 'L1_2',
            icon: () => {
                return '';
            },
            menuPath: 'L1_2',
            menuPathLabel: '一级菜单2',
            children: [
                {
                    label: '二级菜单1',
                    key: 'L2_1',
                    icon: () => {
                        return '';
                    },
                    menuPath: 'L1_2/L2_1',
                    menuPathLabel: '一级菜单2/二级菜单1',
                },
                {
                    label: '二级菜单2',
                    key: 'L2_2',
                    icon: () => {
                        return '';
                    },
                    menuPath: 'L1_2/L2_2',
                    menuPathLabel: '一级菜单2/二级菜单2',
                    children: [
                        {
                            label: '三级菜单1',
                            key: 'L3_1',
                            icon: () => {
                                return '';
                            },
                            menuPath: 'L1_2/L2_2/L3_1',
                            menuPathLabel: '一级菜单2/二级菜单2/三级菜单1',
                        },
                    ],
                },
                {
                    label: '二级菜单3',
                    key: 'L2_3',
                    icon: () => {
                        return '';
                    },
                    menuPath: 'L1_2/L2_3',
                    menuPathLabel: '一级菜单2/二级菜单3',
                },
            ],
        },
        {
            label: '一级菜单3',
            key: 'L1_3',
            icon: () => {
                return '';
            },
            menuPath: 'L1_3',
            menuPathLabel: '一级菜单3',
        },
    ];
}
