// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using MemoryPack;
using SqlSugar;
using T2ACore;
using System.Collections.Generic;

namespace PTools_PSilo;

/// <summary>
/// rfa_resource实体
/// </summary>
[MemoryPackable]
[SugarTable("rfa_resource")]
public partial class Rfa_resource_Class
{
    /// <summary>
    /// 主键Id{MenuBase:族资源}{Option:file_name,id}
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        ColumnName = "id",
        ColumnDataType = "char",
        ColumnDescription = "主键Id{MenuBase:族资源}{Option:file_name,id}",
        IsNullable = false,
        Length = 36
    )]
    public Guid Id { get; set; }

    /// <summary>
    /// 库型Id{Search}{Frontend:SelectFrom(dict_silo)}
    /// </summary>
    [SugarColumn(
        ColumnName = "dict_silo_id",
        ColumnDataType = "char",
        ColumnDescription = "库型Id{Search}{Frontend:SelectFrom(dict_silo)}",
        IsNullable = false,
        Length = 36
    )]
    public Guid Dict_silo_id { get; set; }

    /// <summary>
    /// 族类型名{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "symbol_name",
        ColumnDataType = "varchar",
        ColumnDescription = "族类型名{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Symbol_name { get; set; }

    /// <summary>
    /// 族文件地址{Search}{Frontend:FilePath}{Download}
    /// </summary>
    [SugarColumn(
        ColumnName = "rfa_path",
        ColumnDataType = "varchar",
        ColumnDescription = "族文件地址{Search}{Frontend:FilePath}{Download}",
        IsNullable = true,
        Length = 255
    )]
    public string Rfa_path { get; set; }

    /// <summary>
    /// 族文件名称{Search}{Validate:NotEmpty}
    /// </summary>
    [SugarColumn(
        ColumnName = "file_name",
        ColumnDataType = "varchar",
        ColumnDescription = "族文件名称{Search}{Validate:NotEmpty}",
        IsNullable = true,
        Length = 255
    )]
    public string File_name { get; set; }

    /// <summary>
    /// 族文件大小{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "file_size",
        ColumnDataType = "int",
        ColumnDescription = "族文件大小{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public int File_size { get; set; }

    /// <summary>
    /// 说明
    /// </summary>
    [SugarColumn(
        ColumnName = "note",
        ColumnDataType = "varchar",
        ColumnDescription = "说明",
        IsNullable = true,
        Length = 255
    )]
    public string Note { get; set; }

    /// <summary>
    /// 模板基点x{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "template_x",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "模板基点x{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Template_x { get; set; }

    /// <summary>
    /// 模板基点y{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "template_y",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "模板基点y{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Template_y { get; set; }

    /// <summary>
    /// 模板基点z{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "template_z",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "模板基点z{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Template_z { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人",
        IsNullable = true,
        Length = 50
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_account",
        ColumnDataType = "varchar",
        ColumnDescription = "更新账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Update_account { get; set; }

    /// <summary>
    /// 更新人
    /// </summary>
    [SugarColumn(
        ColumnName = "update_username",
        ColumnDataType = "varchar",
        ColumnDescription = "更新人",
        IsNullable = true,
        Length = 50
    )]
    public string Update_username { get; set; }

    /// <summary>
    /// 更新时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_time",
        ColumnDataType = "bigint",
        ColumnDescription = "更新时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Update_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        IsNullable = true,
        Length = 255
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

    /// <summary>
    /// 当前类转为MemoryPack Bin
    /// </summary>
    /// <returns></returns>
    public byte[] ToMemoryPackBin()
    {
        return MemoryPackSerializer.Serialize(this);
    }

    /// <summary>
    /// 将 RFA 资源表模型转换为筒仓布置模型
    /// </summary>
    /// <param name="inClass">源 RFA 资源表模型</param>
    /// <returns>转换后的筒仓布置模型</returns>
    public static SiloPlacement Cast(Rfa_resource_Class inClass)
    {
        var newModel = new SiloPlacement();
        newModel.Id = Guid.NewGuid();
        newModel.Rfa_resource_id = inClass.Id;
        newModel.Layout_title = inClass.Symbol_name;
        newModel.Rfa_path = inClass.Rfa_path;
        newModel.TemplatePoint = TPGeometryPro.XYZ.New(
            decimal.ToDouble(inClass.Template_x),
            decimal.ToDouble(inClass.Template_y),
            decimal.ToDouble(inClass.Template_z));
        return newModel;
    }
}
