// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using MemoryPack;
using SqlSugar;
using T2ACore;
using System.Collections.Generic;

namespace PTools_PSilo;

/// <summary>
/// task_base实体
/// </summary>
[MemoryPackable]
[SugarTable("task_base")]
public partial class Task_base_Class
{
    /// <summary>
    /// Id{MenuBase:建模任务}{Option:task_title,id}
    /// </summary>
    [SugarColumn(
        IsPrimaryKey = true,
        ColumnName = "id",
        ColumnDataType = "char",
        ColumnDescription = "Id{MenuBase:建模任务}{Option:task_title,id}",
        IsNullable = false,
        Length = 36
    )]
    public Guid Id { get; set; }

    /// <summary>
    /// 任务标题{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "task_title",
        ColumnDataType = "varchar",
        ColumnDescription = "任务标题{Search}",
        IsNullable = true,
        Length = 255
    )]
    public string Task_title { get; set; }

    /// <summary>
    /// 库型{Validate:NotEmpty}{Frontend:SelectFrom(dict_silo)}
    /// </summary>
    [SugarColumn(
        ColumnName = "silo_type",
        ColumnDataType = "varchar",
        ColumnDescription = "库型{Validate:NotEmpty}{Frontend:SelectFrom(dict_silo)}",
        IsNullable = true,
        Length = 50
    )]
    public string Silo_type { get; set; }

    /// <summary>
    /// 储库直径{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "silo_diameter",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "储库直径{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Silo_diameter { get; set; }

    /// <summary>
    /// 库底板高度{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "silo_height",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "库底板高度{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Silo_height { get; set; }

    /// <summary>
    /// 项目基点x{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "task_x",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "项目基点x{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Task_x { get; set; }

    /// <summary>
    /// 项目基点y{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "task_y",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "项目基点y{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Task_y { get; set; }

    /// <summary>
    /// 项目基点z{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "task_z",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "项目基点z{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Task_z { get; set; }

    /// <summary>
    /// 旋转角度{Frontend:Number}
    /// </summary>
    [SugarColumn(
        ColumnName = "rotation_angle",
        ColumnDataType = "decimal(20,6)",
        ColumnDescription = "旋转角度{Frontend:Number}",
        IsNullable = true,
        Length = 0
    )]
    public decimal Rotation_angle { get; set; }

    /// <summary>
    /// 状态{Frontend:Select(10:新建,11:计算中,12:计算成功,13:计算失败,20:错误)}
    /// </summary>
    [SugarColumn(
        ColumnName = "status",
        ColumnDataType = "int",
        ColumnDescription = "状态{Frontend:Select(10:新建,11:计算中,12:计算成功,13:计算失败,20:错误)}",
        IsNullable = true,
        Length = 0
    )]
    public int Status { get; set; }

    /// <summary>
    /// 错误信息
    /// </summary>
    [SugarColumn(
        ColumnName = "error_msg",
        ColumnDataType = "text",
        ColumnDescription = "错误信息",
        IsNullable = true
    )]
    public string Error_msg { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_account",
        ColumnDataType = "varchar",
        ColumnDescription = "创建账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Create_account { get; set; }

    /// <summary>
    /// 创建人
    /// </summary>
    [SugarColumn(
        ColumnName = "create_username",
        ColumnDataType = "varchar",
        ColumnDescription = "创建人",
        IsNullable = true,
        Length = 50
    )]
    public string Create_username { get; set; }

    /// <summary>
    /// 创建时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "create_time",
        ColumnDataType = "bigint",
        ColumnDescription = "创建时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Create_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_account",
        ColumnDataType = "varchar",
        ColumnDescription = "更新账号{Search}",
        IsNullable = true,
        Length = 50
    )]
    public string Update_account { get; set; }

    /// <summary>
    /// 更新人
    /// </summary>
    [SugarColumn(
        ColumnName = "update_username",
        ColumnDataType = "varchar",
        ColumnDescription = "更新人",
        IsNullable = true,
        Length = 50
    )]
    public string Update_username { get; set; }

    /// <summary>
    /// 更新时间{Default:Now}
    /// </summary>
    [SugarColumn(
        ColumnName = "update_time",
        ColumnDataType = "bigint",
        ColumnDescription = "更新时间{Default:Now}",
        IsNullable = true,
        Length = 0
    )]
    public long Update_time { get; set; } = FunCommon.GetStandardTimeStamp(); //感谢yf关于默认值的建议！20220324

    /// <summary>
    /// 备注
    /// </summary>
    [SugarColumn(
        ColumnName = "remark",
        ColumnDataType = "varchar",
        ColumnDescription = "备注",
        IsNullable = true,
        Length = 255
    )]
    public string Remark { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

    /// <summary>
    /// 当前类转为MemoryPack Bin
    /// </summary>
    /// <returns></returns>
    public byte[] ToMemoryPackBin()
    {
        return MemoryPackSerializer.Serialize(this);
    }

}
