// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;
using T2ACore;

namespace PTools_PSilo.Controllers;
/// <summary>
/// Rfa_resource控制器
/// </summary>
[ApiController]
[Route("/PTools_PSilo/[controller]/[action]")]
[ApiExplorerSettings(GroupName = "Admin")]
[TPOK]
public class Rfa_resourceController : ControllerBase
{
    private readonly IRfa_resource_Business Rfa_resourceBusiness;
    /// <summary>
    /// 构造函数
    /// </summary>
    public Rfa_resourceController(IRfa_resource_Business inDI)
    {
        Rfa_resourceBusiness = inDI;
    }

    /// <summary>
    /// 根据主键获取单个实体
    /// </summary>
    /// <param name="inId"></param>
    /// <returns></returns>
    [HttpGet("{inId}")]
    public TPResponse<Rfa_resource_Class> Get([FromRoute] Guid inId)
    {
        var res = Rfa_resourceBusiness.GetOne(inId);
        return TPResponse.New(res);
    }

    #region 单字段查询
    /// <summary>
    /// 根据Rfa_code查询
    /// </summary>
    /// <param name="inSearch_Rfa_code">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Rfa_code}")]
    public TPResponse<List<Rfa_resource_Class>> Search_Rfa_code([FromRoute] string inSearch_Rfa_code)
    {
        var res = Rfa_resourceBusiness.SearchBy_Rfa_code(inSearch_Rfa_code);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Symbol_name查询
    /// </summary>
    /// <param name="inSearch_Symbol_name">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Symbol_name}")]
    public TPResponse<List<Rfa_resource_Class>> Search_Symbol_name([FromRoute] string inSearch_Symbol_name)
    {
        var res = Rfa_resourceBusiness.SearchBy_Symbol_name(inSearch_Symbol_name);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Rfa_path查询
    /// </summary>
    /// <param name="inSearch_Rfa_path">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Rfa_path}")]
    public TPResponse<List<Rfa_resource_Class>> Search_Rfa_path([FromRoute] string inSearch_Rfa_path)
    {
        var res = Rfa_resourceBusiness.SearchBy_Rfa_path(inSearch_Rfa_path);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据File_name查询
    /// </summary>
    /// <param name="inSearch_File_name">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_File_name}")]
    public TPResponse<List<Rfa_resource_Class>> Search_File_name([FromRoute] string inSearch_File_name)
    {
        var res = Rfa_resourceBusiness.SearchBy_File_name(inSearch_File_name);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Create_account}")]
    public TPResponse<List<Rfa_resource_Class>> Search_Create_account([FromRoute] string inSearch_Create_account)
    {
        var res = Rfa_resourceBusiness.SearchBy_Create_account(inSearch_Create_account);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    [HttpGet("{inSearch_Update_account}")]
    public TPResponse<List<Rfa_resource_Class>> Search_Update_account([FromRoute] string inSearch_Update_account)
    {
        var res = Rfa_resourceBusiness.SearchBy_Update_account(inSearch_Update_account);
        return TPResponse.New(res);
    }

    #endregion
    /// <summary>
    /// 分页高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    [HttpPost]
    public TPResponse<PagedResponse<Rfa_resource_Class>> MultiPagedSearch(
        [FromBody] Rfa_resource_paged_Search inSearchModel)
    {
        var (total, datas) = Rfa_resourceBusiness.MultiPagedSearch(inSearchModel);
        var res = PagedResponse.New(total, datas);
        return TPResponse.New(res);
    }

    /// <summary>
    /// 以rfa_resource生成选项
    /// </summary>
    /// <returns></returns>
    [HttpGet]
    public TPResponse<List<SelectOption<Guid>>> GetOptions()
    {
        var datas = Rfa_resourceBusiness.GetAll().DistinctBy(x => x.Id);
        var res = new List<SelectOption<Guid>>();
        foreach (var data in datas)
        {
            var option = SelectOption<Guid>.New(data.File_name, data.Id);
            res.Add(option);
        }
        return TPResponse.New(res);
    }
    /// <summary>
    /// 添加一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPost]
    [DefaultSetAddUserInfo]
    public TPResponse<Res_2Para> Add([FromBody] Rfa_resource_Class inEntity)
    {
        //添加一些判断，如：if (inEntity.Id == Guid.Empty) inEntity.Id = FunCommon.MakeSortedGuid();
        if (inEntity.Id == Guid.Empty)
        {
            inEntity.Id = FunCommon.MakeSortedGuid();
        }
        var res = Rfa_resourceBusiness.Add(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 修改一个实体
    /// </summary>
    /// <param name="inEntity">实体</param>
    /// <returns></returns>
    [HttpPut]
    [DefaultSetUpdateUserInfo]
    public TPResponse<Res_2Para> Update([FromBody] Rfa_resource_Class inEntity)
    {
        //添加一些判断，修改操作主键很重要
        var res = Rfa_resourceBusiness.Update(inEntity);
        var msg = res ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res, msg));
    }

    /// <summary>
    /// 删除一批实体
    /// </summary>
    /// <param name="arr">Id集合</param>
    /// <returns></returns>
    [HttpDelete]
    public TPResponse<Res_2Para> Delete([FromBody] Guid[] arr)
    {
        var res = Rfa_resourceBusiness.DeleteByIds(arr);
        var msg = res == arr.Length ? "操作成功" : "操作失败";
        return TPResponse.New(Res_2Para.New(res == arr.Length, msg));
    }


    /// <summary>
    /// 以流的方式获取文件
    /// </summary>
    /// <param name="remaining"></param>
    /// <param name="fileBusiness"></param>
    /// <returns></returns>
    [HttpGet("{*remaining}")]
    public async Task<IActionResult> Download(
        [FromRoute] string remaining,
        [FromServices] IFileMange_Business fileBusiness)
    {
        var filePath = remaining.Replace("%2F", "//");

        var fileInfo = new FileInfo(filePath);
        var (ms, msg) = await fileBusiness.GetObjectStreamOss(
            filePath, Config.OssConfig.BucketName);

        //TODO 校验申请文件人的租户是否与资源所属租户一致

        if (msg == "ok")
        {
            return File(ms, FunOss.GetContentType(fileInfo.Name), fileInfo.Name);
        }
        else
        {
            return new JsonResult(new { msg });
        }
    }
}
