<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20240105
import { onMounted, ref, useTemplateRef } from 'vue';
import {
    NSpace,
    NButton,
    NInput,
    NForm,
    NModal,
    NGrid,
    NFormItemGi,
    NSelect,
    NInputNumber,
    NDynamicTags,
    NDatePicker,
} from 'naive-ui';
import moment from 'moment';
import { Add, Update } from '@request/Basic_Request.js';
import { executeRes } from '@utility/resultExecute.js';
import { translate } from '@utility/i18n.js';

const itemName = 'Sys_tenant';

const sheetData = ref({}); //表单数据
const dialogShow = ref(false); //表单显隐
const formRef = useTemplateRef('formRef'); //表单控件
const formState = ref('add'); //表单状态add,edit
//表单规则
const sheetRules = {
};

defineExpose({ open });
const emit = defineEmits(['sheetDone']);
const inPara = defineProps({});

onMounted(() => {});

//表单开启
function open(openType, data) {
    formState.value = openType;
    sheetData.value = data;
    dialogShow.value = true;
}

//表单完成
function formDone(res) {
    executeRes(res, translate, () => {
        emit('sheetDone');
        dialogShow.value = false;
    });
}

//提交
function btnSubmit() {
    formRef.value
        ?.validate((errors) => {
            if (!errors) {
                if (formState.value == 'add') {
                    Add(sheetData.value, itemName).then((res) => {
                        formDone(res);
                    });
                } else {
                    Update(sheetData.value, itemName).then((res) => {
                        formDone(res);
                    });
                }
            }
        })
        .catch((err) => {
            window.$message.warning(err[0][0].message);
        });
}

//取消
function btnCancel() {
    sheetData.value = {};
    dialogShow.value = false;
}
</script>

<template>
    <NModal
        :title="formState == 'add' ? translate.t('新增') : translate.t('编辑')"
        v-model:show="dialogShow"
        preset="card"
        :style="{ width: '60%' }"
        :segmented="{ footer: 'soft' }"
        :on-after-leave="btnCancel"
    >
        <NForm
            ref="formRef"
            :rules="sheetRules"
            :model="sheetData"
            label-placement="left"
            :label-width="120"
            require-mark-placement="right-hanging"
            size="medium"
        >
            <NGrid :cols="24" :x-gap="24">
                <div hidden>
                    <NFormItemGi :span="12" :label="translate.t('Id')" path="id">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('Id')"
                        v-model:value="sheetData.id"
                      />
                    </NFormItemGi>
                </div>
                    <NFormItemGi :span="12" :label="translate.t('编码')" path="code">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('编码')"
                        v-model:value="sheetData.code"
                      />
                    </NFormItemGi>
                    <NFormItemGi :span="12" :label="translate.t('名称')" path="title">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('名称')"
                        v-model:value="sheetData.title"
                      />
                    </NFormItemGi>
                <div hidden>
                    <NFormItemGi :span="12" :label="translate.t('创建账号')" path="create_account">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('创建账号')"
                        v-model:value="sheetData.create_account"
                      />
                    </NFormItemGi>
                </div>
                    <NFormItemGi :span="12" :label="translate.t('创建人姓名')" path="create_username">
                      <NInput
                        disabled
                        :placeholder="translate.t('请输入') + ' ' + translate.t('创建人姓名')"
                        v-model:value="sheetData.create_username"
                      />
                    </NFormItemGi>
                    <NFormItemGi :span="12" :label="translate.t('创建时间')" path="create_time">
                    <NDatePicker
                        disabled
                        style="width: 100%"
                        type="datetime"
                        v-model:value="sheetData.create_time"
                        :placeholder="translate.t('请输入') + ' ' + translate.t('创建时间')"
                    />
                    </NFormItemGi>
                <div hidden>
                    <NFormItemGi :span="12" :label="translate.t('更新账号')" path="update_account">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('更新账号')"
                        v-model:value="sheetData.update_account"
                      />
                    </NFormItemGi>
                </div>
                    <NFormItemGi :span="12" :label="translate.t('更新人姓名')" path="update_username">
                      <NInput
                        disabled
                        :placeholder="translate.t('请输入') + ' ' + translate.t('更新人姓名')"
                        v-model:value="sheetData.update_username"
                      />
                    </NFormItemGi>
                    <NFormItemGi :span="12" :label="translate.t('更新时间')" path="update_time">
                    <NDatePicker
                        disabled
                        style="width: 100%"
                        type="datetime"
                        v-model:value="sheetData.update_time"
                        :placeholder="translate.t('请输入') + ' ' + translate.t('更新时间')"
                    />
                    </NFormItemGi>
                    <NFormItemGi :span="12" :label="translate.t('备注')" path="remark">
                      <NInput
                        :placeholder="translate.t('请输入') + ' ' + translate.t('备注')"
                        v-model:value="sheetData.remark"
                      />
                    </NFormItemGi>
            </NGrid>
        </NForm>
        <template #footer>
            <NSpace justify="center">
                <NButton type="primary" @click="btnSubmit">{{ translate.t('提交') }}</NButton>
                <NButton type="primary" @click="btnCancel">{{ translate.t('取消') }}</NButton>
            </NSpace>
        </template>
    </NModal>
</template>
<style scoped></style>
