<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20241009
import { onMounted, ref, computed, useTemplateRef } from 'vue';
import { make_text_NButton, make_h_NSpace, h_tag } from '@utility/NaiveHComponent';
import { NSpace, NDataTable, NButton, NFormItem, NInput, NPagination } from 'naive-ui';
import { confirmDel } from '@common/message/confirmDel';
import moment from 'moment';
import Layout_UMD from '@common/layoutIndi/Layout_UMD.vue';
import { GetOne, Delete, MultiPagedSearch } from '@request/Basic_Request.js';
import sys_tenant_Form from './sys_tenant_Form.vue';
import { executeRes } from '@utility/resultExecute.js';
import { translate } from '@utility/i18n.js';

const itemName = 'Sys_tenant';

//检索条件
const queryInfo = ref({
    page: 1,
    pageSize: 15,
    code: '',
    create_account: '',
    update_account: '',
});

const tableLoading = ref(false); //加载中
const columns = ref([]); //显示的列
const tableData = ref([]); //表格数据
const totalCount = ref(0); //数据总数

const sys_tenant_FormRef = useTemplateRef('sys_tenant_FormRef'); //表单控件
const emit = defineEmits([]);
const inPara = defineProps({});

onMounted(() => {
    resetColumns();
    initData();
});

//初始化数据
function initData() {
    tableLoading.value = true;
    MultiPagedSearch(queryInfo.value, itemName)
        .then((res) => {
            tableData.value = res.datas;
            totalCount.value = res.totalCount;
            tableLoading.value = false;
        })
        .catch((err) => console.error(err));
}

//重置列
function resetColumns() {
    columns.value = [
        {
            title: computed(() => translate.t('序号')),
            align: 'center',
            width: '50px',
            render(row, index) {
                return index + 1;
            },
        },
        // {
        //     title: computed(() => translate.t('Id')),
        //     key: 'id',
        //     width: '100px',
        //     ellipsis: {
        //         tooltip: true,
        //     },
        //     sorter: 'default',
        // },
        {
            title: computed(() => translate.t('编码')),
            key: 'code',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
        },
        {
            title: computed(() => translate.t('名称')),
            key: 'title',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
        },
        //        {
        //            title: computed(() => translate.t('创建账号')),
        //            key: 'create_account',
        //            width: '100px',
        //            ellipsis: {
        //                tooltip: true,
        //            },
        //            sorter: 'default',
        //        },
        {
            title: computed(() => translate.t('创建人')),
            key: 'create_username',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
        },
        {
            title: computed(() => translate.t('创建时间')),
            key: 'create_time',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
            render(val, idx) {
                return moment(val.create_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
            },
        },
        //        {
        //            title: computed(() => translate.t('更新账号')),
        //            key: 'update_account',
        //            width: '100px',
        //            ellipsis: {
        //                tooltip: true,
        //            },
        //            sorter: 'default',
        //        },
        {
            title: computed(() => translate.t('更新人')),
            key: 'update_username',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
        },
        {
            title: computed(() => translate.t('更新时间')),
            key: 'update_time',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
            render(val, idx) {
                return moment(val.update_time).utc(true).format('YYYY-MM-DD HH:mm:ss.SSS');
            },
        },
        {
            title: computed(() => translate.t('备注')),
            key: 'remark',
            width: '100px',
            ellipsis: {
                tooltip: true,
            },
            sorter: 'default',
        },
        {
            title: computed(() => translate.t('操作')),
            width: 160,
            render(row) {
                let opts = [];
                opts.push(make_text_NButton(translate.t('编辑'), () => editRow(row)));
                opts.push(
                    make_text_NButton(translate.t('删除'), () =>
                        confirmDel(translate, () => delRow(row))
                    )
                );
                opts.push(make_text_NButton(translate.t('选中'), () => pickRow(row)));
                return make_h_NSpace(() => opts);
            },
        },
    ];
}

//高级查询
function queryList() {
    queryInfo.value.page = 1;
    queryInfo.value.pageSize = 15;
    initData();
}
//重置查询
function resetQuery() {
    queryInfo.value.page = 1;
    queryInfo.value.pageSize = 15;
    queryInfo.value.code = '';
    queryInfo.value.create_account = '';
    queryInfo.value.update_account = '';
    initData();
}

//新任务
function newTask() {
    sys_tenant_FormRef.value.open('add', {});
}

//编辑
function editRow(row) {
    GetOne(row.id, itemName).then((res) => {
        sys_tenant_FormRef.value.open('edit', res);
    });
}

//删除
function delRow(row) {
    Delete([row.id], itemName).then((res) => {
        executeRes(res, translate, () => {
            initData();
        });
    });
}

//翻页
function pageChange(page) {
    queryInfo.value.page = page;
    initData();
}
//改变页码
function pageSizeChange(pageSize) {
    queryInfo.value.page = 1;
    queryInfo.value.pageSize = pageSize;
    initData();
}

//选中行
function pickRow(row) {
    console.log(row.id);
}
</script>

<template>
    <Layout_UMD>
        <template #header>
            <NSpace justify="space-between">
                <!-- 高级查询 -->
                <NSpace>
                    <NFormItem :label="translate.t('编码')" label-placement="left">
                        <NInput v-model:value="queryInfo.code" />
                    </NFormItem>
                    <!-- <NFormItem :label="translate.t('创建账号')" label-placement="left">
                        <NInput v-model:value="queryInfo.create_account" />
                    </NFormItem> -->
                    <!-- <NFormItem :label="translate.t('更新账号')" label-placement="left">
                        <NInput v-model:value="queryInfo.update_account" />
                    </NFormItem> -->
                    <NButton type="primary" @click="queryList">{{ translate.t('查询') }}</NButton>
                    <NButton @click="resetQuery">{{ translate.t('重置') }}</NButton>
                </NSpace>
                <NButton type="primary" @click="newTask">
                    {{ translate.t('添加') }}
                </NButton>
            </NSpace>
        </template>
        <template #list>
            <NDataTable
                ref="table"
                bordered
                striped
                :loading="tableLoading"
                :columns="columns"
                :data="tableData"
                :style="{ height: `100%` }"
                flex-height
            ></NDataTable>
        </template>
        <template #footer>
            <NSpace>
                <NPagination
                    v-model:page="queryInfo.page"
                    v-model:page-size="queryInfo.pageSize"
                    :item-count="totalCount"
                    show-size-picker
                    :page-sizes="[15, 30, 45]"
                    :on-update:page="pageChange"
                    :on-update:page-size="pageSizeChange"
                    :prefix="
                        ({ itemCount }) => {
                            return translate.t('共') + ' ' + itemCount + ' ' + translate.t('条');
                        }
                    "
                />
            </NSpace>
        </template>
    </Layout_UMD>
    <sys_tenant_Form ref="sys_tenant_FormRef" @sheetDone="initData()"></sys_tenant_Form>
</template>
<style scoped></style>
