<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20220722
import { onMounted, ref, watch } from 'vue';
import { NSpace, NTabs, NTab, NMenu } from 'naive-ui';
import Theme from '../theme/theme.vue';
import HeaderButtons from '../headerButtons/HeaderButtons.vue';
import LogoButton from '../headerButtons/LogoButton.vue';
import LayoutIndi_OnlyHead from '../layoutIndi/LayoutIndi_OnlyHead.vue';
import type { MenuItem } from '../../types/MenuItem.d.ts';

const pageTitle = ref<string>(''); //页面标题
const menuOptions = ref<MenuItem[]>([]); //菜单数据

const currentMenuKey = ref('');
const menuInstRef = ref<any>(null);

const tabMenus = ref<MenuItem[]>([]); //Tab的Menu

const inPara = defineProps({
  platformTitle: String,
  menus: Object,
  menuSelectObj: Object,
});

defineExpose({ DoMenuRefresh }); // 将方法暴露出来

const emit = defineEmits(['menuSelected', 'menuTabKilled']);

onMounted(() => {
  menuOptions.value = inPara.menus as MenuItem[];
  pageTitle.value = inPara.platformTitle || '';
  tabMenus.value.push({
    code: 'Home',
    label: '首页',
  });
});

//监控菜单变化
watch(
  () => inPara.menus,
  (val) => {
    menuOptions.value = val as MenuItem[];
  },
  { deep: true }
);

//监控标题变化
watch(
  () => inPara.platformTitle,
  (val) => {
    pageTitle.value = val || '';
  }
);

//刷新菜单
function DoMenuRefresh() {
  if (inPara.menuSelectObj?.code && inPara.menuSelectObj?.label) {
    if (menuInstRef.value) {
      setTimeout(() => {
        currentMenuKey.value = inPara.menuSelectObj!.code;
        menuInstRef.value.showOption(currentMenuKey.value);
      }, 1);
    }
  }
}

//通知
function btnBell() {}

//搜索
function btnFind() {}

//选择菜单
function menuSelected(key: string, pickedVal: any) {
  window.localStorage.setItem('menu', key);
  emit('menuSelected', key);
  addTabMenu(pickedVal as MenuItem);
}

//点击Title
function titleClick() {
  window.localStorage.setItem('menu', 'Home');
  emit('menuSelected', 'Home');
  currentMenuKey.value = 'Home';
  setTimeout(() => {
    addTabMenu(inPara.menuSelectObj as MenuItem);
  }, 1);
}

//处理点选Tab
function handleUpdateTab(key: string) {
  window.localStorage.setItem('menu', key);
  currentMenuKey.value = key;
  emit('menuSelected', key);
}

//关闭Tab
function handleTabClose(key: string) {
  emit('menuTabKilled', key);
  let find = tabMenus.value.findIndex((val) => val.code == key);
  tabMenus.value.splice(find, 1);
  if (find > 0) {
    const prevTab = tabMenus.value[find - 1];
    if (prevTab) {
      handleUpdateTab(prevTab.code || '');
    }
  } else {
    if (tabMenus.value.length > 0) {
      const firstTab = tabMenus.value[0];
      if (firstTab) {
        handleUpdateTab(firstTab.code || '');
      }
    } else {
      titleClick();
    }
  }
}

//根据给定的menu对象，增加Tab
function addTabMenu(pickedVal: MenuItem) {
  let finds = tabMenus.value.filter((val) => val.code == pickedVal.code);
  if (finds.length == 0) {
    if (inPara.menuSelectObj?.code && inPara.menuSelectObj?.label) {
      tabMenus.value.push({
        label: pickedVal.label,
        code: pickedVal.code,
      });
    }
  }
}
</script>
<template>
  <Theme>
    <LayoutIndi_OnlyHead>
      <template #logo-title>
        <LogoButton :title="pageTitle" :showTitle="true" @menuSelected="titleClick"></LogoButton>
      </template>
      <template #menu-area>
        <NSpace class="navBar" justify="space-between" :align="'center'" :wrap-item="false">
          <div class="topMenu">
            <n-menu
              class="menu_container"
              ref="menuInstRef"
              v-model:value="currentMenuKey"
              :options="menuOptions"
              mode="horizontal"
              @update:value="menuSelected"
            />
          </div>

          <HeaderButtons @find="btnFind" @bell="btnBell"></HeaderButtons>
        </NSpace>
      </template>

      <template #tabs-content>
        <NTabs
          class="tabs-bar"
          :value="currentMenuKey"
          :closable="true"
          type="card"
          @update:value="handleUpdateTab"
          @close="handleTabClose"
        >
          <NTab v-for="tab in tabMenus" :name="tab.code || ''">
            {{ tab.label }}
          </NTab>
        </NTabs>
      </template>

      <template #main-content>
        <div id="layoutCard">
          <slot name="main">内容</slot>
        </div>
      </template>
    </LayoutIndi_OnlyHead>
  </Theme>
</template>
<style></style>
