<script setup lang="ts">
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 20260121
import { onMounted, ref, useTemplateRef } from 'vue';
import {
  NSpace,
  NButton,
  NInput,
  NForm,
  NModal,
  NGrid,
  NFormItemGi,
  NSelect,
  NInputNumber,
  NDynamicTags,
  NDatePicker,
} from 'naive-ui';
//import moment from 'moment';
import { Add, Update } from './req_menu.ts';
import { executeRes } from '@utility/resultExecute.ts';
import { translate } from '@utility/i18n.ts';

import type { Sys_menu_Class } from './sys_menu.d.ts';

// const itemName = 'Sys_menu';

const sheetData = ref<Sys_menu_Class>({} as Sys_menu_Class); //表单数据
const dialogShow = ref(false); //表单显隐
const formRef = useTemplateRef('formRef'); //表单控件
const formState = ref<'add' | 'edit'>('add'); //表单状态add,edit
//表单规则
const sheetRules = {};
defineExpose({ open });
const emit = defineEmits(['sheetDone']);
const inPara = defineProps({});

onMounted(() => {});

//表单开启
function open(openType: 'add' | 'edit', data: Sys_menu_Class, parent: Sys_menu_Class) {
  formState.value = openType;
  sheetData.value = data;
  if (parent && !!parent.id) {
    sheetData.value.parent_id = parent.id;
    sheetData.value.sys_code = parent.sys_code;
    sheetData.value.path = parent.path + '/';
    sheetData.value.alias = parent.alias + '/';
  }
  dialogShow.value = true;
}

//表单完成
function formDone(res: { status?: boolean; message?: string }) {
  executeRes(res, translate, () => {
    emit('sheetDone');
    dialogShow.value = false;
  });
}

//提交
function btnSubmit() {
  formRef.value
    ?.validate((errors: any) => {
      if (!errors) {
        if (formState.value == 'add') {
          Add(sheetData.value).then((res) => {
            formDone(res);
          });
        } else {
          Update(sheetData.value).then((res) => {
            formDone(res);
          });
        }
      }
    })
    .catch((err: Error) => {
      window.$message.warning(err.message);
    });
}

//取消
function btnCancel() {
  sheetData.value = {} as Sys_menu_Class;
  dialogShow.value = false;
}
</script>

<template>
  <NModal
    :title="formState == 'add' ? translate.t('新增') : translate.t('编辑')"
    v-model:show="dialogShow"
    preset="card"
    :style="{ width: '60%' }"
    :segmented="{ footer: 'soft' }"
    :on-after-leave="btnCancel"
  >
    <NForm
      ref="formRef"
      :rules="sheetRules"
      :model="sheetData"
      label-placement="left"
      :label-width="120"
      require-mark-placement="right-hanging"
      size="medium"
    >
      <NGrid :cols="24" :x-gap="24">
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('Id')" path="id">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('Id')"
              v-model:value="sheetData.id"
            />
          </NFormItemGi>
          <NFormItemGi :span="12" :label="translate.t('父级Id')" path="parent_id">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('父级Id')"
              v-model:value="sheetData.parent_id"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('排序')" path="sort">
          <NInputNumber
            style="width: 100%"
            :placeholder="translate.t('请输入') + ' ' + translate.t('排序')"
            v-model:value="sheetData.sort"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('系统编码')" path="sys_code">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('系统编码')"
            v-model:value="sheetData.sys_code"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('菜单编码')" path="code">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('菜单编码')"
            v-model:value="sheetData.code"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('菜单名称')" path="label">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('菜单名称')"
            v-model:value="sheetData.label"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('编码路径')" path="path">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('编码路径')"
            v-model:value="sheetData.path"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('名称路径')" path="alias">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('名称路径')"
            v-model:value="sheetData.alias"
          />
        </NFormItemGi>

        <!-- <NFormItemGi :span="12" :label="translate.t('组件地址')" path="component">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('组件地址')"
            v-model:value="sheetData.component"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('重定向地址')" path="redirect">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('重定向地址')"
            v-model:value="sheetData.redirect"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('图标地址')" path="icon">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('图标地址')"
            v-model:value="sheetData.icon"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('是否固定(10否11是)')" path="is_fixed">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('是否固定(10否11是)')"
            v-model:value="sheetData.is_fixed"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('是否缓存(10否11是)')" path="is_keep_alive">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('是否缓存(10否11是)')"
            v-model:value="sheetData.is_keep_alive"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('是否打开新页面(10否11是)')" path="is_open_new">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('是否打开新页面(10否11是)')"
            v-model:value="sheetData.is_open_new"
          />
        </NFormItemGi>
        <NFormItemGi
          :span="12"
          :label="translate.t('是否隐藏注册(菜单栏中不可见)(10否11是)')"
          path="is_hidden"
        >
          <NInput
            :placeholder="
              translate.t('请输入') + ' ' + translate.t('是否隐藏注册(菜单栏中不可见)(10否11是)')
            "
            v-model:value="sheetData.is_hidden"
          />
        </NFormItemGi>
        <NFormItemGi
          :span="12"
          :label="translate.t('只有一级子路由，父路由是否显示在菜单中(10否11是)')"
          path="is_always_show"
        >
          <NInput
            :placeholder="
              translate.t('请输入') +
              ' ' +
              translate.t('只有一级子路由，父路由是否显示在菜单中(10否11是)')
            "
            v-model:value="sheetData.is_always_show"
          />
        </NFormItemGi>

        <NFormItemGi :span="12" :label="translate.t('状态(10失效11正常)')" path="status">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('状态(10失效11正常)')"
            v-model:value="sheetData.status"
          />
        </NFormItemGi> -->
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('创建账号')" path="create_account">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('创建账号')"
              v-model:value="sheetData.create_account"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('创建人姓名')" path="create_username">
          <NInput
            disabled
            :placeholder="translate.t('请输入') + ' ' + translate.t('创建人姓名')"
            v-model:value="sheetData.create_username"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('创建时间')" path="create_time">
          <NDatePicker
            disabled
            style="width: 100%"
            type="datetime"
            v-model:value="sheetData.create_time"
            :placeholder="translate.t('请输入') + ' ' + translate.t('创建时间')"
          />
        </NFormItemGi>
        <div hidden>
          <NFormItemGi :span="12" :label="translate.t('更新账号')" path="update_account">
            <NInput
              :placeholder="translate.t('请输入') + ' ' + translate.t('更新账号')"
              v-model:value="sheetData.update_account"
            />
          </NFormItemGi>
        </div>
        <NFormItemGi :span="12" :label="translate.t('更新人姓名')" path="update_username">
          <NInput
            disabled
            :placeholder="translate.t('请输入') + ' ' + translate.t('更新人姓名')"
            v-model:value="sheetData.update_username"
          />
        </NFormItemGi>
        <NFormItemGi :span="12" :label="translate.t('更新时间')" path="update_time">
          <NDatePicker
            disabled
            style="width: 100%"
            type="datetime"
            v-model:value="sheetData.update_time"
            :placeholder="translate.t('请输入') + ' ' + translate.t('更新时间')"
          />
        </NFormItemGi>
        <NFormItemGi :span="24" :label="translate.t('备注')" path="remark">
          <NInput
            :placeholder="translate.t('请输入') + ' ' + translate.t('备注')"
            v-model:value="sheetData.remark"
          />
        </NFormItemGi>
      </NGrid>
    </NForm>
    <template #footer>
      <NSpace justify="center">
        <NButton type="primary" @click="btnSubmit">{{ translate.t('提交') }}</NButton>
        <NButton type="primary" @click="btnCancel">{{ translate.t('取消') }}</NButton>
      </NSpace>
    </template>
  </NModal>
</template>
<style scoped></style>
