/*
 * This file is generated by SwaggerCenter.
 * If you met a bug, please tell me, thanks!
 * wrx 20220101
 */
import request from '@utility/request';

export function getLanguages() {
    return request({
        url: `/T2ACore/Language/GetAllLanguage`,
        method: 'get',
    });
}
