/*
 * This file is generated by SwaggerCenter.
 * If you met a bug, please tell me, thanks!
 * wrx 20220101
 */
import request from '@utility/request';

export function getMenus() {
    return request({
        url: `/T2ACore/Menu/GetMenusTree`,
    });
}
export function getAdminMenus() {
    return request({
        url: `/T2ACore/Menu/GetAdminMenusTree`,
    });
}

export function getSysMenus() {
    return request({
        url: `/T2ACore/Menu/GetSysMenusTree`,
    });
}
