// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using MemoryPack;
using System.Collections.Generic;
using FluentValidation;

namespace PTools_PSilo;

/// <summary>
/// dict_silo验证类
/// cyl 20220826
/// </summary>
public class Dict_silo_Validate : AbstractValidator<Dict_silo_Class>
{
    /// <summary>
    /// 构造函数
    /// </summary>
    public Dict_silo_Validate()
    {
        //设置验证触发级别,遇到第一个失败即停止
        RuleLevelCascadeMode = CascadeMode.Stop;
        ClassLevelCascadeMode = CascadeMode.Stop;
        RuleFor(x => x.Silo_name)
            .NotNull().NotEmpty()
            .WithName("库型名称")
            .WithMessage("不可为空");

    }
}
