// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using MemoryPack;
using System.Collections.Generic;
using FluentValidation;

namespace PTools_PSilo;

/// <summary>
/// rfa_resource验证类
/// cyl 20220826
/// </summary>
public class Rfa_resource_Validate : AbstractValidator<Rfa_resource_Class>
{
    /// <summary>
    /// 构造函数
    /// </summary>
    public Rfa_resource_Validate()
    {
        //设置验证触发级别,遇到第一个失败即停止
        RuleLevelCascadeMode = CascadeMode.Stop;
        ClassLevelCascadeMode = CascadeMode.Stop;
        RuleFor(x => x.Rfa_code)
            .NotNull().NotEmpty()
            .WithName("族编码")
            .WithMessage("不可为空");
        RuleFor(x => x.File_name)
            .NotNull().NotEmpty()
            .WithName("族文件名称")
            .WithMessage("不可为空");

    }
}
