<script setup>
//This file is generated by Table2API.
//If you met a bug, please tell me, thanks!
//wrx 202200905
import { onMounted, ref } from 'vue';
import PageFrame from '@common/layout/FrameIndi_Classic.vue';
//import PageFrame from '@common/layout/FrameIndi_OnlyHead.vue';

import MainPage from '@common/MainPage.vue';
import Page404 from '@common/ResultPage/Page404.vue';

import GetMenu from './MenuData';

//此处引入页面组件
import Preface from './views/P000_Preface/Preface.vue';
import Colors from './views/P101_Colors/Colors.vue';
import Fonts from './views/P102_Fonts/Fonts.vue';
import Shadow from './views/P103_Shadow/Shadow.vue';

import Buttons from './views/P201_Buttons/Buttons.vue';
import Icons from './views/P202_Icons/Icons.vue';

import LayoutLeftRight from './views/P301_LayoutLeftRight/LayoutLeftRight.vue';
import LayoutUpDown from './views/P302_LayoutUpDown/LayoutUpDown.vue';
import SplitLine from './views/P303_SplitLine/SplitLine.vue';
import LayoutDemo1 from './views/P304_LayoutDemo1/LayoutDemo1.vue';
import LayoutDemo2 from './views/P305_LayoutDemo2/LayoutDemo2.vue';
import LayoutDemo3 from './views/P306_LayoutDemo3/LayoutDemo3.vue';
import LayoutDemo4 from './views/P307_LayoutDemo4/LayoutDemo4.vue';

import Breadcrumb from './views/P401_Breadcrumb/Breadcrumb.vue';
import Menu from './views/P402_Menu/Menu.vue';
import Pagination from './views/P403_Pagination/Pagination.vue';
import Steps from './views/P404_Steps/Steps.vue';

import DataTable from './views/P501_DataTable/DataTable.vue';
import Tree from './views/P502_Tree/Tree.vue';
import ScrollBar from './views/P503_ScrollBar/ScrollBar.vue';
import Empty from './views/P504_Empty/Empty.vue';
import Popover from './views/P505_Popover/Popover.vue';
import Tabs from './views/P506_Tabs/Tabs.vue';
import Tag from './views/P507_Tag/Tag.vue';
import TimeLine from './views/P508_TimeLine/TimeLine.vue';
import Collapse from './views/P509_Collapse/Collapse.vue';
import Card from './views/P510_Card/Card.vue';

import Selector from './views/P600_Selector/Selector.vue';
import Cascader from './views/P601_Cascader/Cascader.vue';
import DatePicker from './views/P602_DatePicker/DatePicker.vue';
import Form from './views/P603_Form/Form.vue';
import FormDemo from './views/P604_FormDemo/FormDemo.vue';
import Input from './views/P605_Input/Input.vue';
import InputNumber from './views/P606_InputNumber/InputNumber.vue';
import CheckBox from './views/P607_CheckBox/CheckBox.vue';
import Radio from './views/P608_Radio/Radio.vue';
import Switch from './views/P609_Switch/Switch.vue';
import Transfer from './views/P610_Transfer/Transfer.vue';
import Upload from './views/P611_Upload/Upload.vue';

import Drawer from './views/P701_Drawer/Drawer.vue';
import Message from './views/P702_Message/Message.vue';
import Modal from './views/P703_Modal/Modal.vue';
import Notification from './views/P704_Notification/Notification.vue';
import Popconfirm from './views/P705_Popconfirm/Popconfirm.vue';
import Progress from './views/P706_Progress/Progress.vue';
import Result from './views/P707_Result/Result.vue';

import {
    getMenuHome,
    executeMenuIcon,
    executeMenuLabel,
    killMenuChildren,
    searchMenuByKey,
} from '@common/layout/indexFunc';

import { translate } from '@utility/i18n.js';

const PageFrameRef = ref(null);

let initMenuHome = getMenuHome(translate.t('首页'));

const keepAliveArray = ref([]); //用于删除Tab取消菜单的持久化
const menus = ref([]);
const menuKey = ref('Home');
const menuObj = ref(initMenuHome);

onMounted(() => {
    window.addEventListener('hashchange', () => {
        updateMenu(location.hash.substring(1));
        if (PageFrameRef.value) {
            PageFrameRef.value.DoMenuRefresh();
        }
    });
    menus.value = GetMenu();
    killMenuChildren(menus.value);
    updateMenu(location.hash.substring(1));
    if (PageFrameRef.value) {
        PageFrameRef.value.DoMenuRefresh();
    }
});

//点选菜单
function menuSelected(key) {
    updateMenu(key);
    window.location.hash = key;
}

//更新menuKey,menuObj
function updateMenu(key) {
    if (key == 'Home' || key == '') {
        menuKey.value = key;
        menuObj.value = initMenuHome;
    } else {
        let tempMenuObj = searchMenuByKey(menus.value, key);

        if (Object.keys(tempMenuObj).length > 0) {
            menuKey.value = key;
            menuObj.value = tempMenuObj;
        } else {
            menuKey.value = '404';
            menuObj.value = {};
        }
    }
}

//通过tab的方式关闭菜单
function menuKilled(key) {
    keepAliveArray.value.push(key);
    setTimeout(() => {
        keepAliveArray.value = [];
    }, 1000);
}

//渲染菜单文字
function renderMenuLabel(val) {
    return executeMenuLabel(translate.t(val.label));
}

//渲染菜单图标
function renderMenuIcon(val) {
    return executeMenuIcon(val);
}
</script>
<template>
    <PageFrame
        ref="PageFrameRef"
        :platformTitle="translate.t('数字所UI规定')"
        :menus="menus"
        :menuSelectObj="menuObj"
        @menuSelected="menuSelected"
        @menuTabKilled="menuKilled"
        :renderMenuIcon="renderMenuIcon"
        :renderMenuLabel="renderMenuLabel"
    >
        <template v-slot:main>
            <!-- keep-alive中不可以有注释，同一条件下只允许有一个dom节点 -->
            <keep-alive :exclude="keepAliveArray">
                <MainPage v-if="menuKey == 'Home' || menuKey == ''" :msg="'Welcome'"></MainPage>
                <Preface v-else-if="menuKey == 'Preface'"></Preface>
                <Colors v-else-if="menuKey == 'Colors'"></Colors>
                <Fonts v-else-if="menuKey == 'Fonts'"></Fonts>
                <Shadow v-else-if="menuKey == 'Shadow'"></Shadow>
                <Buttons v-else-if="menuKey == 'Buttons'"></Buttons>
                <Icons v-else-if="menuKey == 'Icons'"></Icons>
                <LayoutLeftRight v-else-if="menuKey == 'LayoutLeftRight'"></LayoutLeftRight>
                <LayoutUpDown v-else-if="menuKey == 'LayoutUpDown'"></LayoutUpDown>
                <SplitLine v-else-if="menuKey == 'SplitLine'"></SplitLine>
                <LayoutDemo1 v-else-if="menuKey == 'LayoutDemo1'"></LayoutDemo1>
                <LayoutDemo2 v-else-if="menuKey == 'LayoutDemo2'"></LayoutDemo2>
                <LayoutDemo3 v-else-if="menuKey == 'LayoutDemo3'"></LayoutDemo3>
                <LayoutDemo4 v-else-if="menuKey == 'LayoutDemo4'"></LayoutDemo4>
                <Breadcrumb v-else-if="menuKey == 'Breadcrumb'"></Breadcrumb>
                <Menu v-else-if="menuKey == 'MenuSub'"></Menu>
                <Pagination v-else-if="menuKey == 'Pagination'"></Pagination>
                <Steps v-else-if="menuKey == 'Steps'"></Steps>
                <DataTable v-else-if="menuKey == 'DataTable'"></DataTable>
                <Tree v-else-if="menuKey == 'Tree'"></Tree>
                <ScrollBar v-else-if="menuKey == 'ScrollBar'"></ScrollBar>
                <Empty v-else-if="menuKey == 'Empty'"></Empty>
                <Popover v-else-if="menuKey == 'Popover'"></Popover>
                <Tabs v-else-if="menuKey == 'Tabs'"></Tabs>
                <Tag v-else-if="menuKey == 'Tag'"></Tag>
                <TimeLine v-else-if="menuKey == 'TimeLine'"></TimeLine>
                <Collapse v-else-if="menuKey == 'Collapse'"></Collapse>
                <Card v-else-if="menuKey == 'Card'"></Card>
                <Selector v-else-if="menuKey == 'Selector'"></Selector>
                <Cascader v-else-if="menuKey == 'Cascader'"></Cascader>
                <DatePicker v-else-if="menuKey == 'DatePicker'"></DatePicker>
                <Form v-else-if="menuKey == 'Form'"></Form>
                <FormDemo v-else-if="menuKey == 'FormDemo'"></FormDemo>
                <Input v-else-if="menuKey == 'Input'"></Input>
                <InputNumber v-else-if="menuKey == 'InputNumber'"></InputNumber>
                <CheckBox v-else-if="menuKey == 'CheckBox'"></CheckBox>
                <Radio v-else-if="menuKey == 'Radio'"></Radio>
                <Switch v-else-if="menuKey == 'Switch'"></Switch>
                <Transfer v-else-if="menuKey == 'Transfer'"></Transfer>
                <Upload v-else-if="menuKey == 'Upload'"></Upload>
                <Drawer v-else-if="menuKey == 'Drawer'"></Drawer>
                <Message v-else-if="menuKey == 'Message'"></Message>
                <Modal v-else-if="menuKey == 'Modal'"></Modal>
                <Notification v-else-if="menuKey == 'Notification'"></Notification>
                <Popconfirm v-else-if="menuKey == 'Popconfirm'"></Popconfirm>
                <Progress v-else-if="menuKey == 'Progress'"></Progress>
                <Result v-else-if="menuKey == 'Result'"></Result>
                <Page404 v-else></Page404>
            </keep-alive>
        </template>
    </PageFrame>
</template>
<style></style>
