/*
 * This file is generated by SwaggerCenter.
 * If you met a bug, please tell me, thanks!
 * wrx 20220101
 */
import request from '@utility/request.ts';

const NAMESPACE = import.meta.env.VITE_NAMESPACE;

export function checkLogin(account: string, password: string) {
  return request({
    url: '/' + NAMESPACE + '/Login',
    method: 'post',
    data: JSON.stringify({ account, password }),
  });
}
