// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx cyl 20221130

using System;
using SqlSugar;
using System.Linq;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// File_record业务类
/// </summary>
public class File_record_Business : IFile_record_Business
{
    //private readonly string CacheKey = "_File_record_AllData";
    //private readonly ICache CacheFunc; 
    private readonly IDBHelper dbHelper;
    private readonly string connId = "System";

    /// <summary>
    /// 构造函数
    /// </summary>
    public File_record_Business(IDBHelper inDI)
    {
        dbHelper = inDI;
        //CacheFunc = inDI2; 
    }


    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    public bool CreateTable()
    {
        try
        {
            dbHelper.GetDB("System").CodeFirst.InitTables<File_record_Class>();
            return true;
        }
        catch (Exception)
        {
            throw;
        }
    }

    /////////////////////////////////////////////////////////// 
    //  以下为生成代码
    /////////////////////////////////////////////////////////// 

    #region 查询
    /// <summary> 
    /// 获取所有实体 
    /// </summary> 
    /// <returns></returns> 
    public List<File_record_Class> GetAll()
    {
        var newData = dbHelper.QueryList<File_record_Class>(connId);
        return newData;
    }

    /// <summary>
    /// 构造树形File_record
    /// </summary>
    /// <returns></returns>
    public List<File_record_InTree> GetTree()
    {
        return dbHelper.QueryTreeList<File_record_Class, File_record_InTree>(connId,
            (x) => x.Children,
            (x) => x.Parent_id,
            default, null, x => x.Sort);
    }

    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    /// <returns></returns>
    public int GetAllCount()
    {
        return dbHelper.QueryCount<File_record_Class>(connId, (x) => true);
    }

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    /// <param name="pageIndex"></param>
    /// <param name="pageSize"></param>
    /// <returns></returns>
    public (int TotalCount, List<File_record_Class> Datas) GetAllPaged(int pageIndex, int pageSize)
    {
        return dbHelper.QueryPageList<File_record_Class>(connId,
            (x) => true, (x) => new
            {
                x.Id
            }, default, pageIndex, pageSize);
    }
    /// <summary> 
    /// 根据主键得到一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public List<File_record_Class> GetByIds(Guid[] inSet)
    {
        return dbHelper.QueryByIds<File_record_Class, Guid>(connId, inSet);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public File_record_Class GetOneFromAll(Guid id)
    {
        return GetAll().Find(p => p.Id == id);
    }

    /// <summary> 
    /// 根据主键从全部实体中获取单个实体 
    /// </summary> 
    /// <param name="id"></param> 
    /// <returns></returns> 
    public File_record_Class GetOne(Guid id)
    {
        return dbHelper.QueryOne<File_record_Class, Guid>(connId, id);
    }

    /// <summary>
    /// 根据Parent_id查询
    /// </summary>
    /// <param name="inSearch_Parent_id">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Parent_id(Guid inSearch_Parent_id)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.Parent_id == inSearch_Parent_id,
            (x) => x.Parent_id, default);
    }

    /// <summary>
    /// 根据Parent_id集合查询
    /// </summary>
    /// <param name="inSearch_Parent_ids">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Parent_ids(List<Guid> inSearch_Parent_ids)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_Parent_ids.Contains(x.Parent_id),
            (x) => x.Parent_id, default);
    }

    /// <summary>
    /// 根据File_name查询
    /// </summary>
    /// <param name="inSearch_File_name">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_File_name(string inSearch_File_name)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.File_name == inSearch_File_name,
            (x) => x.File_name, default);
    }

    /// <summary>
    /// 根据File_name集合查询
    /// </summary>
    /// <param name="inSearch_File_names">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_File_names(List<string> inSearch_File_names)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_File_names.Contains(x.File_name),
            (x) => x.File_name, default);
    }

    /// <summary>
    /// 根据File_ext查询
    /// </summary>
    /// <param name="inSearch_File_ext">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_File_ext(string inSearch_File_ext)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.File_ext == inSearch_File_ext,
            (x) => x.File_ext, default);
    }

    /// <summary>
    /// 根据File_ext集合查询
    /// </summary>
    /// <param name="inSearch_File_exts">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_File_exts(List<string> inSearch_File_exts)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_File_exts.Contains(x.File_ext),
            (x) => x.File_ext, default);
    }

    /// <summary>
    /// 根据Bucket_name查询
    /// </summary>
    /// <param name="inSearch_Bucket_name">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Bucket_name(string inSearch_Bucket_name)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.Bucket_name == inSearch_Bucket_name,
            (x) => x.Bucket_name, default);
    }

    /// <summary>
    /// 根据Bucket_name集合查询
    /// </summary>
    /// <param name="inSearch_Bucket_names">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Bucket_names(List<string> inSearch_Bucket_names)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_Bucket_names.Contains(x.Bucket_name),
            (x) => x.Bucket_name, default);
    }

    /// <summary>
    /// 根据Tenant查询
    /// </summary>
    /// <param name="inSearch_Tenant">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Tenant(string inSearch_Tenant)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.Tenant == inSearch_Tenant,
            (x) => x.Tenant, default);
    }

    /// <summary>
    /// 根据Tenant集合查询
    /// </summary>
    /// <param name="inSearch_Tenants">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Tenants(List<string> inSearch_Tenants)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_Tenants.Contains(x.Tenant),
            (x) => x.Tenant, default);
    }

    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Create_account(string inSearch_Create_account)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => x.Create_account == inSearch_Create_account,
            (x) => x.Create_account, default);
    }

    /// <summary>
    /// 根据Create_account集合查询
    /// </summary>
    /// <param name="inSearch_Create_accounts">查询字段</param>
    /// <returns></returns>
    public List<File_record_Class> SearchBy_Create_accounts(List<string> inSearch_Create_accounts)
    {
        return dbHelper.QueryListByClause<File_record_Class>(connId,
            (x) => inSearch_Create_accounts.Contains(x.Create_account),
            (x) => x.Create_account, default);
    }

    /// <summary>
    /// 高级检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<File_record_Class> MultiSearch(File_record_Search inSearchModel)
    {
        var exp = Expressionable.Create<File_record_Class>();
        exp.AndIF((inSearchModel.Parent_id != Guid.Empty), x => x.Parent_id.Equals(inSearchModel.Parent_id));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.File_name)), x => x.File_name.Contains(inSearchModel.File_name));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.File_ext)), x => x.File_ext.Contains(inSearchModel.File_ext));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Bucket_name)), x => x.Bucket_name.Contains(inSearchModel.Bucket_name));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Tenant)), x => x.Tenant.Contains(inSearchModel.Tenant));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        return dbHelper.QueryListByClause(connId, exp.ToExpression(), x => x.Id);
    }
    /// <summary>
    /// 高级模糊检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public List<File_record_Class> BlurSearch(File_record_Search inSearchModel)
    {
        var exp = Expressionable.Create<File_record_Class>();
        exp.OrIF((inSearchModel.Parent_id != Guid.Empty), x => x.Parent_id.Equals(inSearchModel.Parent_id));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.File_name)), x => x.File_name.Contains(inSearchModel.File_name));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.File_ext)), x => x.File_ext.Contains(inSearchModel.File_ext));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Bucket_name)), x => x.Bucket_name.Contains(inSearchModel.Bucket_name));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Tenant)), x => x.Tenant.Contains(inSearchModel.Tenant));
        exp.OrIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        return dbHelper.QueryListByClause(connId, exp.ToExpression(), x => x.Id);
    }

    /// <summary>
    /// 高级分页检索
    /// </summary>
    /// <param name="inSearchModel">查询类</param>
    /// <returns></returns>
    public (int, List<File_record_Class>) MultiPagedSearch(File_record_paged_Search inSearchModel)
    {
        var exp = Expressionable.Create<File_record_Class>();
        exp.AndIF((inSearchModel.Parent_id != Guid.Empty), x => x.Parent_id.Equals(inSearchModel.Parent_id));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.File_name)), x => x.File_name.Contains(inSearchModel.File_name));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.File_ext)), x => x.File_ext.Contains(inSearchModel.File_ext));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Bucket_name)), x => x.Bucket_name.Contains(inSearchModel.Bucket_name));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Tenant)), x => x.Tenant.Contains(inSearchModel.Tenant));
        exp.AndIF((!string.IsNullOrWhiteSpace(inSearchModel.Create_account)), x => x.Create_account.Contains(inSearchModel.Create_account));
        var res = dbHelper.QueryPageList(
            connId, exp.ToExpression(),
            x => x.Id, OrderByType.Desc,
            inSearchModel.Page, inSearchModel.PageSize);

        return res;
    }

    /// <summary>
    /// 获取去重的file_ext
    /// </summary>
    public List<string> Distinct_File_ext()
    {
        return dbHelper.QueryDistinct<File_record_Class, string>(connId, (x) => x.File_ext);
    }

    /// <summary>
    /// 获取去重的bucket_name
    /// </summary>
    public List<string> Distinct_Bucket_name()
    {
        return dbHelper.QueryDistinct<File_record_Class, string>(connId, (x) => x.Bucket_name);
    }

    /// <summary>
    /// 获取去重的tenant
    /// </summary>
    public List<string> Distinct_Tenant()
    {
        return dbHelper.QueryDistinct<File_record_Class, string>(connId, (x) => x.Tenant);
    }

    #endregion 查询

    #region 添加
    /// <summary> 
    /// 添加一个实体 
    /// </summary> 
    /// <param name="inEntity"></param> 
    /// <returns></returns> 
    public bool Add(File_record_Class inEntity)
    {
        return dbHelper.AddOne(connId, inEntity);
    }

    /// <summary> 
    /// 添加一批实体 
    /// </summary> 
    /// <param name="inSet"></param> 
    /// <returns></returns> 
    public int Add(List<File_record_Class> inSet)
    {
        return dbHelper.AddBatch(connId, inSet);
    }
    #endregion 添加

    #region 修改
    /// <summary> 
    /// 修改一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param> 
    /// <returns></returns> 
    public bool Update(File_record_Class inEntity)
    {
        return dbHelper.UpdateOne(connId, inEntity);
    }

    /// <summary> 
    /// 修改一批实体 
    /// </summary> 
    /// <param name="inSet">实体</param> 
    /// <returns></returns> 
    public int Update(List<File_record_Class> inSet)
    {
        return dbHelper.UpdateBatch(connId, inSet);
    }
    #endregion 修改

    #region 删除
    /// <summary> 
    /// 删除一个实体 
    /// </summary> 
    /// <param name="inEntity">实体</param>
    /// <returns></returns> 
    public bool Delete(File_record_Class inEntity)
    {
        return dbHelper.DeleteOne(connId, inEntity);
    }

    /// <summary> 
    /// 删除一批实体 
    /// </summary> 
    /// <param name="inSet">实体集合</param>
    /// <returns></returns> 
    public int Delete(List<File_record_Class> inSet)
    {
        return dbHelper.DeleteBatch(connId, inSet);
    }

    /// <summary> 
    /// 根据主键删除一个实体 
    /// </summary> 
    /// <param name="inId">主键</param>
    /// <returns></returns> 
    public bool DeleteById(Guid inId)
    {
        return dbHelper.DeleteOneById<File_record_Class, Guid>(connId, inId);
    }

    /// <summary> 
    /// 根据主键删除一批实体 
    /// </summary> 
    /// <param name="inArr">主键集合</param>
    /// <returns></returns> 
    public int DeleteByIds(Guid[] inArr)
    {
        return dbHelper.DeleteBatchByIds<File_record_Class, Guid>(connId, inArr);
    }
     
    /// <summary> 
    /// 根据主键软删除一个实体 
    /// </summary> 
    /// <param name="inId">主键</param>
    /// <returns></returns> 
    public int SoftDeleteById(Guid inId)
    {
        return dbHelper.UpdateSome<File_record_Class>(connId,
            x => new File_record_Class() { Is_delete = 11 },
            x => x.Id == inId);
    }

    /// <summary> 
    /// 根据主键软删除一批实体 
    /// </summary> 
    /// <param name="inArr">主键集合</param>
    /// <returns></returns> 
    public int SoftDeleteByIds(Guid[] inArr)
    {
        return dbHelper.UpdateSome<File_record_Class>(connId,
            x => new File_record_Class() { Is_delete = 11 },
            x => inArr.Contains(x.Id)); 
    }

    #endregion 删除
}
