// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;

namespace T2ACore;

/// <summary>
/// file_record业务类接口
/// </summary>
public interface IFile_record_Business
{
    /// <summary>
    /// 创建表
    /// </summary>
    /// <returns></returns>
    bool CreateTable();

    /////////////////////////////////////////////////////////// 
    //  以下为生成代码
    /////////////////////////////////////////////////////////// 

    /// <summary>
    /// 查询所有实体
    /// </summary>
    public List<File_record_Class> GetAll();
    /// <summary>
    /// 构造树形file_record
    /// </summary>
    /// <returns></returns>
    public List<File_record_InTree> GetTree();
    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    public int GetAllCount();

    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    public (int TotalCount, List<File_record_Class> Datas) GetAllPaged(int pageIndex, int pageSize);
    /// <summary>
    /// 查询多个实体
    /// </summary>
    public List<File_record_Class> GetByIds(Guid[] inSet);
    /// <summary>
    /// 通过检索全部实体查询一个实体
    /// </summary>
    public File_record_Class GetOneFromAll(Guid id);
    /// <summary>
    /// 查询一个实体
    /// </summary>
    public File_record_Class GetOne(Guid id);
    /// <summary>
    /// 根据Parent_id查询
    /// </summary>
    public List<File_record_Class> SearchBy_Parent_id(Guid inSearch_Parent_id);
    /// <summary>
    /// 根据Parent_id集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_Parent_ids(List<Guid> inSearch_Parent_ids);
    /// <summary>
    /// 根据File_name查询
    /// </summary>
    public List<File_record_Class> SearchBy_File_name(string inSearch_File_name);
    /// <summary>
    /// 根据File_name集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_File_names(List<string> inSearch_File_names);
    /// <summary>
    /// 根据File_ext查询
    /// </summary>
    public List<File_record_Class> SearchBy_File_ext(string inSearch_File_ext);
    /// <summary>
    /// 根据File_ext集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_File_exts(List<string> inSearch_File_exts);
    /// <summary>
    /// 根据Bucket_name查询
    /// </summary>
    public List<File_record_Class> SearchBy_Bucket_name(string inSearch_Bucket_name);
    /// <summary>
    /// 根据Bucket_name集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_Bucket_names(List<string> inSearch_Bucket_names);
    /// <summary>
    /// 根据Tenant查询
    /// </summary>
    public List<File_record_Class> SearchBy_Tenant(string inSearch_Tenant);
    /// <summary>
    /// 根据Tenant集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_Tenants(List<string> inSearch_Tenants);
    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    public List<File_record_Class> SearchBy_Create_account(string inSearch_Create_account);
    /// <summary>
    /// 根据Create_account集合查询
    /// </summary>
    public List<File_record_Class> SearchBy_Create_accounts(List<string> inSearch_Create_accounts);
    /// <summary>
    /// 高级查询
    /// </summary>
    public List<File_record_Class> MultiSearch(File_record_Search inSearchModel);

    /// <summary>
    /// 高级模糊查询
    /// </summary>
    public List<File_record_Class> BlurSearch(File_record_Search inSearchModel);

    /// <summary>
    /// 高级分页查询
    /// </summary>
    /// <param name="inSearchModel"></param>
    /// <returns></returns>
    (int, List<File_record_Class>) MultiPagedSearch(File_record_paged_Search inSearchModel);

    /// <summary>
    /// 获取去重的file_ext
    /// </summary>
    public List<string> Distinct_File_ext();

    /// <summary>
    /// 获取去重的bucket_name
    /// </summary>
    public List<string> Distinct_Bucket_name();

    /// <summary>
    /// 获取去重的tenant
    /// </summary>
    public List<string> Distinct_Tenant();


    /// <summary>
    /// 添加一个实体
    /// </summary>
    public bool Add(File_record_Class inEntity);
    /// <summary>
    /// 添加一批实体
    /// </summary>
    public int Add(List<File_record_Class> inSet);

    /// <summary>
    /// 修改一个实体
    /// </summary>
    public bool Update(File_record_Class inEntity);
    /// <summary>
    /// 修改一批实体
    /// </summary>
    public int Update(List<File_record_Class> inSet);

    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool Delete(File_record_Class inEntity);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int Delete(List<File_record_Class> inSet);
    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool DeleteById(Guid inId);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int DeleteByIds(Guid[] inArr);
    /// <summary>
    /// 软删除一个实体
    /// </summary>
    public int SoftDeleteById(Guid inId);
    /// <summary>
    /// 软删除一批实体
    /// </summary>
    public int SoftDeleteByIds(Guid[] inArr);



    /////////////////////////////////////////////////////////// 
    //  以下为新建代码
    /////////////////////////////////////////////////////////// 


}
