namespace PTools_PSilo;

// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230323

using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using System.Reflection;
using T2ACore;

/// <summary>
/// 启动验证
/// </summary>
public static class LaunchValidation
{
    /// <summary>
    /// 添加服务
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="mvc"></param>
    public static void AddValidationService(this WebApplicationBuilder builder, IMvcBuilder mvc)
    {
        //加验证FluentValidation
        //20221010 感谢yg提供的最新写法
        builder.Services.AddFluentValidationAutoValidation();
        builder.Services.AddValidatorsFromAssembly(Assembly.GetEntryAssembly());
        mvc.ConfigureApiBehaviorOptions(options =>
        {
            //使用自定义模型验证
            options.InvalidModelStateResponseFactory = (context) =>
            {
                context.HttpContext.Response.StatusCode = 400;
                var result = string.Join(Environment.NewLine, context.ModelState.Values
                    .SelectMany(v => v.Errors.Select(e => e.ErrorMessage)));
                var res = TPResponse.Bad("Validate Error", result, 400);
                return new JsonResult(res);
            };
        });
    }
}

