namespace PTools_PSilo;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230323

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Http;
using T2ACore;

/// <summary>
/// 启动Exception
/// </summary>
public static class LaunchException
{
    /// <summary>
    /// 使用全局Exception服务
    /// </summary>
    /// <param name="app"></param>
    public static void UseExceptionService(this WebApplication app)
    {
        app.UseExceptionHandler(new ExceptionHandlerOptions()
        {
            AllowStatusCode404Response = true,
            //ExceptionHandlingPath = "/Error",
            ExceptionHandler = async httpContext =>
            {
                var response = httpContext.Response;
                var feature = httpContext.Features
                    .Get<IExceptionHandlerPathFeature>();
                var (account, userName) = ScopeUser.GetUserAccountName();
                HttpLogMsg.LogError(feature.Error, httpContext, account, userName);
                var json = "500 - Internal Server Error";
                await httpContext.Response.WriteAsync(json);
            }
        });
    }

}

