namespace PTools_PSilo;
// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20230323

using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using T2ACore;

/// <summary>
/// 启动Cors
/// </summary>
public static class LaunchCors
{
    /// <summary>
    /// 添加Cors服务
    /// </summary>
    /// <param name="builder"></param>
    /// <param name="MyAllowSpecificOrigins"></param>
    public static void AddCorsService(this WebApplicationBuilder builder, string MyAllowSpecificOrigins)
    {
        builder.Services.AddCors(options =>
        {
            options.AddPolicy(
                MyAllowSpecificOrigins,
                builder => builder
                    .WithOrigins(Config.BaseConfig.WebAPI_Origins.Split(','))
                    .WithMethods(Config.BaseConfig.WebAPI_Methods.Split(','))
                    //.AllowCredentials() 考量Origin是否为*及是否前后端分离访问，二者不可共存
                    .AllowAnyHeader());
        });
    }
}

