// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using Newtonsoft.Json;
using MemoryPack;
using System.Collections.Generic;

namespace PTools_PSilo;

/// <summary>
/// template_silo检索类
/// </summary>
public partial class Template_silo_Search
{
    /// <summary>
    /// 库型名称{Search}{Validate:NotEmpty}
    /// </summary>
    public string Silo_name { get; set; }

    /// <summary>
    /// 族类型名{Search}
    /// </summary>
    public string Symbol_name { get; set; }

    /// <summary>
    /// 族文件地址{Search}{Frontend:FilePath}{Download}
    /// </summary>
    public string Rfa_path { get; set; }

    /// <summary>
    /// 创建账号{Search}
    /// </summary>
    public string Create_account { get; set; }

    /// <summary>
    /// 更新账号{Search}
    /// </summary>
    public string Update_account { get; set; }

    /// <summary>
    /// 当前类转为Json
    /// </summary>
    /// <returns></returns>
    public string ToJsonString()
    {
        return JsonConvert.SerializeObject(this);
    }

    /// <summary>
    /// 当前类转为MemoryPack Bin
    /// </summary>
    /// <returns></returns>
    public byte[] ToMemoryPackBin()
    {
        return MemoryPackSerializer.Serialize(this);
    }

}
/// <summary>
/// template_silo分页检索类
/// </summary>
public class Template_silo_paged_Search : Template_silo_Search
{

    /// <summary>
    /// 页码
    /// </summary>
    public int Page { get; set; }

    /// <summary>
    /// 单页数量
    /// </summary>
    public int PageSize { get; set; }
}
