// This file is generated by Table2API.
// If you met a bug, please tell me, thanks!
// wrx 20220126

using System;
using System.Collections.Generic;

namespace PTools_PSilo;

/// <summary>
/// template_silo业务类接口
/// </summary>
public interface ITemplate_silo_Business
{

    ///////////////////////////////////////////////////////////
    //  以下为生成代码
    ///////////////////////////////////////////////////////////


#if DEBUG
    /// <summary>
    /// Template_silo创建表
    /// </summary>
    /// <returns></returns>
    bool CreateTable();
#endif
    /// <summary>
    /// 查询所有实体
    /// </summary>
    public List<Template_silo_Class> GetAll();

    /// <summary>
    /// 获取所有实体,不使用缓存
    /// 数据量大时需注意
    /// </summary>
    /// <returns></returns>
    List<Template_silo_Class> GetAllWithoutCache();

    /// <summary>
    /// 获取全部数据数量
    /// </summary>
    public int GetAllCount();
    /// <summary>
    /// 直接从数据库获取分页全部数据
    /// </summary>
    public (int TotalCount, List<Template_silo_Class> Datas) GetAllPaged(int pageIndex, int pageSize);
    /// <summary>
    /// 查询多个实体
    /// </summary>
    public List<Template_silo_Class> GetByIds(Guid[] inSet);
    /// <summary>
    /// 通过检索全部实体查询一个实体
    /// </summary>
    public Template_silo_Class GetOneFromAll(Guid id);
    /// <summary>
    /// 查询一个实体
    /// </summary>
    public Template_silo_Class GetOne(Guid id);
    /// <summary>
    /// 根据Silo_name查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Silo_name(string inSearch_Silo_name);
    /// <summary>
    /// 根据Silo_name集合查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Silo_names(List<string> inSearch_Silo_names);
    /// <summary>
    /// 根据Symbol_name查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Symbol_name(string inSearch_Symbol_name);
    /// <summary>
    /// 根据Symbol_name集合查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Symbol_names(List<string> inSearch_Symbol_names);
    /// <summary>
    /// 根据Rfa_path查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Rfa_path(string inSearch_Rfa_path);
    /// <summary>
    /// 根据Rfa_path集合查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Rfa_paths(List<string> inSearch_Rfa_paths);
    /// <summary>
    /// 根据Create_account查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Create_account(string inSearch_Create_account);
    /// <summary>
    /// 根据Create_account集合查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Create_accounts(List<string> inSearch_Create_accounts);
    /// <summary>
    /// 根据Update_account查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Update_account(string inSearch_Update_account);
    /// <summary>
    /// 根据Update_account集合查询
    /// </summary>
    public List<Template_silo_Class> SearchBy_Update_accounts(List<string> inSearch_Update_accounts);
    /// <summary>
    /// 高级查询
    /// </summary>
    public List<Template_silo_Class> MultiSearch(Template_silo_Search inSearchModel);

    /// <summary>
    /// 高级模糊查询
    /// </summary>
    public List<Template_silo_Class> BlurSearch(Template_silo_Search inSearchModel);

    /// <summary>
    /// 高级分页查询
    /// </summary>
    public (int, List<Template_silo_Class>) MultiPagedSearch(Template_silo_paged_Search inSearchModel);

    /// <summary>
    /// 高级模糊分页查询
    /// </summary>
    public (int, List<Template_silo_Class>) BlurPagedSearch(Template_silo_paged_Search inSearchModel);


    /// <summary>
    /// 添加一个实体
    /// </summary>
    public bool Add(Template_silo_Class inEntity);
    /// <summary>
    /// 添加一批实体
    /// </summary>
    public int Add(List<Template_silo_Class> inSet);

    /// <summary>
    /// 修改一个实体
    /// </summary>
    public bool Update(Template_silo_Class inEntity);
    /// <summary>
    /// 修改一批实体
    /// </summary>
    public int Update(List<Template_silo_Class> inSet);

    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool Delete(Template_silo_Class inEntity);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int Delete(List<Template_silo_Class> inSet);
    /// <summary>
    /// 删除一个实体
    /// </summary>
    public bool DeleteById(Guid inId);
    /// <summary>
    /// 删除一批实体
    /// </summary>
    public int DeleteByIds(Guid[] inArr);
    /// <summary>
    /// 根据Silo_name删除
    /// </summary>
    /// <param name="inSearch_Silo_name">查询字段</param>
    /// <returns></returns>
    public int DeleteBy_Silo_name(string inSearch_Silo_name);

    /// <summary>
    /// 根据Silo_name集合删除
    /// </summary>
    /// <param name="inSearch_Silo_names">查询字段集合</param>
    /// <returns></returns>
    public int DeleteBy_Silo_names(List<string> inSearch_Silo_names);

    /// <summary>
    /// 根据Symbol_name删除
    /// </summary>
    /// <param name="inSearch_Symbol_name">查询字段</param>
    /// <returns></returns>
    public int DeleteBy_Symbol_name(string inSearch_Symbol_name);

    /// <summary>
    /// 根据Symbol_name集合删除
    /// </summary>
    /// <param name="inSearch_Symbol_names">查询字段集合</param>
    /// <returns></returns>
    public int DeleteBy_Symbol_names(List<string> inSearch_Symbol_names);

    /// <summary>
    /// 根据Rfa_path删除
    /// </summary>
    /// <param name="inSearch_Rfa_path">查询字段</param>
    /// <returns></returns>
    public int DeleteBy_Rfa_path(string inSearch_Rfa_path);

    /// <summary>
    /// 根据Rfa_path集合删除
    /// </summary>
    /// <param name="inSearch_Rfa_paths">查询字段集合</param>
    /// <returns></returns>
    public int DeleteBy_Rfa_paths(List<string> inSearch_Rfa_paths);

    /// <summary>
    /// 根据Create_account删除
    /// </summary>
    /// <param name="inSearch_Create_account">查询字段</param>
    /// <returns></returns>
    public int DeleteBy_Create_account(string inSearch_Create_account);

    /// <summary>
    /// 根据Create_account集合删除
    /// </summary>
    /// <param name="inSearch_Create_accounts">查询字段集合</param>
    /// <returns></returns>
    public int DeleteBy_Create_accounts(List<string> inSearch_Create_accounts);

    /// <summary>
    /// 根据Update_account删除
    /// </summary>
    /// <param name="inSearch_Update_account">查询字段</param>
    /// <returns></returns>
    public int DeleteBy_Update_account(string inSearch_Update_account);

    /// <summary>
    /// 根据Update_account集合删除
    /// </summary>
    /// <param name="inSearch_Update_accounts">查询字段集合</param>
    /// <returns></returns>
    public int DeleteBy_Update_accounts(List<string> inSearch_Update_accounts);


    ///////////////////////////////////////////////////////////
    //  以下为新建代码
    ///////////////////////////////////////////////////////////



}
